### ISSUE TITLE
Access denied on a get request (possibly Cloudlfare changed)

### ISSUE THREAD

**Issue by simonsruggi** [VeNoMouS/cloudscraper#103]
Getting 403 on a get request to this url:

link = 'https://www.bstn.com/p/new-balance-cw997-b-774511-50-3-159779'
headers = {
                    'Host': 'www.bstn.com',
                    'upgrade-insecure-requests': '1',
                    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
                    'sec-fetch-mode': 'navigate',
                    'sec-fetch-user': '?1',
                    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
                    'sec-fetch-site': 'same-origin',
                    'referer': link,
                    'accept-language': 'it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6,es;q=0.5',
                    }

scraper = cloudscraper.create_scraper(interpreter='nodejs')

response = scraper.get(link, headers = headers)

**Comment by VeNoMouS** [comment]
Headers should be constructed with an ordereddict... why dont you

```
scraper = cloudscraper.create_scraper(interpreter='nodejs', browser={'browser': 'chrome', 'mobile': False})

scraper.headers.update(
    {
        'User-Agent']: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
        'sec-fetch-mode': 'navigate',
        'sec-fetch-user': '?1',
        'Refer': link
    }
)
response = scraper.get(link)
```
