### ISSUE TITLE
CF reCaptcha - Low volume access

### ISSUE THREAD

**Issue by Rekrii** [VeNoMouS/cloudscraper#104]
I'm using a simple cloudscraper:

```python
import cloudscraper
url = "https://www.curseforge.com/wow/addons/censusplusclassic/files"
scraper = cloudscraper.create_scraper(browser={'browser': 'chrome', 'mobile': False}, debug=True)
page = scraper.get(url)
```

Everything has been going fine, and I have been using this for ~10 calls per week to curseforge (various URLs similar to the above). It has now started to throw up reCaptchas. 

I'm not sure if i should have been doing this a different way, or if the CF reCaptcha is pretty keen on flagging browsers/scraper-browsers.

Any help would be much appreciated, or fallback is using random proxies, but as it's more unreliable, would prefer not to.

Debug dump below:
```
> < GET /wow/addons/censusplusclassic/files HTTP/1.1
> < Host: www.curseforge.com
> < User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
> < DNT: 1
> < Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
> < Accept-Language: en-US,en;q=0.9
> < Accept-Encoding: gzip, deflate, br
> < sec-fetch-mode: navigate
> < sec-fetch-user: ?1
> < Referer: www.google.com
> <
> 
> > HTTP/1.1 403 Forbidden
> > Date: Sat, 07 Dec 2019 09:00:47 GMT
> > Content-Type: text/html; charset=UTF-8
> > Transfer-Encoding: chunked
> > Connection: close
> > CF-Chl-Bypass: 1
> > Set-Cookie: __cfduid=df4e14429873ed22a1a54d4420ad691161575709247; expires=Mon, 06-Jan-20 09:00:47 GMT; path=/; domain=.curseforge.com; HttpOnly
> > Cache-Control: no-cache
> > X-Frame-Options: SAMEORIGIN
> > Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> > Vary: Accept-Encoding
> > Server: cloudflare
> > CF-RAY: 54154faa3cdc4d2c-PER
> > Content-Encoding: gzip
```

**Comment by VeNoMouS** [comment]
Nothing is jumping out at me, i dont see any sort of real anti-bot stuff on that page...  

pretty sure from memory `CF-Chl-Bypass` means your hitting reCaptcha.... I don't see any google v2/v3 happening on the website... 

is it still occurring for you? I just tested it, and got a 200 fine...

**Comment by VeNoMouS** [comment]
Sorry I tell i lie.. i do see google reCaptcha calls in there.... from the site.. perhaps your ip address has been flagged?

**Comment by Rekrii** [comment]
This is a reCaptcha check, but this was personal use, at a very low frequency - about 10 calls per week. I was just surprised that this was flagged, that was all.
