### ISSUE TITLE
Not bypassing cloudflare page

### ISSUE THREAD

**Issue by leonswoosh** [VeNoMouS/cloudscraper#107]
When trying to bypass cloudflare / access the login page of https://www.consortium.co.uk,
I always get hit with the cloudflare page.

scraper = cloudscraper.create_scraper()

url = "https://www.consortium.co.uk/customer/account/login/"
r = scraper.get(url)
soup = BeautifulSoup(r.content, "html.parser")

Is it an issue on my side?

**Comment by dontshareyourname8** [comment]
That’s not an issue from your side as consortium is not under CF but protected by another protection.
