### ISSUE TITLE
print scraper.get does not work

### ISSUE THREAD

**Issue by darchon7** [VeNoMouS/cloudscraper#108]
your documentation says the simplest way to use cloudscraper is the following code but running it on windows 10 with python 3.7 results in an error:

    print scraper.get("http://javlibrary.com").content  # => "<!DOCTYPE html><html><head>..."
          ^
SyntaxError: invalid syntax

**Comment by VeNoMouS** [comment]
You must be new to python...

py2 you dont need to wrap print with ()

py3 its required...

``python
print(scraper.get("http://javlibrary.com").content )
```

**Comment by darchon7** [comment]
thanks for the quick response! yes just started learning the language.  :)

**Comment by VeNoMouS** [comment]
All good mate :), best of luck
