### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by darchon7** [VeNoMouS/cloudscraper#109]
so i'm getting 301 Moved Permanently when i attempt to use the following code:

```
import cloudscraper
scraper = cloudscraper.create_scraper()  # returns a CloudScraper instance
print(scraper.get("http://javlibrary.com").content)
```

**Comment by VeNoMouS** [comment]
Thanks for the heads up, I added a 302 fix in the dev branch the other day, as Cloudflare recently changed their challenge / solve procedure... I will add in 301 fix into the dev branch right now

**Comment by darchon7** [comment]
you're awesome!

**Comment by VeNoMouS** [comment]
Commited 687713700f35936b18c2fff485cc98390a7a7f5a in dev branch, which will resolve this issue.
