### ISSUE TITLE
cfscrape convension

### ISSUE THREAD

**Issue by quancore** [VeNoMouS/cloudscraper#11]
Does it have the same API with cfscraper? So that we can easily migrate it. If not, can you provide a short guide for conversion between two of them?

**Comment by VeNoMouS** [comment]
its almost exactly the same.. refer to the readme

**Comment by quancore** [comment]
Thank you for your answer.The only thing I can say please deploy the package on anaconda as well so that we do not need to handle problems for dependencies or other kinds of stuff.

**Comment by VeNoMouS** [comment]
@quancore do you not use `pip`?

**Comment by quancore** [comment]
I will try and give feedback. I suggest it in general.

**Comment by VeNoMouS** [comment]
Cheers mate, feedback is appreciated :)
