### ISSUE TITLE
Cant evade cloudflare

### ISSUE THREAD

**Issue by Dangeres** [VeNoMouS/cloudscraper#110]
Setted last version cloudscraper-1.2.16. Have some problem with evade cloudflare.

```
import requests, cloudscraper

ses = requests.session()

ses = cloudscraper.create_scraper(sess=ses)

data = ses.get('https://ggdrop.net').text
```

Thats code will return that page 
[so.txt](https://github.com/VeNoMouS/cloudscraper/files/3956320/so.txt)

**Comment by VeNoMouS** [comment]
Not sure why you're passing a requests session like for such a simple query..

```python
import requests, cloudscraper
ses = cloudscraper.create_scraper(debug=True)
ses.get('https://ggdrop.net')
```

and looking at the crappy 100% wrapped text file you have attached, this appears to be a firewall block at the ip level... 

```python
>>> ses = cloudscraper.create_scraper()
>>> ses.get('https://ggdrop.net')
<Response [200]>
>>>
```

Please supply a proper debug output, and code block it, don't file attach.

**Comment by VeNoMouS** [comment]
Actually testing what you had...

by submitting the session... https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L105 is not being implemented for some reason... so its using default requests headers

```python
>>> ses = cloudscraper.create_scraper(sess=ses, debug=True)
>>> data = ses.get('https://ggdrop.net').text
< GET / HTTP/1.1
< Host: ggdrop.net
< User-Agent: python-requests/2.22.0
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< Cookie: __cfduid=dbfd3f6552d46e6e1184ea852f345b4091576182307
<

> HTTP/1.1 403 Forbidden
> Date: Thu, 12 Dec 2019 20:25:37 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Cache-Control: max-age=15
> Expires: Thu, 12 Dec 2019 20:25:52 GMT
> X-Frame-Options: SAMEORIGIN
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 54426dba2be9ee9a-AKL
> Content-Encoding: gzip
>
```

**Comment by Dangeres** [comment]
> Not sure why you're passing a requests session like for such a simple query..

Just its a part of bigger codebase and i did it for simply understanding.

**Comment by VeNoMouS** [comment]
Nah its ok, I can confirm it is a problem

**Comment by VeNoMouS** [comment]
Ok.... problem is its kind of __by design__ for create_scraper()

you see after it creates the scraper object... it sets all items in the requests session you over the top of scraper object... so basically it inherits everything a user would set in the session... 

```python
    @classmethod
    def create_scraper(cls, sess=None, **kwargs):
        """
        Convenience function for creating a ready-to-go CloudScraper object.
        """
        scraper = cls(**kwargs)

        if sess:
            for attr in ['auth', 'cert', 'cookies', 'headers', 'hooks', 'params', 'proxies', 'data']:
                val = getattr(sess, attr, None)
                if val:
                    setattr(scraper, attr, val)

        return scraper
```

passing requests implies you know what you're already doing its kind of an `advance` technique...

so if you're wanting to pass a session you are going to have to setup the ciphers and headers correctly...

so... something like...

```python
>>> import requests
>>> import cloudscraper
>>> from cloudscraper.user_agent import User_Agent
>>> UA = User_Agent()
>>> ses = requests.session()
>>> ses.headers = UA.headers
>>> ses = cloudscraper.create_scraper(sess=ses, debug=True, cipherSuite=UA.cipherSuite)
>>> ses.headers
OrderedDict([('User-Agent', 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.7090.120 Mobile Safari/537.36'), ('DNT', '1'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'), ('Accept-Language', 'en-US,en;q=0.9'), ('Accept-Encoding', 'gzip, deflate')])
>>> ses.cipherSuite
['TLS_AES_128_GCM_SHA256', 'TLS_AES_256_GCM_SHA384', 'TLS_CHACHA20_POLY1305_SHA256', 'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-CHACHA20-POLY1305', 'AES128-GCM-SHA256', 'AES256-GCM-SHA384', 'AES256-SHA']
>>>
```

**Comment by Dangeres** [comment]
Why did it work in next week?

**Comment by VeNoMouS** [comment]
I assume you mean `last week`... perhaps your requests session headers were different? but nothing has changed in recent updates around this area, look at the commits....

**Comment by VeNoMouS** [comment]
Actually... its possible... that issue is from the SSL

https://github.com/VeNoMouS/cloudscraper/commit/5c2901a0c32e21974c693fcf3d5fc59574c4b2f6

**Comment by Dangeres** [comment]
> I assume you mean `last week`... perhaps your requests session headers were different? but nothing has changed in recent updates around this area, look at the commits....

Yep.



> Actually... its possible... that issue is from the SSL

Thanks for explain and your work.

**Comment by VeNoMouS** [comment]
Actually... i still don't think that is it...

```python
>>> ses = cloudscraper.create_scraper(sess=ses, debug=True, cipherSuite=':'.join([ssl._DEFAULT_CIPHERS, '!ECDHE+SHA','!AES128-SHA']))
>>> ses.cipherSuite
'DEFAULT:!aNULL:!eNULL:!MD5:!3DES:!DES:!RC4:!IDEA:!SEED:!aDSS:!SRP:!PSK:!ECDHE+SHA:!AES128-SHA'
>>> ses.get('https://ggdrop.net')
<Response [403]>
```

I know 100% for a fact that Cloudflare does in fact look at the headers and header order.

**Comment by Dangeres** [comment]
> Actually... i still don't think that is it...

But given example is working fine and im glad for that.

**Comment by VeNoMouS** [comment]
All good mate :)
