### ISSUE TITLE
Enable cookies message when accessing web

### ISSUE THREAD

**Issue by Fran008** [VeNoMouS/cloudscraper#114]
I am trying to access the web http://arenavision.us from a Google Cloud machine and it says "Enable cookies" since yesterday. It worked perfect before.

It's important to say that this web allows to access from anywhere except from Google Cloud machines. In Google Cloud machines it enables the recaptcha challenge, which I was able to surpass with deathbycaptcha parameters until yesterday.

I can't test if it works from a local PC because "http://arenavision.us" only performs CloudFlare limitations some specific days on local machines. Instead of that, it goes recaptcha permanently in Google Cloud, that is where I have found the bug.

**Comment by Fran008** [comment]
It's a bit strange, because if I do "wget http://arenavision.us" from the Google Cloud machine it says: 403 Forbidden

But I have now try it with a Google Machine in Europe and it works. It's working the "wget" and it's working the Cloudscraper. Maybe arenavision.us only blocks Google Cloud machines in USA.

I have tried with another instance, too, in Asia... and it's blocked aswell.

So I think it's maybe a problem of blocking IPs, not just a Cloudscraper problem. Thank you anyway.

**Comment by Fran008** [comment]
import cloudscraper
scraper = cloudscraper.create_scraper(interpreter='nodejs')
scraper.recaptcha={  'provider': 'deathbycaptcha',  'username': 'xxx',  'password': 'yyy'}
print (scraper.get("http://arenavision.us").content)

RuntimeError: Cloudflare has a restriction on your IP (Code 1020 Detected), you are BLOCKED.

**Comment by VeNoMouS** [comment]
can you test out the dev branch, as i discovered if you have openssl < 1.1.1 (for tls 1.3) and you're not sending TLS 1.3 ciphers... cloudflare returns back a 1020 block... 

or you can simply
```python
>>> import ssl
>>> ssl.OPENSSL_VERSION
```

and check your SSL version for me

**Comment by Fran008** [comment]
ssl.OPENSSL_VERSION

'OpenSSL 1.1.0k  28 May 2019'

**Comment by Fran008** [comment]
I have tried the following:

1-Install the branch version

wget https://www.openssl.org/source/openssl-1.1.1a.tar.gz
tar -zxf openssl-1.1.1a.tar.gz && cd openssl-1.1.1a
./config
make
sudo mv /usr/bin/openssl ~/tmp
sudo make install
sudo ln -s /usr/local/bin/openssl /usr/bin/openssl
sudo ldconfig
export LD_LIBRARY_PATH=/usr/local/lib


Now the result is:

import ssl
ssl.OPENSSL_VERSION

'OpenSSL 1.1.1a  20 Nov 2018'

But same results, not workin with arenavision.us

**Comment by Fran008** [comment]
https://github.com/openssl/openssl/issues/5845

This upgrade does not work either.

**Comment by VeNoMouS** [comment]
What is your python version?

**Comment by VeNoMouS** [comment]
FWIW python does not use the binary openssl, it uses the libraries that are compiled against it

**Comment by Fran008** [comment]
My Python version is 2.7.13-2

Python3 is 3.5.3-1

**Comment by Fran008** [comment]
I have externalized Cloudscraper into a Raspberry Pi 4, and no more executable from Google Cloud machine, so it is working now. I guess at the end is a Firewall rule excludig Google Cloud from arenavision.us

Thank you for everything!

PS: I will test later in a Google Machine with OpenSSL 1.1.1

**Comment by Fran008** [comment]
It works in Google Cloud with latest version! OpenSSL 1.1.0

**Comment by VeNoMouS** [comment]
Sorry I only got home late last night, glad you're up and running, so we can improve this moving forward for other users, can you please give me the *exact* version that worked for you, as you said 1.1.1a wasnt working.

**Comment by Fran008** [comment]
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.0l  10 Sep 2019'
>>>

**Comment by VeNoMouS** [comment]
hrrrrm...

Nothing major happened in 1.1.0 apart from bug fixes for vulns...

https://www.openssl.org/news/openssl-1.1.0-notes.html

as you can see in the bottom of 

https://www.openssl.org/news/openssl-1.1.1-notes.html

when things started really happening

So... unsure why yours suddenly started working..

**Comment by Fran008** [comment]
I'll make new tests.

I have created a NEW Google Cloud machine in which I installed the new version of OpenSSL, so... it could be that the new machine would not be IP blocked. In that case it has nothing to do with the version installed, simply it's free of IP ban.

**Comment by Fran008** [comment]
For some reason, it works now accessing to https instead of http, even with the older versions of OpenSSL

**Comment by Fran008** [comment]
JFYI it works with older versions of OpenSSL but only if there is not recaptcha challenge. It seems that in that case it needs the new OpenSSL.

Anyway, I have upgraded all the system in my "production" environment and it works perfect. I only have the old version in some tests machines.

**Comment by VeNoMouS** [comment]
https://github.com/VeNoMouS/cloudscraper/blob/dev/cloudscraper/__init__.py#L590-L597

**Comment by Fran008** [comment]
Thank you for the info. Depending on the access, if I am sure it works well in that page, I may need to deactivate that restriction sometimes.

**Comment by VeNoMouS** [comment]
I changed the dev branch to a print, the current production raises an exception

**Comment by Fran008** [comment]
So that's why it is working in my older machines: I have installed the dev branch in them, with older OpenSSL too. In that machines, it works well when there is UAM but it fails when there is reCaptcha.

Nevertheless, it is not important, because one day I will update all the system in that machines too, with production Cloudscraper and newer OpenSSL. Thank you!
