### ISSUE TITLE
Loop protection - We have tried to solve 3 times in a row

### ISSUE THREAD

**Issue by Fran008** [VeNoMouS/cloudscraper#116]
I get this error:

Python 2.7.16 (default, Apr  6 2019, 01:42:57)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper(interpreter='nodejs')
>>> scraper.recaptcha={  'provider': 'deathbycaptcha',  'username': 'xxx',  'password': 'yyy'}
>>> contenido=scraper.get("http://arenavision.us/p81/cloud/servers/362ws/saz/xz/d3/2/few/ef/23/2e/wdc/df/events-guide").content
RuntimeError: !!Loop Protection!! We have tried to solve 3 time(s) in a row.

SSL Version:
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.1c  28 May 2019'
>>>

**Comment by Fran008** [comment]
Same in python3:

Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper(interpreter='nodejs')
>>> scraper.recaptcha={ 'provider': 'deathbycaptcha', 'username': 'xxx', 'password': 'yyy'}
>>> contenido=scraper.get("http://arenavision.us/p81/cloud/servers/362ws/saz/xz/d3/2/few/ef/23/2e/wdc/df/events-guide").content
RuntimeError: !!Loop Protection!! We have tried to solve 3 time(s) in a row.

SSL Version:

import ssl
ssl.OPENSSL_VERSION
'OpenSSL 1.1.1c 28 May 2019'

**Comment by Fran008** [comment]
The last error was in Raspberry Pi 4. I have tested the same in a Google Cloud machine and I get this other one:

import cloudscraper
scraper = cloudscraper.create_scraper(interpreter='nodejs')
scraper.recaptcha={ 'provider': 'deathbycaptcha', 'username': 'xxx', 'password': 'yyy'}
contenido=scraper.get("http://arenavision.us/p81/cloud/servers/362ws/saz/xz/d3/2/few/ef/23/2e/wdc/df/events-guide").content

ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be
 a bug in the script.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.16-py2.7.egg/cloudscraper/__init__.py", line 195, i
n request
    resp = self.Challenge_Response(resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.16-py2.7.egg/cloudscraper/__init__.py", line 428, i
n Challenge_Response
    self.interpreter
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.16-py2.7.egg/cloudscraper/__init__.py", line 309, i
n IUAM_Challenge_Response
    getattr(e, 'message', e)
RuntimeError: Unable to parse Cloudflare anti-bots page: Missing Node.js runtime. Node is required and must be in t
he PATH (check with `node -v`).
Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install node
js-legacy` on some Debian-based systems.
(Please read the cloudscraper README's Dependencies section: https://github.com/VeNoMouS/cloudscraper#dependencies.
)

**Comment by Fran008** [comment]
Sorry, I have installed cloudscraper in Google Cloud machine, including all dependencies nodejs, and then... same error in Google Cloud:

RuntimeError: !!Loop Protection!! We have tried to solve 3 time(s) in a row.

**Comment by Fran008** [comment]
Just one consideration: this page is not permanent, so probably in one hour or two it will be UAM free

**Comment by Fran008** [comment]
SOLVED!!

I was directing to http:// and the real web was https://

Just a "s" in https... so important sometimes.

Thank you for your attention!

**Comment by Fran008** [comment]
Anyway... the page in http:// keeps serving the same error message. I have passed the problem because in https:// there is no UAM. So I don't know if the problem is relevant or it is not, in http://

**Comment by Fran008** [comment]
The web was http until today. Now it seems to have gone https and all my programs suddenly have started to fail. It was the reason.

But If I try to access the web the old way -- i.e. http -- then it fails with the mentioned error. Thanks for averything!

**Comment by VeNoMouS** [comment]
```
SOLVED!!

I was directing to http:// and the real web was https://```

Refer #117 , This also addresses your issue @Fran008
