### ISSUE TITLE
RuntimeError: Cloudflare reCaptcha detected

### ISSUE THREAD

**Issue by rodrigo-apoc** [VeNoMouS/cloudscraper#117]
Hi mate, I'm with the same issue of #85 

```
import cloudscraper, bs4

scraper = cloudscraper.create_scraper()
print(scraper.get("https://whereisxur.com/#xurinventory").content)
```

it returns 
`RuntimeError: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.`

Debug:
[debug.txt](https://github.com/VeNoMouS/cloudscraper/files/3999109/debug.txt)

Any ideia of how to solve this?

**Comment by VeNoMouS** [comment]
![image](https://user-images.githubusercontent.com/597545/71427050-6c6cf600-2718-11ea-9851-90f90cc6ca5c.png)

@rodrigo-apoc , it's Christmas day for me at the moment, but I've pushed something out into the dev branch that should help you..

3db00bb3fbbe26f5b75eac3460328ca7ede8d166

Let me know how you go

**Comment by rodrigo-apoc** [comment]
Thank you for your time and also sorry.
So, I just replaced the whole content of __init__.py to the new one you commited.
The result was a new error of OpenSSL version. 
I googled and tried some things then I realized that I should update my python (was using 3.7.5).
So I did it and install the cloudscraper of the master branch and now it's working fine. Not even needed to replace de init.py content. Don't know why.
Using latest python 3.8 right now.

**Comment by rodrigo-apoc** [comment]
also Merry Christmas my friend <3

**Comment by VeNoMouS** [comment]
3.7.5 should be new enough... i use 3.7.3 ;P

**Comment by VeNoMouS** [comment]
FWIW, I actually had 3.7.5 installed on windows as well.. I tested it, while there was an issue where it was looping with solving the challenge with the problem with http -> https , i didnt get an SSL too old issue... 

Anyway if I were you I would still use the dev branch `1.2.17` as this does address the protocol scheme switching issue.
