### ISSUE TITLE
RuntimeError: Sorry but the OpenSSL being used by this python install...

### ISSUE THREAD

**Issue by cxs1427** [VeNoMouS/cloudscraper#118]
RuntimeError: Sorry but the OpenSSL being used by this python install (OpenSSL 1.1.0j  20 Nov 2018) does not meet the minimum version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare.
Please tell me how to handle this problem?

**Comment by VeNoMouS** [comment]
If on windows/macosx upgrade your python as OpenSSL packaged with... if linux, upgrade your OpenSSL

**Comment by VeNoMouS** [comment]
I just double checked the latest 2.7.17 and that is shipped with OpenSSL 1.0.2s, I will have to remove that sanity check and replace it with a warning

**Comment by VeNoMouS** [comment]
@cxs1427 I've just pushed a fix in the dev branch under version `1.2.19` that should help you out, however... if you experience an increase in reCaptcha or Challenge looping, I will not provide any support.

**Comment by cxs1427** [comment]
@VeNoMouS thanks for your reply, i notice the newest version is 1.2.18 , where to find the 1.2.19?

**Comment by cxs1427** [comment]
ok, i've upgrade my python to the newest version and solve the problem,thank for your suggestions again !

**Comment by VeNoMouS** [comment]
1.2.19 is under the dev branch here on github... https://github.com/VeNoMouS/cloudscraper/tree/dev , to clone this you would do 

For example, if using git cli...

```
git clone -b dev https://github.com/VeNoMouS/cloudscraper.git
```

or 

![image](https://user-images.githubusercontent.com/597545/71461242-06659900-2814-11ea-8eda-e08a2c5eed65.png)

then you would install via...

```python setup.py install```


Out of curiosity, what OS and python version were you using before fixing?

**Comment by cxs1427** [comment]
win10 and python 3.7.2, 
ok,i've found the 1.2.19 and upgrade it, 
thanks for your job, the cloudscraper is awesome , it helps me a lot

**Comment by VeNoMouS** [comment]
Thanks man :)

**Comment by miigotu** [comment]
Man, cloudflare about to have a field day with this lol, so many things using python2 and no more updates to it x.X

**Comment by NoahCardoza** [comment]
Any idea why I might be getting this error with Python 3.7.0?

```
ION: The OpenSSL being used by this python install (OpenSSL 1.1.0h  27 Mar 2018) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
cloudscraper.exceptions.CloudflareCode1020: Cloudflare has blocked this request (Code 1020 Detected).```

**Comment by VeNoMouS** [comment]
its pretty much explains itself doesn't it? the openssl you're using with python is too old and doesnt have update todate SSL protocols/ciphers

**Comment by NoahCardoza** [comment]
From what I am finding on Google it seems that Python 3 is supposed to come with the correct version, no? OpenSSL on my Mac is at `LibreSSL 2.8.3` how would I get Python to use a newer version?

**Comment by NoahCardoza** [comment]
After further inspection it looks like `LibreSSL 2.8.3` doesn't support TLS 1.3 seeing as `openssl s_client -state -debug -msg -connect order.dominos.com:443 -tls1_3` throws an error.

**Comment by NoahCardoza** [comment]
Never mind, got it all sorted. If anyone finds this check out https://stackoverflow.com/questions/18752409/updating-openssl-in-python-2-7
