### ISSUE TITLE
Brotli

### ISSUE THREAD

**Issue by miigotu** [VeNoMouS/cloudscraper#121]
Honestly, I'm not sure if I need brotli support enabled? If I do, is there any possibility to include a pure python version such as https://github.com/pothos/brotlipython or other? Linked brotli version is platform and architecturally dependant

**Comment by VeNoMouS** [comment]
You can disable it via param, `allow_brotli` set to `False`...

However... that said.. i noticed I've included in the `requirements` file , I can amend that...

Setting the `allow_brotli` to `False` will remove `br` from the header `Accept-Encoding` when it sets up the user-agent, which the remote web server should honor...

Should `Brotli` content be returned https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L145-L157 deals with that and detects if the option is disabled.

**Comment by miigotu** [comment]
It might come down to me including yours and the other package and allowing either the user to select which one to use with each site, or automatically trying the other as a fallback. Cloudflare changes so fast it has to drive you insane.

**Comment by VeNoMouS** [comment]
LOL, yea them changing stuff is slightly annoying, but I normally fix it within a couple hours... I think though we have ironed out alot of the bugs, and we haven't needed to really change stuff much lately... the last major change was Cloudflare changing their IUAM challenge which I resolved pretty much straight away and for good measure I added in a new native python challenge solver (which is now the default) so there is no js dependency such as js2py, chakra, nodejs etc...

**Comment by miigotu** [comment]
Yeah I'm actually happy this is here, and it should work for what I need. cfscrape hasn't been updated in months, and there is a pr open that fixes the challenge but nada yet. I applied the patch to my source for now, but might change it up soon. keep doing what you do.

**Comment by VeNoMouS** [comment]
I saw that PR... 

![image](https://user-images.githubusercontent.com/597545/71940781-7f092400-321c-11ea-8c02-08c046f989d2.png)

That PR is horrible... to put it blunt, I can't see him accepting it into production

**Comment by VeNoMouS** [comment]
@miigotu brotli has been removed from requirements on the dev branch

**Comment by miigotu** [comment]
I'll see about switching after i get my tvdb3 changes into master and deal with any new issues it causes (57k lines changed x.X)
