### ISSUE TITLE
9kw.eu recaptcha Support

### ISSUE THREAD

**Issue by rix1337** [VeNoMouS/cloudscraper#124]
Please support 9kw.eu in this project. 

The service is capable of reliably solving recaptcha and I have an active account there.
Would be extremely convenient to use it for scraping.

More info: https://www.9kw.eu/

Let me know if I can help implementing this !

**Comment by VeNoMouS** [comment]
Yea I can add it... if i can decipher their API documentation... (IT SUCKS!!)

![image](https://user-images.githubusercontent.com/597545/72210878-c34f3980-3526-11ea-9d31-0b2c18fc00b9.png)

**Comment by rix1337** [comment]
+1 for the meme

Thank you. Their support appeared responsive to me, might help to shoot them a mail!

**Comment by VeNoMouS** [comment]
FWIW.... I managed to work out their API..

JESUS the documentation is a pile of fucking shit... that's 2 hours of my life I'm never getting back...

![image](https://user-images.githubusercontent.com/597545/72230053-fa514800-3617-11ea-89a7-a2e4ea9af817.png)

**Comment by rix1337** [comment]
Sounds awesome.

**Comment by VeNoMouS** [comment]
@rix1337 sorry been busy with... life ... lately.. 

i've implemented the request in dev branch for you, have a test / play and let me know if anything is missing.

**Comment by rix1337** [comment]
Will do asap. Life's the same for me. Thanks for implementing this.
