### ISSUE TITLE
CloudScraper Hangs

### ISSUE THREAD

**Issue by para-dise** [VeNoMouS/cloudscraper#128]
Hey, I've been having an issue with CloudScraper hanging without ever returning a response.

Test code:
```py
import cloudscraper

scraper = cloudscraper.create_scraper()
print(scraper.get("https://www.spigotmc.org/").text)
```

It seems to be stuck between request & sendChallengeResponse - therefore I believe CloudFlare might have updated their page once again.

Some traceback: [https://ghostbin.co/paste/phhyq](https://ghostbin.co/paste/phhyq)

**Comment by Fran008** [comment]
Same here

**Comment by VeNoMouS** [comment]
Let me have a look

**Comment by VeNoMouS** [comment]
Hrm... are you guys running latest version 1.1.20?

Because it worked straight away for me....

**Comment by VeNoMouS** [comment]
LOL `cloudscraper-1.1.5`... your using TOOOOO old version!!! upgrade

![image](https://user-images.githubusercontent.com/597545/73126453-8fd8d880-4017-11ea-8130-d6713d016b00.png)

**Comment by para-dise** [comment]
Whoops the old version always worked for me, rip.

Well, seems like it works after updating.

**Comment by VeNoMouS** [comment]
All good, Cloudflare updated their challenge in December just before christmas..
