### ISSUE TITLE
Add header entries for scraping

### ISSUE THREAD

**Issue by timvonwerne** [VeNoMouS/cloudscraper#129]
Currently working on a project which requires scraping a HTML site which is protected by Cloudflare to get a stream URL. Unfortunately the URL to the video is protected by another check for header entries like referrer, origin and x-requested-with (XMLHttpRequest).

Is it possible to achieve this with Cloudscraper or is there a solution to combine requests and cloudscraper together?

**Comment by VeNoMouS** [comment]
simply add the header with

```python
scraper = cloudscraper.create_scraper()
scraper.headers['x-requested-with'] = '....'
scraper.get('https://.....')
```

**Comment by timvonwerne** [comment]
Seems like something is wrong with my code. I already read that the order of the user agent is important to Cloudflare. Do you know if there is something like this for the order of headers?

```python
URL_MAIN = "https://example.com/"
scraper = cloudscraper.create_scraper()
scraper.headers.update({
  'X-Requested-With': 'XMLHttpRequest',
  'Referer': URL_MAIN,
  'Origin': URL_MAIN,
  'Host': URL_MAIN
})
html = scraper.get(URL_MAIN).text
```
The response in console from Cloudflare is "400 Bad Request"..

**Comment by VeNoMouS** [comment]
`I already read that the order of the user agent is important to Cloudflare. Do you know if there is something like this for the order of headers?` 

The what the what???

The `User-Agent" is a **header**....

And you pasting that, doesn't really answer me ANYTHING you'll have to supply me with the website if you expect me to help you? 

This is not a cloudscraper issue.
