### ISSUE TITLE
Broswers.json not found

### ISSUE THREAD

**Issue by EclipsedDev** [VeNoMouS/cloudscraper#130]
Hey, 
I'm using your cloudscraper and I'm always getting a error message like "browser.json" not found.
In my python IDE (PyCharm) everything works flawless but if I run it as exe after compiling with pyinstaller I always get that error. Would really appreciate help!
![Screenshot_1](https://user-images.githubusercontent.com/54325655/73609644-0e151c00-45d0-11ea-9a5f-959ae2a3dc16.png)

**Comment by VeNoMouS** [comment]
Since it appears to be putting it into its own directory on construction ... its most like a similar problem to 

https://github.com/VeNoMouS/cloudscraper/issues/72#issuecomment-524593291
