### ISSUE TITLE
No module named 2captcha

### ISSUE THREAD

**Issue by FlorianREGAZ** [VeNoMouS/cloudscraper#131]
No plan why that happens. Cant really say anything than that it works when I start it in my IDE, so maybe its a problem with PyInstaller again, maybe you have a good alternative, saw that you're normally not using it. I'm getting that error before or while making a post request.
https://prnt.sc/qxhmwl

**Comment by VeNoMouS** [comment]
yes, the problem is pyinstaller, as i posted in your other ticket you didnt respond too..

https://github.com/VeNoMouS/cloudscraper/issues/72#issuecomment-524593291

**Comment by FlorianREGAZ** [comment]
> yes, the problem is pyinstaller, as i posted in your other ticket you didnt respond too..
> 
> [#72 (comment)](https://github.com/VeNoMouS/cloudscraper/issues/72#issuecomment-524593291)

Ok thanks that helped, didnt see that you replied in time sry and thanks you very much for help and for you great module! :)
