### ISSUE TITLE
Loop protection

### ISSUE THREAD

**Issue by riccardolunardi** [VeNoMouS/cloudscraper#132]
Hi!
I'm trying to scrape this link: https://www.bstn.com/r/adidas-yeezy-boost-350-v2-non-static-122501
The link gives you a reCaptcha everytime you access it, no matter in which way, even in the normal browser. 
When my script try to access it, it gives an error 403 or a "Loop protection". 
I can scrape every other page of the website and I tested the reCaptcha solver on other website. I tried to activate the debug and I can see that I'm begin redirect to a link that seems correct (Ex. https://www.bstn.com/r/adidas-yeezy-boost-350-v2-159311?__cf_chl_captcha_tk__=a_lot_of_stuff), but it asks the reCaptcha again.
Here's my code:
```
scraper = cloudscraper.CloudScraper(
    browser={
        'browser': 'chrome',
        'desktop': True
    },
    debug=False,
    interpreter='nodejs',
    recaptcha={
        'provider': 'anticaptcha',
        'api_key': 'my_key'
    })

proxies = {
        "https": "my_proxy"
    }

r = scraper.get(page_link, timeout=10, proxies=proxies)

if r.status_code==200:
    page_content = BeautifulSoup(r.content, 'html.parser')
    #A lot of cool stuff
```

Things I tried:
- Checked correctness of the url scheme (http and https)
- Update all python3 module (urllib3, requests, etc...)
- Changing captcha service (I tried 2Captcha and AntiCaptcha

My OpenSSL version is 1.1.1d and I'm on Debian GNU/Linux 10 (buster) using Python 3.7.3
What am I doing wrong? Could be a cipher problem?

It's my first time posting an issue so let me know if I forgot something :)

EDIT: Actually I forgot something. Is `browser = { ... } ` enough for the headers? Or should I customize something?

**Comment by VeNoMouS** [comment]
Ok, 

So since your scraping sneakers.. im assuming you're doing a monitor, and your utilizing proxies... from memory im pretty sure the cfuid from CF is valid for the ip making the call.. using another ip will result in it to challenge again, my best suggestion is, if you're using proxies... store your cookies specific for that proxy after solve  away like in redis or a database or simply in a dict of dicts, and repopulate the cookies when required when using that specific proxy etc...

**Comment by riccardolunardi** [comment]
Thanks! I'm going to try it tomorrow.
One quick question to see if I understand correctly: when I cycle to a new proxy, if I set the correct CFUID and I already solved correctly a reCaptcha, I should not get it, right?

Also, I'm going to fix the 2 things you pointed out, thanks :)

**Comment by VeNoMouS** [comment]
> One quick question to see if I understand correctly: when I cycle to a new proxy, if I set the correct CFUID and I already solved correctly a reCaptcha, I should not get it, right?

That is correct.

**Comment by riccardolunardi** [comment]
I made the changed and now it works! Thank you :)

**Comment by VeNoMouS** [comment]
np :)

**Comment by kentavr009** [comment]
It is recommended to also send current proxy that you're using on the site to 2captcha.com with initial request, so the captcha can be solved from the same proxy as it was loaded. It will make solving process faster and and less likely you'll get "incorrect_captcha_sol" answer (sometimes Google does not accept ever correct answers and gives this error). Here is the official 2captcha statement regarding this: https://2captcha.com/2captcha-api#proxies

**Comment by VeNoMouS** [comment]
Actually the whole google reCaptcha solve thing has nothing to do with the "source address", its more of a timing attack, if you send it with a threshold of time after being solved it will be valid, google do not check the source address due to multi homed networks and or dynamic ips.

**Comment by kentavr009** [comment]
Well, we can't be 100% sure about Google's algorithms, but if there is even a slim chance that sending proxy would help somehow — we probably should use it. It won't make things worse at least.

**Comment by VeNoMouS** [comment]
Sorry guys, 

What I should've done was actually investigate further, I had a lot on when you guys filed this through,I have since investigated and confirmed its an actual bug... 

A fix is in currently in dev branch.

![image](https://user-images.githubusercontent.com/597545/74115144-8acc7980-4c12-11ea-9b9c-6f439c402c06.png)
