### ISSUE TITLE
pyinstaller: No Such file or directory

### ISSUE THREAD

**Issue by vadeex** [VeNoMouS/cloudscraper#137]
Hey I want to export my program, but I am getting the No such file or directory error for browsers.json.

I ran this command: 

```
pyinstaller main.py --onefile --add-data "C:\Users\vdx\AppData\Local\Programs\Python\Python36\Lib\site-packages\cloudscraper\user_agent\browsers.json;cloudscraper" --icon=favicon.ico
```

**Comment by VeNoMouS** [comment]
Do the whole directory, not just the browser.json because you'll also miss the dynamic loading interpreters 

Look at https://github.com/VeNoMouS/cloudscraper/issues/72#issuecomment-524593291 for reference

**Comment by VeNoMouS** [comment]
```
 --onefile --add-data "C:\Users\vdx\AppData\Local\Programs\Python\Python36\Lib\site-packages\cloudscraper\:cloudscraper"
```

also fwiw, its `:` not `;` , and in windows you might need to double escape `\` ie `C:\\Users\\vdx\\...`
