### ISSUE TITLE
Pyinstaller Error: No such file or directory

### ISSUE THREAD

**Issue by hope-console** [VeNoMouS/cloudscraper#138]
I'using cloudscraper on my script, when i pass it to exe and I start the .exe file, I get this error:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HWRUser\\AppData\\Local\\Temp\\_MEI46322\\cloudscraper\\user_agent\\browsers.json'

the error is there:
sess=requests.Session()
s=cloudscraper.create_scraper(sess=sess)

**Comment by VeNoMouS** [comment]
Ticket Dupe: https://github.com/VeNoMouS/cloudscraper/issues/137

**Comment by hope-console** [comment]
> Ticket Dupe: #137

thanks, it works
