### ISSUE TITLE
RuntimeError: !!Loop Protection!! ...

### ISSUE THREAD

**Issue by TheYoke** [VeNoMouS/cloudscraper#139]
Hi, I'm encountering a problem where I try to request a certain page and it keeps reporting error: `RuntimeError: !!Loop Protection!! We have tried to solve 3 time(s) in a row.` I tried to set `solveDepth` to a higher value, But I keep getting a really long URL.

The website I currently have a problem with is https://kissanime.ru
Below is the example code that reproduces the problem.
```
import cloudscraper
session = cloudscraper.create_scraper(solveDepth=3)
session.get('https://kissanime.ru/Anime/One-Piece/Episode-921?id=166565')
```

Currently, I'm fixing it by requesting a parent URL first (`https://kissanime.ru/Anime/One-Piece` in this case), But is there a better?.

**Comment by VeNoMouS** [comment]
As a work around... 

```
import cloudscraper
session = cloudscraper.create_scraper()
# Populate Cookies...
session.get('https://kissanime.ru/')

# Make request
response =session.get('https://kissanime.ru/Anime/One-Piece/Episode-921?id=166565').content
```

Let me look into why there is suddenly so many  issues with 302 lately....  you are the like the 4-5th person to raise the isue.

**Comment by VeNoMouS** [comment]
I just spotted something on CF side, let me investigate

**Comment by VeNoMouS** [comment]
Yea 100% found the issue, let me work out a fix that will work for everyone

**Comment by VeNoMouS** [comment]
There is currently a fix for this issue on the dev branch.

**Comment by TheYoke** [comment]
Thanks for fixing this so quick. I'll try the dev branch.
