### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by ResQNetM** [VeNoMouS/cloudscraper#14]
When i try to get https://chatmanager.pro, cloudscraper throws the error:
>js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function

And logging:
>ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.
ERROR:root:"https://chatmanager.pro" returned an error. Could not collect tokens.

Code:
>> import cloudscraper
> scraper = cloudscraper.create_scraper()
> scraper.get_tokens
<bound method CloudScraper.get_tokens of <class 'cloudscraper.CloudScraper'>>
> scraper.get_tokens('https://chatmanager.pro')

Other sites working

**Comment by VeNoMouS** [comment]
Works fine for me.... 

can you please `scraper.debug=True` before you `scraper.get_tokens()` and pastebin the whole debug please ... as i can't replicate the issue...

**Comment by valos** [comment]
I had the same error with the site https://japscan.to.
Adding 'br' in the Accept-Encoding header corrected the problem.
I hope this can help.

**Comment by VeNoMouS** [comment]
but BR is in the accept encoding... brolti is enabled by default as long as you have the brotli library installed?!

**Comment by VeNoMouS** [comment]
@valos can you debug for me with and without please?!

**Comment by VeNoMouS** [comment]
Also.. I've used japscan.to many times to test with, and never had an issue... can you guys give me debug logs... as if there is a problem i'd rather resolve it, than have undocumented hacky work arounds... cheers :)

**Comment by ResQNetM** [comment]
> Works fine for me.... in py2 and py3
> 
> can you please `scraper.debug=True` before you `scraper.get_tokens()` and pastebin the whole debug please ... as i can't replicate the issue...
Too strange, problem solved when i use torsocks, but japscan.to dont work, log for:
https://pastebin.com/AAZcsvYf

**Comment by VeNoMouS** [comment]
Thanks I'll go over the debug in awhile and get back to you if thats ok?

**Comment by valos** [comment]
Strange, it does not work anymore this morning. It is therefore random.
Several tries (a dozen), only one success.
Here is a debug log: https://pastebin.com/Q89rmsTA

**Comment by VeNoMouS** [comment]
Interesting... yea I can replicate under py3 not under py2... let me investigate.

**Comment by VeNoMouS** [comment]
hrrm this seems to be directly related to js2py... trying to work it out as if i use nodejs via

```
print (scraper.get_tokens('https://www.japscan.to/search/', interpreter = 'nodejs'))
```

it's fine

**Comment by VeNoMouS** [comment]
@valos , @ResQNetM from what I can determine, its something to do with js2py's jsunfuck code, we (@pro-src ) and myself thought it was resolved with @pro-src's PR to @PiotrDabkowski repo https://github.com/PiotrDabkowski/Js2Py/pull/157 

More investigation into what exactly is breaking is required... however I have put a bypass in place that does a manual jsunfuck before it sends it over to js2py... from my tests it resolves the issue you having, can you please let me know if this temporary resolves it for you.

Thanks.

**Comment by PiotrDabkowski** [comment]
One solution is to simply include the polyfills that define the missing JS functionality. One example could be `String.prototype.italics`, this is needed by jsfuck but because italics is not part of ECMA 5.1 it is not defined in Js2Py.

**Comment by VeNoMouS** [comment]
ok i traced it to 

```
Function("return escape")()(("")["italics"]())[2]
```

which translates to C

however.. it would appear the polyfill is not working for `"italics"`

**Comment by VeNoMouS** [comment]
Hi @PiotrDabkowski thanks for responding, sorry mate, turns out it's our issue not yours due to the polyfill, spent more time investigating.. its 2am for me atm ;(

**Comment by VeNoMouS** [comment]
@PiotrDabkowski in regards to

```python
js2py.eval_js('function italics (str) {return "<i>" + this + "</i>"; };Function("return escape")()("")["italics"]()')
```

any inside as to why that would not be working?

**Comment by PiotrDabkowski** [comment]
Your JS code is wrong. You need to add the method to the string prototype:

`js2py.eval_js('function italics (str) {return "<i>" + this + "</i>"; };String.prototype.italics=italics;Function("return escape")()("")["italics"]()')`

**Comment by pro-src** [comment]
@PiotrDabkowski is absolutely correct. `italics` is a `String.prototype` method. :laughing:

**Comment by pro-src** [comment]
@PiotrDabkowski Would you ever consider adding https://tc39.github.io/ecma262/#sec-additional-ecmascript-features-for-web-browsers ?

`italics (deprecated)` https://tc39.github.io/ecma262/#sec-string.prototype.italics
Similar methods: https://tc39.github.io/ecma262/#sec-additional-properties-of-the-string.prototype-object

**Comment by pro-src** [comment]
I'm going to be that the answer is no and for that reason. Abandon js2py for this purpose... lol

**Comment by pro-src** [comment]
Using `core-js` is an option as well, it can normalize the runtime: https://github.com/zloirock/core-js/tree/master/packages/core-js/es/string

Which is essentially what you'd have to use if CF ever starts using es6 features since babel uses `core-js` under the hood and the only way to run es6 in js2py is to transpile down to es5 using babel or similar.

**Comment by PiotrDabkowski** [comment]
You can even use js2py.eval_js6 to evaluate js6 code. It uses babel js translated to python via js2py.

**Comment by pro-src** [comment]
@PiotrDabkowski I know it's possible to compile https://unpkg.com/core-js-bundle@3.0.1/minified.js using js2py but I'm curious as to how you would then reuse the compiled code with js2py. Do you mind giving me an example?

**Comment by pro-src** [comment]
@PiotrDabkowski I just looked at the code for `translate_es6_to_es5` as an example. I've got it figured out.
