### ISSUE TITLE
How to enable javascript on the page i want to get contents from ?

### ISSUE THREAD

**Issue by IGlace** [VeNoMouS/cloudscraper#140]
I have a little problem here i want to get content from a specific website that use cloudflare of course, and that's not the problem here the libary get the contents of the website perfectly.
My problem is this website use javascript to get the data from database to show in it , so if the user doesnt use javascript when browsing on the website the content will not show. (I'm sorry my English is not very good so I hope I clarified my problem well).

Her is my code : 

`import cloudscraper`
`url = "##############"`
`scraper = cloudscraper.create_scraper(`
`     browser={`
`        'browser': 'chrome',`
`        'mobile': False`
`     },`
`     interpreter = 'nodejs',`
`)`
`html = scraper.get(url).text`

Although i'm using nodejs as interpreter ( i already finished installing nodejs in my computer and its working perfectly ), but that didn't make any difference and when i try to get the contents of this website this message appear in the html that i get using cloudscrapper `You must enable JavaScript to view the site content`.

Please help me how i can enable javascript on the page i want to get content from by the way the url of the website is `https://gmanga.me/mangas` 

The website is arabic so probably you will not understand the content of the page but you can easly notice if you try open this link on browser and then try scrape content from it using cloudscrapper , then you will notice that cloudscraper get the content of the website without any data.

**Comment by VeNoMouS** [comment]
use something like `js2py` or `nodejs` ...**cloudscraper does not run javascript for you**, it simply bypasses the IUAM protection on cloudfalre.

**Comment by IGlace** [comment]
Thank you for answering my question ^_^ ,  I will try to take your advice, and find a solution.
