### ISSUE TITLE
It does not work in http, it only works for https

### ISSUE THREAD

**Issue by Fran008** [VeNoMouS/cloudscraper#144]
I have downloaded latest version 1.2.23, and now it's not working with http.

I change the protocol to https and then it works.

**Comment by Fran008** [comment]
I have reverted to version 1.2.22 and then it works OK with both, http and https.

**Comment by Fran008** [comment]
I have made all my tests in the url "http://arenavision.live"

**Comment by VeNoMouS** [comment]
And a good morning to you too @Fran008 

Now... where to start...

a) I don't know WTF `KO` is...
b) 
```python
>>> scraper = cloudscraper.create_scraper(debug=True)
>>> response = scraper.get('http://arenavision.live')
< GET / HTTP/1.1
< Host: arenavision.live
< User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; SM-J737V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.92 Mobile Safari/537.36
< DNT: 1
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate, br
<

> HTTP/1.1 301 Moved Permanently
> Date: Mon, 17 Feb 2020 19:42:41 GMT
> Transfer-Encoding: chunked
> Connection: keep-alive
> Cache-Control: max-age=3600
> Expires: Mon, 17 Feb 2020 20:42:41 GMT
> Location: https://arenavision.live/
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 566a3ef24f86eea6-AKL
>
< GET / HTTP/1.1
< Host: arenavision.live
< User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; SM-J737V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.92 Mobile Safari/537.36
< DNT: 1
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate, br
<

> HTTP/1.1 200 OK
> Date: Mon, 17 Feb 2020 19:42:41 GMT
> Content-Type: text/html; charset=utf-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Set-Cookie: __cfduid=d098abbc4fde83dacbefe3a9eca16c2b81581968561; expires=Wed, 18-Mar-20 19:42:41 GMT; path=/; domain=.arenavision.live; HttpOnly; SameSite=Lax; Secure
> X-Powered-By: PHP/7.2.27
> X-Drupal-Cache: HIT
> Content-Language: es
> X-Frame-Options: SAMEORIGIN
> Cache-Control: public, max-age=0
> Last-Modified: Mon, 17 Feb 2020 19:36:03 GMT
> Expires: Sun, 19 Nov 1978 05:00:00 GMT
> Vary: Cookie,Accept-Encoding
> Vary: Accept-Encoding
> X-Content-Type-Options: nosniff
> X-Turbo-Charged-By: LiteSpeed
> CF-Cache-Status: DYNAMIC
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Server: cloudflare
> CF-RAY: 566a3ef29cddee92-AKL
> Content-Encoding: br
>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie6 ie" lang="es" dir="ltr"> <![endif]-->
<!--[if IE 7]>    <html class="ie7 ie" lang="es" dir="ltr"> <![endif]-->
<!--[if IE 8]>    <html class="ie8 ie" lang="es" dir="ltr"> <![endif]-->
<!--[if gt IE 8]> <!--> <html class="" lang="es" dir="ltr"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
<link rel="alternate" type="application/rss+xml" title="ArenaVision | We Love Sports RSS" href="https://arenavision.live/rss.xml" />
<link rel="shortcut icon" href="https://arenavision.live/sites/default/files/FAVICON_AV2015.png" type="image/png" />
```
```python
>>> response.url
'https://arenavision.live/'
>>>
```
c) The site doesn't even have Cloudflares IUAM
d) post your test code if you want me to validate what you're saying.

**Comment by VeNoMouS** [comment]
BTW.. I'm fine, how are you, thanks for asking :)

![image](https://user-images.githubusercontent.com/597545/74683103-bd86fb00-522c-11ea-9811-277225e745cc.png)

**Comment by Fran008** [comment]
First of all, I want to apologize for my lack of education. I respect you and your programming abilities much more than this... but my english is quite bad and I don't express with fluency.

Your program is AWESOME and I'd like to enjoy it for a long long time. I should be more polite in my posts, I'm sorry.

Secondly, I will test the issue later and I'll tell you if I can reproduce the error... or if I have been mistaken. Thank ypu for your patience.

**Comment by Fran008** [comment]
This is the code:

cookie_string=scraper.get_cookie_string("http://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list")
ERROR:root:"http://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list" returned an error. Could not collect tokens.
cloudflare_exceptions.Cloudflare_reCaptcha_Provider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.

If I do the calling in https then it works:

cookie_string=scraper.get_cookie_string("https://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list")
print (cookie_string)
('cf_clearance=f907a46b1b97cb58b956b8aff3c5639e7dac804d-1581974573-0-150; __cfduid=de836295e4e1f2db06f82c5c91bd355201581974573', u'Mozilla/5.0 (Android 3.0; Tablet; rv:50.0) Gecko/50.0 Firefox/50.0')

I hope it helps. But if you test it in a few hours the url will change. I will send you a new one if this happens. Thank you for wverything!

**Comment by Fran008** [comment]
Now I have downgraded to version 1.2.22 and results are OK with http:

cookie_string=scraper.get_cookie_string("http://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list")
>>> cookie_string=scraper.get_cookie_string("http://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list")
>>> print (cookie_string)
('cf_clearance=; __cfduid=dcf767a1b4e0a8cfbed0edbc56c73ea781581974978', u'Mozilla/5.0 (Linux; Android 6.0.1; XT1609 Build/MPIS24.241-2.35-1-17) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3236.6 Mobile Safari/537.36')

**Comment by VeNoMouS** [comment]
I asked for test code + debug..

```python3
import cloudscraper
cloudscraper.get_cookie_string(
    "http://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list", 
    debug=True
)
```

And paste the result of the failed...

**Comment by Fran008** [comment]
cookie_string=scraper.get_cookie_string("http://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list",debug=True)
< GET /p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list HTTP/1.1
< Host: arenavision.cc
< User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate, br
< DNT: 1
<

> HTTP/1.1 403 Forbidden
> Date: Mon, 17 Feb 2020 21:46:07 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> Set-Cookie: __cfduid=d8b1781d09f167c5e20d6d74c8c20050a1581975967; expires=Wed, 18-Mar-20 21:46:07 GMT; path=/; domain=.arenavision.cc; HttpOnly; SameSite=Lax; Secure
> CF-Chl-Bypass: 1
> Cache-Control: no-cache
> X-Frame-Options: SAMEORIGIN
> Vary: Accept-Encoding
> Alt-Svc: h2=":443"; ma=60
> Server: cloudflare
> CF-RAY: 566af3c24cd65496-MAD
> Content-Encoding: gzip
>
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>


<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>




</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> arenavision.cc</h2>
      </div>

      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">

              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list?__cf_chl_captcha_tk__=d63e3561834a7223395e9403a8b7022bcd75a93b-1581975967-0-AWtBkK-YNFPR33JR3HsMJiIz4JOEA1rRDeWfaQ0p7S9lglnOK5K7_PZ3OmVVSDJjrN8iq-GCVUohOXfCpA9lyQyd3LaPN4SaUl9RIVNTtIQt_fKdP5yhlrTVv3zesRWbO3Q4fTw1wqd9g21cFc5SMl0DxUSjIg4LK5Foz3zAMxMA8YVY30T6jRtXM2RckoPJxBcbAYaWGM-2W_8-aGtbnoFM6UqnjqVETMQ9IYD3r80hWdyJtW5NYuy4OV3aVqYspmrA-LJZ1UeSNPW-5JvInsTqCIMLhoorKJl8h6zD0cLdz8X5eXb6XKYoLl0udeaAttu8KrOJzr7d-l8mhv_3hOFlC74aI3x6xe0vvjRFmy1cO5XXIIiToUHJIW1TQuiZXZcvM2Rk9VHutzSnFVu1G6irJy-P478H6729HKYmznUWj2PJHturmQO5fsY4OeseW2Ex3HAlu1xI6FlrH9JGnLrU7pSGUbxaCwcPUmcFcYJ0ITL-sDAs5D7qfeCQBbZTg8-QDh44qgaHnmjmQs3s-PboG1irhJtXiv_NHYyeCzR8" method="POST" enctype="application/x-www-form-urlencoded">
  <input type="hidden" name="r" value="11ecc5ddd23fb7f1cb54ffc0fe1ea9f211d976c0-1581975967-0-ASjW3kb2y4EARf0BB6tON13Bol8ZdN9Zt8l1DrSs/yKSh5eiPW5Y4q8R2QVOCI60gvINzGjvT5ByrkpVgcc1IZly61r3S4d/9qJ6vHMVyWkmCZaEhbR2WAcvDmDOQZeIFLltiP6j/uCjjcyJm5NvAujsWc5VYsSAaoJhTmyjw6knbDuZz9R19/zEr7jqWGzqb0ODCepwASQKLH+soaGsISHxBUvufegikFkb41pFQPkZeABdWkkBz0isvHGLaIrizrVqIC0f0lgN3hdZF7aJ5yKqHfuqbMrMJ57wRqy4rmLsMUjFhYqAbHT4qKgMSjizN9T4bdBhlkScFrg+ZZmlDny33mTsFbVby9MFUoLMdcr9HTlIaCiDE46Y0rA2VaLB6GLnOKmmv0TcYbb4p2Z5QPOkqw5amkk5FwL1d3dMyBuTDlEzYIYZ/gQhjjmLpfalaeVQDRG4RkRPna7XaD2jr+hqrA1WquxA7To4ahe8xi+A2wy+1WjGP8ryHtFUU3Kz0l3SualGzLRzQeO7QqhhhUOiFZB2y3i0wJUOB+0b2z46OV1SBBbt6ePdJfpsiCZ67vQE/+2P2Wm8MOCKbTRImGve2Rt7P6O3R7D4Eeg0mW9N">
  <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="566af3c24cd65496" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
    <div><div style="width: 302px">
      <div>
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0" frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
      </div>
      <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
        <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
        <input type="submit" value="Submit"></input>
      </div>
    </div></div>
  </noscript>
</form>

                <script type="text/javascript">
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      if (!a()) return;

      window.addEventListener("message", handleMessage, false)

      function handleMessage(event) {
        if (event.data && event.data.type === 'results') {
          var f = document.getElementById('challenge-form');

          if (f) {
            addInput(f, 'bf_challenge_id', '10959');
            addInput(f, 'bf_execution_time', event.data.executionTimeMs);
            addInput(f, 'bf_result_hash', event.data.resultHash);
          }

          window.removeEventListener("message", handleMessage, false)
        }
      }

      function addInput(parent, name, value) {
        var input = document.createElement('input');
        input.type = 'hidden';
        input.name = name;
        input.value = value;
        parent.appendChild(input);
      }

      function withIframe(iframeContent) {
        var iframe = document.createElement('iframe');
        iframe.id = 'bf_test_iframe';
        iframe.style.visibility = 'hidden';
        document.body.appendChild(iframe);
        var doc = (iframe.contentWindow || iframe.contentDocument).document;
        doc.write(iframeContent);
        doc.close();
      }

      withIframe("<!DOCTYPE html>\n<html>\n  <head>\n    <title><\/title>\n\n    \n    \n    \n\n    <script src=\"https:\/\/ajax.cloudflare.com\/cdn-cgi\/scripts\/697236fc\/cloudflare-static\/bot-filter.js\"><\/__script__>\n    \n  <\/head>\n  <body>\n    <div><\/div>\n\n    <progress id=\"indeterminate\"><\/progress>\n    <progress id=\"removevalue\" value=\"0.5\"><\/progress>\n    <progress id=\"quarter\" value=\"1\" max=\"4\"><\/progress>\n    <progress id=\"largerthanmax\" value=\"2\"><\/progress>\n    <progress id=\"invalidmax\" value=\"1\" max=\"a\"><\/progress>\n    <progress id=\"negativemax\" value=\"1\" max=\"-1\"><\/progress>\n    <progress id=\"invalidvalue\" value=\"a\"><\/progress>\n    <progress id=\"negativevalue\" value=\"-1\"><\/progress>\n\n    \n  <\/body>\n<\/html>\n<script>test(function(){__c$1(indeterminate.value)});<\/__script__>".replace(/\/__script__/g, '/script'));

    }, false);
  })();
  </script>

              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">

                <span class="cf-no-screenshot"></span>

              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>

            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>


            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>


              <p data-translate="resolve_captcha_privacy_pass"> Another way to prevent getting this page in the future is to use Privacy Pass. You may need to download version 2.0 now from the <a href="https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/">Firefox Add-ons Store</a>.</p>


          </div>
        </div>
      </div>
      <div style="display: none;"><a href="http://sprengung.org/blocky.php?e=25">table</a></div>

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>566af3c24cd65496</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 88.27.211.77</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};


</script>


  <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/f8ce4a63/cloudflare-static/pic-chl.js"></script>
<script type="text/javascript">
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var f = document.getElementById('challenge-form');
      if (f) {
        var input = document.createElement('input');
        input.type = 'hidden';
        input.name = 'cv_chal_result';
        input.value = window.__CF$cv$chal([0x0f58915bd0,0xfd130a1f11]);
        f.appendChild(input);
        try {
           if (window.__CF$cv$fp) {
              var input = document.createElement('input');
              input.type = 'hidden';
              input.name = 'cv_chal_fp';
              input.value = window.__CF$cv$fp();
              f.appendChild(input);
           }
        } catch (e) { }
      }
    }, false);
  })();
</script>

</body>
</html>

ERROR:root:"http://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list" returned an error. Could not collect tokens.
cloudflare_exceptions.Cloudflare_reCaptcha_Provider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.

**Comment by VeNoMouS** [comment]
@Fran008 

What happens when you

```python
import cloudscraper
cloudscraper.get_cookie_string(
    "http://arenavision.cc/p81/cloud/servers/p2p/premium/p7/live/monday-17-february-2020-events-guide-list", 
    browser={
        'custom': 'Mozilla/5.0 (Android 3.0; Tablet; rv:50.0) Gecko/50.0 Firefox/50.0'
    },
    debug=True
)
```
'

**Comment by VeNoMouS** [comment]
Ahhh... FWIW..

if u use `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0` as custom UA i get reCaptcha... 

if i use custom UA of Mozilla/5.0 (Android 3.0; Tablet; rv:50.0) Gecko/50.0 Firefox/50.0`... so there is your issue... site is foring reCaptcha on specific UA's.

so there is your issue...

**Comment by Fran008** [comment]
Great! It works now.

It's a bit weird that in version 1.2.22 does not block the UA, but I guess you have changed something related to this in 1.2.23. You deserve my respect, my gratitude... and a coffee, why not? I will pay that as a donation ;)

**Comment by VeNoMouS** [comment]
No, its purely the random selector hitting a UA  that happens to be blocked by that website.

https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/__init__.py#L100-L111

**Comment by Fran008** [comment]
Thank you man!
