### ISSUE TITLE
Problem with anticaptcha

### ISSUE THREAD

**Issue by gbozzetti** [VeNoMouS/cloudscraper#149]
Hello,

I'm experiencing some problems with Deathbycaptcha service, all the requests end up with:

DeathByCaptcha: reCaptcha solve took to long to execute job id None, aborting.

I already contacted them and they told me everything was fine from their side.

Can you help me? 

cloudscraper version is 1.2.24

Thank you!!

**Comment by Fran008** [comment]
Just for your information, I'm working with deathcaptcha and latest version 1.2.24, and I think it's working fine for me... If I have some problem I will report.

**Comment by VeNoMouS** [comment]
The fact `jobID` is None, sounds like its having problems even logging the job with the API...

Let me investigate it try clean things up a bit.

**Comment by gbozzetti** [comment]
Thank you Venomous, anyway I tried again few minutes ago and I received back a response without error.... so I suspect it was a temporary problem of DeathByCaptcha service

**Comment by sociohacker** [comment]
Had same problems with DBC from time to time.
Switched to 2captcha, never had those problems here.
Maybe you should check them also is you considering to solve lots of captchas in the future.

**Comment by VeNoMouS** [comment]
Eye eye captain! ;P

**Comment by Fran008** [comment]
I am having this issue... with deathbycaptcha it's taking a long time sometimes and it ends up working bad.

But other times it works ok. Maybe 80% ok and 20% bad.

**Comment by VeNoMouS** [comment]
@Fran008 I can only try to improve on the client code... the actual solver stuff... if bad solve... you will have to take up with dbc...

I can try to improve on the report job if cf failure... however, that gets tricky when people start messing with headers and creating the problem themselves...

**Comment by Fran008** [comment]
I'm sorry, it could be my fault: I have put an external timeout in my program. Maybe increasing MY timeout will improve results. Thank you and keep up the good work!

**Comment by VeNoMouS** [comment]
@Fran008 thanks for the coffee ❤️ , I appreciate that

**Comment by Fran008** [comment]
My pleasure. And talking about my possible issue with deathcaptcha, I have installed the latest version (1.2.26) ... and it seems that it works much better. Thank you man!
