### ISSUE TITLE
ModuleNotFoundError: No module named 'cloudflare_exceptions'

### ISSUE THREAD

**Issue by joelcloud** [VeNoMouS/cloudscraper#154]
When i use:
`pyarmor pack -e " --onefile --icon logo.ico" script.py`

I get this:
```
import cloudflare_exceptions # noqa: E402
ModuleNotFoundError: No module named 'cloudflare_exceptions'
```

Any idea on how to fix this? Works before i use pyarmor. Thanks in advance.

**Comment by VeNoMouS** [comment]
pyarmor uses pyinstall for its packer right?

Refer to 
https://github.com/VeNoMouS/cloudscraper/issues/72#issuecomment-524593291

Also FWIW I am overhauling all the exceptions stuff, so this will change in the very close future.

**Comment by scullcandyz** [comment]
Had the exact same issue, it didnt find cloudscraper_exceptions (I think?) within __init__.py

you can just open up init.py and give the variable "cloudflare_exceptions"  some value as a quick fix.

**Comment by lz10081** [comment]
you can do from .exceptions import cloudflare_exceptions and add it as hidden import

**Comment by wulfixyt** [comment]
Still get the same error as @joelcloud... May someone explain me in depth what would fix it?

**Comment by joelcloud** [comment]
@lz10081 like this? 
```
from .exceptions import cloudflare_exceptions
import cloudflare_exceptions
```
Doesnt work for me..

**Comment by scullcandyz** [comment]
> @lz10081 like this?
> 
> ```
> from .exceptions import cloudflare_exceptions
> import cloudflare_exceptions
> ```
> 
> Doesnt work for me..

![image](https://user-images.githubusercontent.com/58109239/76248269-4cda6980-6241-11ea-8b10-db0648148106.png)

**Comment by joelcloud** [comment]
@scullcandyz 
`from .exceptions import cloudflare_exceptions`
`pyarmor pack -e " --onefile --icon gradient.ico --hidden-import cloudflare_exceptions" script.py`
Gives:
`ImportError: attempted relative import with no known parent package`
Am i doing something wrong?

**Comment by joelcloud** [comment]
@VeNoMouS I managed to get it to work by doing:
`pyarmor pack -e " --onefile --icon logo.ico --add-data='C:\Users\\joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cloudscraper\;cloudscraper'" script.py`
However now when im running im getting this as exception: 
`reCaptcha_Import_Error`
Do i need to add more data?

**Comment by VeNoMouS** [comment]
I've started to refactor the exceptions for you, give the dev branch a try...

**Comment by VeNoMouS** [comment]
> @VeNoMouS I managed to get it to work by doing:
> `pyarmor pack -e " --onefile --icon logo.ico --add-data='C:\Users\\joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cloudscraper\;cloudscraper'" script.py`
> However now when im running im getting this as exception:
> `reCaptcha_Import_Error`
> `Please install the python module 'polling' via pip or download it from https://github.com/justiniso/polling/`
> even though i have it installed
> Do i need to add more data?

make sure you --add-data for the polling package location

**Comment by VeNoMouS** [comment]
@lz10081 , @scullcandyz , @joelcloud ... have you guys tested dev branch?

**Comment by joelcloud** [comment]
> @lz10081 , @scullcandyz , @joelcloud ... have you guys tested dev branch?

Not sure if this is the correct way to do it, but i downloaded the ZIP from https://github.com/VeNoMouS/cloudscraper/tree/dev
and ran `python setup.py install` 

It gave the same as before:
> When i use:
> `pyarmor pack -e " --onefile --icon logo.ico" script.py`
> 
> I get this:
> 
> ```
> import cloudflare_exceptions # noqa: E402
> ModuleNotFoundError: No module named 'cloudflare_exceptions'
> ```
> 
> Any idea on how to fix this? Works before i use pyarmor. Thanks in advance.

**Comment by joelcloud** [comment]
> > @VeNoMouS I managed to get it to work by doing:
> > `pyarmor pack -e " --onefile --icon logo.ico --add-data='C:\Users\\joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cloudscraper\;cloudscraper'" script.py`
> > However now when im running im getting this as exception:
> > `reCaptcha_Import_Error`
> > `Please install the python module 'polling' via pip or download it from https://github.com/justiniso/polling/`
> > even though i have it installed
> > Do i need to add more data?
> 
> make sure you --add-data for the polling package location
> 
> pyarmor uses pyinstaller for the packager and its retarded when it comes to abstract modules such as ABC

Works now when I added  `--add-data` for the polling file location. Thanks for the help!

**Comment by VeNoMouS** [comment]
No, you have most likely python installed to a direct location if you are still getting

```
import cloudflare_exceptions # noqa: E402
ModuleNotFoundError: No module named 'cloudflare_exceptions'
```

as the dev branch doesn't even have `cloudflare_exceptions` anymore

**Comment by VeNoMouS** [comment]
The new refactored exceptions are in release 1.2.30

**Comment by BarryAl-Jawari** [comment]
@joelcloud I didn't managed to get it working by doing your way with:

`pyarmor pack -e " --onefile --icon logo.ico --add-data='C:\Users\\joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cloudscraper\;cloudscraper'" script.py` (of course I changed my values) but I do only get 

`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\`

did you managed to get this aswell?
