### ISSUE TITLE
Possible Bug with invisible captcha forms

### ISSUE THREAD

**Issue by bacanadian** [VeNoMouS/cloudscraper#155]
Hello,
I am trying to use cloudscraper to post a request on this page here: https://raffle.bstn.com/sacai-x-nike-ldwaffle-black-nylon-
However the final solve challenge just loops until an error. Maybe some of the issue comes from the recaptcha token value required inside the form as well? Although I am pretty sure the following error executes first: 
!!Loop Protection!! We have tried to solve 5 time(s) in a row.

Here are my headers:
```python
self.headers = {
            "accept": "application/json, text/plain, */*",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "en-US,en;q=0.9",
            "content-type": "application/json;charset=UTF-8",
            "cookie": "__cfduid=" + str(self.session.cookies["__cfduid"]),
            "origin": "https://raffle.bstn.com",
            "referer": "https://raffle.bstn.com/sacai-x-nike-ldwaffle-black-nylon-",
            "sec-fetch-dest": "empty",
            "sec-fetch-mode": "cores",
            "sec-fetch-site": "same-origin",
            "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36",
        }
```

Any help is appreciated

**Comment by VeNoMouS** [comment]
If you are getting loop protection, the cfuid you're using isn't valid ....

Are you using the same UA? if you change the UA the cfuid will not match from the setup and you will be challenge requested again...

Additionally, headers have to be in order for cloudflare.. if your hitting challenge.. your headers **have** to be in specific order, there for a `OrderedDict` is required
