### ISSUE TITLE
No exception or traceback when cloudscraper doesn't work

### ISSUE THREAD

**Issue by YuKangYin1997** [VeNoMouS/cloudscraper#156]
I can get html text from a cloudflare protected website successfully sometimes, but in other cases I cannot get html text from the same website, and there are no error or exception messages in the terminal even if I try to catch exceptions by `try exception` . I mean although this problem doesn't appear every time I run my code, it does appear sometimes with no reasons. Since I request this website very often, I don't know if it is because my IP has been blocked by the website?

```
def get_html_text(url):
    scraper = cloudscraper.create_scraper()  # returns a CloudScraper instance
    header = {
        'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36',
    }
    try:
        html_text = scraper.get(url, headers=header).content.decode('utf-8')
        return html_text
    except Exception as e:
        print(str(e))
        return None

def main():
    url = 'https://www.biovision.com/'
    return get_html_text(url)

main()
```

**Comment by VeNoMouS** [comment]
![image](https://user-images.githubusercontent.com/597545/76125967-cd8f3f00-6062-11ea-858a-89b8f819e278.png)

* You do not define user-agents that way 
* `.content.decode('utf-8')` should be replaced with `.text` as it already encoded in requests...
* it does raise an exception... should an exception arise...
* lastly... and most important of all... `https://www.biovision.com` isn't even behind IUAM on CF
