### ISSUE TITLE
Got an unexpected keyword argument 'interpreter'

### ISSUE THREAD

**Issue by marciusl** [VeNoMouS/cloudscraper#161]
Hello, I tried once scrapper with interpreter and it worked. Now after I try it second time it simply says it `Got an unexpected keyword argument 'interpreter'`

Code for using:
`scraper = cfscrape.create_scraper(interpreter='nodejs')`

Error line: `
  File "lib\site-packages\cfscrape\__init__.py", line 95, in __init__
    super(CloudflareScraper, self).__init__(*args, **kwargs)`

**Comment by VeNoMouS** [comment]
This isn't `cfscrape`.
