### ISSUE TITLE
cloudflare_exceptions.Cloudflare_Block: Cloudflare has blocked this request (Code 1020 Detected).

### ISSUE THREAD

**Issue by egonny** [VeNoMouS/cloudscraper#162]
It seems that CloudFlare changed something again. With the default setup and using 1.2.26, I get this when doing a basic test (with a local IP):

```
>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get("https://www.nakedcph.com")
cloudflare_exceptions.Cloudflare_Block: Cloudflare has blocked this request (Code 1020 Detected).
```

Likely related to the previous issue #153.

**Comment by lz10081** [comment]
Yup I just saw this too looks like is really easy to fix, the last update was added  self.ssl_context.set_alpn_protocols(['http/1.1']) looks like CF finded this bypass but undo what they did before so all you need to do is remove line 76 self.ssl_context.set_alpn_protocols(['http/1.1']) then you will pass :)

**Comment by VeNoMouS** [comment]
Just to confirm... and its a wild guess here...

you're both using ubuntu right?

**Comment by VeNoMouS** [comment]
mmm seems like some windows users are also affected... anyway removing ALPN and doing a release.

don't affect debian systems...

**Comment by egonny** [comment]
I had the issue on both Ubuntu and Windows, yeah

**Comment by VeNoMouS** [comment]
@egonny 1.2.28 pushed

Thanks for reporting the issue
