### ISSUE TITLE
Integrating with my PHP script

### ISSUE THREAD

**Issue by Goldenpistol** [VeNoMouS/cloudscraper#163]
Hi Sir. First of all thanks for creating this. Actually i've 0 knowledge about python and paid someone to install this on my Debian 9 server. Everything works fine executing the .py file in ssh - I saw the cookies and UA etc.

I've a PHP script that scraps a certain website. I want to ask how can I pass the  above cookies and UA to be used with on PHP script?

This is the code I have in the python script
```
import cloudscraper

cookie_value, user_agent = cloudscraper.get_cookie_string('https://www.somesites.com')

print('{}'.format(cookie_value))
```

**Comment by VeNoMouS** [comment]
Hi there, 

Thanks :heart: 

You have a couple ways you can go.... 

# First Way:

You could write a simple local REST API to act as a MITM.... perhaps something like i posted here https://github.com/VeNoMouS/cloudscraper/issues/152#issuecomment-591222951

# Second Way:

You could use something https://github.com/KyranRana/cloudflare-bypass but reading the Issue tickets, its broken.

**Comment by Goldenpistol** [comment]
Hi Venom, yes I'm doing this via cURL.

Is there a possibility for you to help me with this? Like via skype etc

**Comment by VeNoMouS** [comment]
Sorry but no.

I don't have the time to stackoverflow every ticket request, and my time is money, if i helped in-depth every single person who asked a simplistic question i'd never get anything done.

I have given you a possible solution in the "first way" that is most likely to solve your issue...

**Comment by Goldenpistol** [comment]
Ok i'll figure out myself. But can I ask how do I use a fixed user agent? I tried the following but every time I run the script different ua as printed

`import cloudscraper

scraper = cloudscraper.create_scraper(
    browser={
        'custom': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36'
    }
)

cookie_value, user_agent = scraper.get_cookie_string('https://www.wdupload.com/user/login')

print('{}'.format(user_agent))
print('$$$')
print('{}'.format(cookie_value))`

**Comment by VeNoMouS** [comment]
```
import cloudscraper

cookie_value, user_agent = cloudscraper.get_cookie_string(
    'https://website.com',
    browser={
        'custom': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36'
    }
)

print('{}'.format(user_agent))
print('$$$')
print('{}'.format(cookie_value))
```
