### ISSUE TITLE
first request doesen't work

### ISSUE THREAD

**Issue by hope-console** [VeNoMouS/cloudscraper#166]
I'm making a request to this site: https://www.slamjam.com and i get the waiting page but the second time that I make the same request in the same session i get response 200
There is an example of my code:

header={
                    'authority': 'www.slamjam.com',
                    'scheme': 'https',
                    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
                    'accept-encoding': 'gzip, deflate, br',
                    'accept-language': 'it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7',
                    'cache-control': 'max-age=0',
                    'sec-fetch-dest': 'document',
                    'sec-fetch-mode': 'navigate',
                    'sec-fetch-site': 'same-origin',
                    'sec-fetch-user': '?1',
                    'upgrade-insecure-requests': '1',
                    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',
                }

session=request.Session()
s=cloudscraper.create_scraper(sess=session, browser={'browser': 'chrome', 'mobile': False}, interpreter='nodejs')

t=0
while t == 0:
    r=s.get('https://www.slamjam.com', headers=header)
    print(r)
    if r.status_code == 200:
        t=1

**Comment by VeNoMouS** [comment]
Ok....  lets get a couple simple things out of the way first and get you a little educated..

# HTTP/2 Pseudo Headers

* authority
* scheme

The above are http/2 pseudo headers, they are not part of the http/1.1 framework .. https://http2.github.io/http2-spec/#rfc.section.8.1.2.3 , there is **ZERO** requirement for them unless you're using h/2

# Fundamental Code Structure Problems

Onto the next lot of problems...

FWIW: You are setting everything up wrong .. if you RTFM you would understand that a more viable approach would have been something more along the lines of..

```python
import cloudscraper

s=cloudscraper.create_scraper(
    browser={
        'custom': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36'
    }
)

while True:
    r = s.get('https://www.slamjam.com')
    print(r)
    if r.status_code == 200:
        break

```

# Lastly: Ordered Dictionaries

Cloudflare expects its headers to be in a specific order, by using a standard dictionary it does not hold its order, you need to use an OrderedDict from collections... but the create_scraper does this all for you....

**Comment by hope-console** [comment]
got it, thank you very much, I didn't mean to sound rude sorry

**Comment by VeNoMouS** [comment]
No , you sound rude (well.. you didnt say hi or nothign ;P), its more the fact that I'm not **stackoverflow**... instead its time out of my day to respond to tickets because people don't bother to read the documentation 🙉, and yea that gets frustrating.

But anyway... I'm really glad its working for you mate, least you can move forward 😄, enjoy the rest of your day ❤️
