### ISSUE TITLE
Cloudflare 403 / 1020 Error

### ISSUE THREAD

**Issue by robertfilam** [VeNoMouS/cloudscraper#168]
I've been getting 403 on many cloudflare sites for a couple of hours, everything was working fine before.
Cloudflare probably changed something, this is just an alert for you.

Btw I use Cloudflare daily, thank you for working on this. I'll donate something for sure!

**Comment by VeNoMouS** [comment]
What python version && OS?

**Comment by robertfilam** [comment]
Python 3.8.1 on macos, python 3.8.something on ubuntu 18
I mainly tried on https://www.slamjam.com/

**Comment by VeNoMouS** [comment]
FWIW it appears just to be cipher issue , i'll push out an out date in a few hours, just busy atm

**Comment by robertfilam** [comment]
thank you!

**Comment by VeNoMouS** [comment]
Also FWIW its appears to be affecting 

* Windows
* Ubuntu
* Possibility OSX

Debian is unaffected.

**Comment by VeNoMouS** [comment]
Guys can you please list the websites not working for you, as i'm having problems replicating any issues for IUAM on ubuntu 18.04....

**Comment by thisdotcrackedequalstrue** [comment]
this one doesnt for me:

**Comment by VeNoMouS** [comment]
@thisdotcrackedequalstrue do you get reCaptcha or 403/1020?

**Comment by mass828** [comment]
hello, i'm having 1020 on https://www.sneakersnstuff.com/ and captchas/403 on sites like https://www.bstn.com/,  https://www.sotostore.com/.

ubuntu 18.04, python 3.6.8

**Comment by VeNoMouS** [comment]
Just a heads up, I am deploying some virtual Ubuntu 18.04 and 19.10 instances so I can have a proper play as I was borrowing some other users boxes to do testing on and I can't mess with their systems to test all theories.

**Comment by VeNoMouS** [comment]
# Standard
```python
>>> scraper = cloudscraper.create_scraper()
>>> for _ in ['https://www.sotostore.com/', 'https://www.slamjam.com/', 'https://www.sneakersnstuff.com/', 'https://www.bstn.com/']:
...    try:
...        print('{} -> {}'.format(_, scraper.get(_)))
...    except:
...        print('{} -> FAILED'.format(_))
...
https://www.sotostore.com/ -> FAILED
https://www.slamjam.com/ -> FAILED
https://www.sneakersnstuff.com/ -> FAILED
https://www.bstn.com/ -> <Response [200]>
>>>
```

# Modified Cipher Suite

```python
>>> import cloudscraper
>>> ciphers = ['TLS_AES_128_GCM_SHA256', 'TLS_AES_256_GCM_SHA384', 'TLS_CHACHA20_POLY1305_SHA256', 'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-GCM-SHA384', 'ECDHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-CHACHA20-POLY1305', 'ECDHE-RSA-CHACHA20-POLY1305', 'AES128-GCM-SHA256', 'AES256-GCM-SHA384', 'AES128-SHA', 'AES256-SHA']
>>> scraper = cloudscraper.create_scraper(debug=False, cipherSuite=ciphers)
>>> for _ in ['https://www.sotostore.com/', 'https://www.slamjam.com/', 'https://www.sneakersnstuff.com/', 'https://www.bstn.com/']:
...    print('{} -> {}'.format(_, scraper.get(_)))
...
https://www.sotostore.com/ -> <Response [200]>
https://www.slamjam.com/ -> <Response [200]>
https://www.sneakersnstuff.com/ -> <Response [200]>
https://www.bstn.com/ -> <Response [200]>
>>>
```


Can you guys please try out the cipherSuite I have pasted above... if ya'll confirm its ok i'll push out it out in a `browser.json` update.

**Comment by selfridgesrty** [comment]
worked for me on https://www.slamjam.com/

**Comment by VeNoMouS** [comment]
thanks @selfridgesrty we will get some of the others confirming, once they do i'll push through the change.

**Comment by thisdotcrackedequalstrue** [comment]
Hey, sorry for the late answer, but ya know, time difference 😝 
Anyways, the above snippet works fine for all 4 sites. 
Thanks a lot.

**Comment by VeNoMouS** [comment]
@thisdotcrackedequalstrue NZDT , currently `Fri Mar 20 20:53:45 NZDT 2020`

**Comment by thisdotcrackedequalstrue** [comment]
Right, like I said, I was late and left ya on read for the whole day (night?). Anyways, thanks for  the quick answer, the solution above works fine like said, thanks a lot.

**Comment by VeNoMouS** [comment]
I just have to work out a bug in the custom UA cipherSuite

**Comment by VeNoMouS** [comment]
Guys sorry about the delay 1.2.30 has been released

**Comment by VeNoMouS** [comment]
Going to close this off , thanks for all the debug info and testing :)
