### ISSUE TITLE
cloudflare getting in the way of progress

### ISSUE THREAD

**Issue by thismebro** [VeNoMouS/cloudscraper#170]
so i usually am able to crack giftcards on certain sites, these certain sites have added cloudflare and made my program stop  working, is there a way to integrate any of this to my applications? anyone can help me ?

before i just had to solve the captcha with a captcha solver manual like 2cap now i get
"Please enable cookies.

One more step

Please complete the security check to access "

**Comment by VeNoMouS** [comment]
![c6f2690dca4a1865f793386a247a6e84](https://user-images.githubusercontent.com/597545/77161234-083ab200-6b0e-11ea-815e-cb2c145174bf.gif)

**Comment by VeNoMouS** [comment]
![giphy (2)](https://user-images.githubusercontent.com/597545/77161296-2b656180-6b0e-11ea-8511-0434527f05d1.gif)
