### ISSUE TITLE
hCaptcha implementation

### ISSUE THREAD

**Issue by thisdotcrackedequalstrue** [VeNoMouS/cloudscraper#175]
It looks like, as least for me, cloudflare's standard Captcha challenge consists now in solving a hCaptcha instead of a reCaptcha. So is there any chance on getting hCaptcha support aswell?
I don't know if it is enforced on every cloudflare site yet, but I have seen it on quite some. Maybe it is also region related and could show either hCaptcha or reCaptcha, depending on either region or ray id of the visitor? Anyways, here is one of the pages where I encountered it:
http://raffle.bstn.com/
![image](https://user-images.githubusercontent.com/59341030/77737604-9cc17a80-700e-11ea-96de-3b74cc19a4cb.png)
Afaik 2captcha and the other providers should support  this weird captcha type.
Thanks for reading and my full respect for your work.

**Comment by vrayv** [comment]
Yes, please, most captcha websites using hcaptcha now.

2captcha and anticaptcha both support it so adding support is logical.

**Comment by VeNoMouS** [comment]
Ok I’ll try find some time to implement it tomorrow

**Comment by VeNoMouS** [comment]
@thisdotcrackedequalstrue , @vrayv  the dev branch has h-captcha support with 2captcha, can you guys test it out?

**Comment by VeNoMouS** [comment]
anticaptcha support added

**Comment by vrayv** [comment]
Works for 2captcha!

**Comment by vrayv** [comment]
There are some errors with anticaptcha.

**Comment by vrayv** [comment]
The version of the python_anticaptcha is not yet published. After manual version replacement it works.

**Comment by cryptocake** [comment]
Perfect! Anti-captcha also works as expected with the hCaptcha tree.

**Comment by thisdotcrackedequalstrue** [comment]
Late answer, but I tested it and it works fine.
![image](https://user-images.githubusercontent.com/59341030/77826829-23ab4b80-7112-11ea-8bee-389881fe46bd.png)

**Comment by VeNoMouS** [comment]
Have pushed an update as not all websites have hCaptcha

**Comment by VeNoMouS** [comment]
I reached out to deathbycaptcha to see if/when they were implementing hCaptcha

```
HI,
 
Thanks for reaching out.
We're planning to, but we do not have a concrete date for it yet. Please, feel free to reach back again in a couple months or so and we'll give you an update/provide you with freebies to test.
 
We appreciate your business,
 
Sincerely,
Zeth
Death By Captcha
```

**Comment by theNarballer** [comment]
Sorry, I'm new to github and I don't know if this question was asked or not, but does anyone know a h-captcha token harvesters? I need a way to manually solve the h-captcha and get the token. Thanks.

**Comment by VeNoMouS** [comment]
@theNarballer why are you trying to manually solve?

**Comment by theNarballer** [comment]
@VeNoMouS I'm trying to build a bot that can enter a website but my parents won't let me pay for services like anti-captcha and 2-captcha. With google's recaptcha, I was able to display the recapcha on a seperate tab, solve the recaptcha, get the token, and use the token in my script to get into  the website and enter a raffle. Now the website uses h-captcha, and it seems pretty similar in the sense that you need a token to enter the main page. I do not know how to get this token though. Any help would be appreciated. Thanks.

**Comment by theNarballer** [comment]
Does anyone know any h-captcha token harvesters. I want to manually harvest h-captcha tokens for a project.

**Comment by NoahCardoza** [comment]
Perfect timing, hcapcha just started popping up for me! Great work!

**Comment by NoahCardoza** [comment]
@theNarballer I don't think this is the place to ask, they are only using second party services to solve the captchas. Maybe try taking a look at https://github.com/Cosmo3904/Recaptcha-Harvester-V2 and modifying the code to load the hcaptchas. With this quarantine I MIGHT take a look and if it's easy cook something up for you.

**Comment by theNarballer** [comment]
@NoahCardoza I have seen Cosmo's harvester, and what I tried to do is edit the html script that he runs to get the reCaptcha harvester, but instead, make it so that the h-captcha shows. When i run the html script by itself, I get the h-captcha thing, but when I run the html part in the harvester.py, the h-captcha does not  show. Thank you for the help though, and I will aks on Cosmo's forum as well.

**Comment by VeNoMouS** [comment]
Due to cipher suite changes on CF this morning, I have to push this into production, I will add in proxy support to reCaptcha requests on next release

**Comment by NoahCardoza** [comment]
@theNarballer checkout https://github.com/NoahCardoza/CaptchaHarvester

**Comment by theNarballer** [comment]
@NoahCardoza  YEP. Got it. Thanks so much!

**Comment by NoahCardoza** [comment]
@theNarballer I just finished the documentation. There are a few more things I'd like to add/update, but time will tell how soon I get around to them. Everything you need for the moment should be there. If you have any questions you can find me on Discord: @MacHacker#7322.

**Comment by VeNoMouS** [comment]
Going to close this ticket out as the proxy related stuff is not hCaptcha related.
