### ISSUE TITLE
ReCaptcha Proxy: True

### ISSUE THREAD

**Issue by NoahCardoza** [VeNoMouS/cloudscraper#176]
After looking through the code, it appears all this means is that the request is made through the proxy, but 2captcha for instance, allows you to give them a proxy which they will solve the captcha from. Is/will that be supported? I'd be happy to submit a PR, at least for 2captcha, I don't have much experience with the other APIs.

https://2captcha.com/newapi-recaptcha-en

**Comment by VeNoMouS** [comment]
Yea ill be overhauling the reCaptcha shortly im just waiting on anticaptcha to add some changes in there code.

this is actually a dupe of #126

**Comment by NoahCardoza** [comment]
My bad, great to hear though!
