### ISSUE TITLE
Is there any way to input my own reCaptcha token?

### ISSUE THREAD

**Issue by theNarballer** [VeNoMouS/cloudscraper#177]
If I have a way to harvest my own reCaptcha token, is there a way that I can input that token into cloudscraper so I can get to my desired webpage? Thanks.

**Comment by pat6969** [comment]
You can do the following:
- set the recaptcha parameter of your scraper to return the response with 
scraper.recaptcha={"provider":"return_response"}
- when it returns a captcha page, fetch the token from your harvester and solve it normally...
Have done it in many times and I think it's basically the best way to integrate your own solving method....
😄 
![image](https://user-images.githubusercontent.com/42221876/77959185-7897bf00-72d6-11ea-892f-61a6659b2af1.png)

**Comment by theNarballer** [comment]
Thank you so much!!!!!!

**Comment by theNarballer** [comment]
Hi,

Thanks for the response. I am trying to make a bot that gets past recaptcha. I am specifically trying to get past on sneakersnstuff.com <http://sneakersnstuff.com/>. When I input your code,

import cloudscraper
scraper = cloudscraper.create_scraper(
 								 interpreter='nodejs',
  								 recaptcha={'provider': 'return_response’}
							     )
print(scraper.get("http://www.sneakersnstuff.com").text)

I get a the recaptcha page, as expected (again, thank you for the help with that). However, now that I have the captcha token with me,  what should I do with that token so I can access the website? Do I need to craft a request. When I manually solve the captcha, I see that the main request being made is this one:



What exactly do I need to submit within this request, if this is even how I get past the recaptcha. Again, thank you for your help.

**Comment by cypri99** [comment]
just parse all the form values and post them to "form", {"class":"challenge-form"})['action'] link and you will get pass through
