### ISSUE TITLE
V1.2.23 (Code 1020 Detected).

### ISSUE THREAD

**Issue by clearclarencs** [VeNoMouS/cloudscraper#179]
Really appreciate the work and support you all put into this service, trying to access sneakersnstuff.com but get cloudflare error, i understand this is a firewall violation however i saw anothe post about how cloudscraper is able to get the site so i tried using a proxy to make sure it wasnt a ip issue witrh same response. Ran on VSC on Windows.

https://pastebin.com/RdSZPsdx

Thanks in advance ill be sure to buy you a coffee.

**Comment by VeNoMouS** [comment]
update to latest push 1.2.32, and thanks if you do get me a coffee ❤️

**Comment by johnnyollo** [comment]
Hi, I still get 403 with last cloudscraper update. Ciphers might have got clipped again.
Python 3.8.1 
Btw I really appreciate your work
