### ISSUE TITLE
Hi, I still get 403 with last cloudscraper update. Ciphers might have got clipped again.

### ISSUE THREAD

**Issue by johnnyollo** [VeNoMouS/cloudscraper#180]
Hi, I still get 403 using last cloudscraper update. Ciphers might have got clipped again.
Python 3.8.1 
https://www.sneakersnstuff.com and https://www.nakedcph.com
Btw I really appreciate your work

_Originally posted by @johnnyollo in https://github.com/VeNoMouS/cloudscraper/issues/179#issuecomment-608669016_

**Comment by clearclarencs** [comment]
Tested on sneakersnstuff.com and it gets past cloudflare and recaptchas just fine for me.
What site are you testing on?

**Comment by johnnyollo** [comment]
https://pastebin.com/VB4gBVfh

I’m also trying on sneakersnstuff, everything was working well until a couple of days ago.
 I tried on macOS python 3.8 and Ubuntu 18 Python3.7, with the last version of cloudscraper

**Comment by VeNoMouS** [comment]
SNS by default is giving reCaptcha in browser every time.

**Comment by johnnyollo** [comment]
@VeNoMouS 
Nah, SNS does not returns captcha challenge every time, check your local ip, it might be flagged.

Here attached a small video of me creating a clean guest chrome session and accessing to SNS without solving any challenge 

https://gyazo.com/766707b82b7e560d31a2947145604aea
