### ISSUE TITLE
User agent regex?

### ISSUE THREAD

**Issue by pim97** [VeNoMouS/cloudscraper#183]
Hi,

When asking for a user agent

```python
tokens, user_agent = scraper.get_tokens(website, proxies=proxies, recaptcha=recaptcha, interpreter='nodejs', delay=10)

    var = {
            "cfduid": tokens['__cfduid'],
            "cf_clearance": tokens['cf_clearance'],
            **"user_agent": user_agent**
        }

    print(
        json.dumps(var)
    )
```

It will return more than just the user agent

```python

{"cfduid": "d0b76c7cfbc7f6d292e303686e2ad9d871586068582", "cf_clearance": "2b0bde165687e8c2a5ccbf56acbda13cf4fbb72c-1586068622-0-250", "user_agent": "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0,gzip(gfe)"}
```
look at last part of user agent: 

```python
,gzip(gfe)
```
 shouldn't be there

and

```python
ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36 AppEngine-Google; (+http://code.google.com/appengine; appid: s~jmfan-4)
```
```python
; (+http://code.google.com/appengine; appid: s~jmfan-4) 
```
shouldn't be there?

**Comment by VeNoMouS** [comment]
Actually its meant to, its a valid UA

Check [Google](
https://www.google.com/search?q=%22Mozilla%2F5.0+(Windows+NT+6.1%3B+rv%3A52.0)+Gecko%2F20100101+Firefox%2F52.0%2Cgzip(gfe)%22&oq=%22Mozilla%2F5.0+(Windows+NT+6.1%3B+rv%3A52.0)+Gecko%2F20100101+Firefox%2F52.0%2Cgzip(gfe)%22&aqs=chrome..69i57.1765j0j7&sourceid=chrome&ie=UTF-8)

**Comment by pim97** [comment]
> Actually its meant to, its a valid UA
> 
> Check [Google](https://www.google.com/search?q=%22Mozilla%2F5.0+(Windows+NT+6.1%3B+rv%3A52.0)+Gecko%2F20100101+Firefox%2F52.0%2Cgzip(gfe)%22&oq=%22Mozilla%2F5.0+(Windows+NT+6.1%3B+rv%3A52.0)+Gecko%2F20100101+Firefox%2F52.0%2Cgzip(gfe)%22&aqs=chrome..69i57.1765j0j7&sourceid=chrome&ie=UTF-8)

Oh thanks for answering that quickly! Didn't know, learning something new.

Btw, great work! Thanks
