### ISSUE TITLE
flixtor.to works?

### ISSUE THREAD

**Issue by FrancHR** [VeNoMouS/cloudscraper#184]
Hi, i am tried to scrape some stuff from flixtor.to, without success.
example:
```
import cloudscraper
scraper = cloudscraper.create_scraper()
response = scraper.get('https://flixtor.to/watch/tv/3364154/better-call-saul')
print(response.text)
```
I have the same response (CF challenge), no matter what i have tried (with/without user agent, with or without Interpreters, etc...).
Is it only for me or?

Thanks!

**Comment by VeNoMouS** [comment]
works fine for me , waht cloudscraper version are you running?

```python
>>> import cloudscraper
>>> cloudscraper.__version__
```

**Comment by FrancHR** [comment]
Hmm, strange.
I have 1.2.32 version, i think is the latest.

**Comment by VeNoMouS** [comment]
User took too long
