### ISSUE TITLE
Not working on Lambda

### ISSUE THREAD

**Issue by Pechi77** [VeNoMouS/cloudscraper#189]
HI, I used this in my local machine, works fine. 

When I deploy it in AWS lambda , it gives the below error.

` "errorMessage": "Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.",
  "errorType": "CloudflareReCaptchaProvider"
}`

Please help

**Comment by pim97** [comment]
```python

  scraper = cloudscraper.create_scraper(
        interpreter='nodejs',
        recaptcha={
            'provider': '2captcha',
            'api_key': 'key'
        }
    )
    tokens, user_agent = scraper.get_tokens(website, proxies=proxies, recaptcha=recaptcha, interpreter='nodejs', delay=10)

```

this is how I have mine set up

**Comment by VeNoMouS** [comment]
WTAF?!

get_tokens is a class method dude...

```python
tokens, user_agent = cloudscraper.get_tokens(
    website,
    proxies=proxies,
    recaptcha= recaptcha={
          'provider': '2captcha',
          'api_key': 'key'
    },
    interpreter='native',
    delay=10
)```

OR

```
scraper = cloudscraper.create_scraper(
      interpreter='native',
      recaptcha={
          'provider': '2captcha',
          'api_key': 'key'
      }
)

print(scraper.get(url).status_code)
```

**Comment by Pechi77** [comment]
I am using as 

Local machine code :

`
scraper = cloudscraper.create_scraper()
text = scraper.get(URL). text
`

Same code works fine in my windows machine but not in lambda

**Comment by VeNoMouS** [comment]
AWS ip's prob flagged with cf... tried using a 3rd party proxy?

**Comment by Pechi77** [comment]
`scraper = cloudscraper.create_scraper()   
res = scraper.get(url,proxies=proxies).text`

**Comment by VeNoMouS** [comment]
Can you supply cloudscraper version and a full debug of what your requesting.

**Comment by Pechi77** [comment]
Hi @VeNoMouS  sorry for the delay, here is the full snippet.
the same code is working fine in local but not in AWS.

cloudscraper version = 1.2.33

```
scraper = cloudscraper.create_scraper()
URL = 
res = scraper.get(url,proxies=proxies).text


output:
{
  "errorMessage": "Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.",
  "errorType": "CloudflareReCaptchaProvider"
}

Logs:

START RequestId: 967b0184-029b-4c2b-a0a0-ef529f70f65a Version: $LATEST
Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.: CloudflareReCaptchaProvider
Traceback (most recent call last):
cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.

END RequestId: 967b0184-029b-4c2b-a0a0-ef529f70f65a
REPORT RequestId: 967b0184-029b-4c2b-a0a0-ef529f70f65a	Duration: 2500.51 ms	Billed Duration: 2600 ms	Memory Size: 128 MB	Max Memory Used: 57 MB	Init Duration: 301.35 ms
```

**Comment by VeNoMouS** [comment]
where is the debug?!

**Comment by Pechi77** [comment]
What information you need?

As I'm running in lambda... I cannot use breakpoint

Pechi

**Comment by Pechi77** [comment]
will this help

DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.1e-fips 11 Feb 2013) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
