### ISSUE TITLE
Wellgosh HTTP 200 however still detected.

### ISSUE THREAD

**Issue by clearclarencs** [VeNoMouS/cloudscraper#190]
Code:
sesh= cloudscraper.create_scraper(browser={'custom': 'Mozilla/5.0 (Linux; U; Android 6.0.1; zh-cn; OPPO R9s Plus Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.134 Mobile Safari/537.36 OppoBrowser/4.4.9'},interpreter='nodejs', recaptcha=anticaptcha, debug=True)
resp=sesh.get("https://wellgosh.com")
Output:
> HTTP/1.1 200 OK
> Content-Type: text/html; charset=UTF-8
> Vary: Accept-Encoding
> X-Magento-Tags: store,cms_b,cms_b_footer_customer_service,cms_b_footer_visit_retail_store,cms_b_footer_contact,cms_b_footer_get_social,cms_b_home_slider_section,cms_b_home_product_section        
> X-Content-Type-Options: nosniff
> X-XSS-Protection: 1; mode=block
> X-Frame-Options: SAMEORIGIN
> MageStack-Tag: Dynamic
> MageStack-Area: Frontend
> MageStack-Loadbalancer: 185.245.116.51
> MageStack-Magento-Version: 2
> MageStack-Debug: true
> MageStack-Last-Modified: true
> MageStack-Config: global
> MageStack-Web-Node: web1
> Content-Encoding: gzip
> MageStack-Cacheable: Yes
> MageStack-Cache-Status: 200
> MageStack-Cache-Lifetime: 86400.000
> MageStack-Cache-Warning: Refusing to overwrite response TTL for Magento 2
> Last-Modified: Fri, 10 Apr 2020 21:27:09 GMT
> Content-Length: 14985
> Accept-Ranges: bytes
> Date: Sat, 11 Apr 2020 17:37:03 GMT
> MageStack-PageSpeed: false
> Pragma: no-cache
> Expires: -1
> Cache-Control: no-store, no-cache, must-revalidate, max-age=0
> MageStack-Cache-Hits: 22177
> MageStack-Cache: Hit
> Server: MageStack-MagentoOS
> Strict-Transport-Security: max-age=0
>
 <!doctype html><html lang="en"><head >  <meta charset="utf-8"/>
<meta name="robots" content="INDEX,FOLLOW"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<meta name="format-detection" content="telephone=no"/>
<title></title>
<link  rel="stylesheet" type="text/css"  media="all" href="https://wellgosh.com/static/version1586436329/_cache/merged/3d94b0d550a629097ee8afb90abb08f2.min.css" />
<link  rel="stylesheet" type="text/css"  media="screen and (min-width: 768px)" href="https://wellgosh.com/static/version1586436329/_cache/merged/900094b7327cfbf4db7c633e9578a6a6.min.css" />
<link  rel="stylesheet" type="text/css"  media="print" href="https://wellgosh.com/static/version1586436329/frontend/Ninedotmedia/wellgosh/en_GB/css/print.min.css" />

<link  rel="icon" type="image/x-icon" href="https://wellgosh.com/media/favicon/stores/1/index.png" />
<link  rel="shortcut icon" type="image/x-icon" href="https://wellgosh.com/media/favicon/stores/1/index.png" />
<meta name="p:domain_verify" content="be2c190b588260b5440ca1238115804b"/>

   

       </head><body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "https://wellgosh.com/static/version1586436329/frontend/Ninedotmedia/wellgosh/en_GB/images/loader-2.gif"}}' class="cms-index-index page-layout-1column">   
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KLHBZRK"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
               <noscript><div class="message global noscript"><div class="content"><p><strong>JavaScript seems to be disabled in your browser.</strong> <span>For the best experience on our site, be sure to turn on Javascript in your browser.</span></p></div><

**Comment by VeNoMouS** [comment]
Site is not on cloudflare
