### ISSUE TITLE
haapi.ankama.com Cloudflare 403 / 1020 Error

### ISSUE THREAD

**Issue by Syliaz** [VeNoMouS/cloudscraper#195]
Hi, don't know if this issue is link to #194 but i'm getting 403/1020 error.

```
< CONNECT https://haapi.ankama.com/json/Ankama/v2/Api/CreateApiKey HTTP/1.1
< Host: haapi.ankama.com
< User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit
/537.36 (KHTML, like Gecko) Chrome/51.0.7610.461 Mobile Safari/537.36
< DNT: 1
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image
/apng,*/*;q=0.8
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate
< Content-Length: 46
< Content-Type: application/x-www-form-urlencoded
<
< login=user&password=passs&long_life_token=true
> HTTP/1.1 403 Forbidden
> Date: Thu, 16 Apr 2020 14:57:25 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Set-Cookie: __cfduid=dc2fdd90607abe2da71e2b302c6d1d5801587049045; expires=Sat,
 16-May-20 14:57:25 GMT; path=/; domain=.ankama.com; HttpOnly; SameSite=Lax
> Cache-Control: max-age=15
> Expires: Thu, 16 Apr 2020 14:57:40 GMT
> X-Frame-Options: SAMEORIGIN
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-c
gi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 584ec2374d54f156-ARN
> Content-Encoding: gzip
> cf-request-id: 022517b68d0000f1563923e200000001
>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | haapi.ankama.com used Cloudflare to restrict access</titl
e>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=
1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" t
ype="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/sty
les/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zep
to.min.js"></script><!--<![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.
common.js"></script><!--<![endif]-->



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-
translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1020</span>
          <small class="heading-ray-id">Ray ID: 584ec2374d54f156 &bull; 2020-04-
16 14:57:25 UTC</small>
        </h1>
        <h2 class="cf-subheadline">Access denied</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>This website is using a security service to protect itself from o
nline attacks.</p>

          </div>



        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>584ec2374d54f156</st
rong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: </span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a h
ref="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="b
rand_link" target="_blank">Cloudflare</a></span>

  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};


</script>

</body>
</html>

Cloudflare has blocked this request (Code 1020 Detected).
```

Python 3.8.2
Windows 10

**Comment by VeNoMouS** [comment]
Can you show code example as well please?

**Comment by VeNoMouS** [comment]
Looking at my past tickets, I have looked into a simliar issue before ...

https://github.com/VeNoMouS/cloudscraper/issues/169#issuecomment-601458942

however, looking re-issuing that code, i get 1020... i think the site has changed something and you're missing a cookie... can you explain the whole process to get the point of posting to **haapi.ankama.com** ?

**Comment by Syliaz** [comment]
Here is my code
```
import cloudscraper
import sys

try:
	username = 'test'
	password = 'test'
	scraper = cloudscraper.create_scraper(browser={'browser': 'chrome', 'desktop': False})
	logindata = {'login': username, 'password': password, 'long_life_token': 'true'}
	print (scraper.post("https://haapi.ankama.com/json/Ankama/v2/Api/CreateApiKey", data = logindata, timeout=10).text)
except Exception as e:
	print(e)
finally:
	sys.stdout.flush()
```

**Comment by Medd410** [comment]
You need a valid ankama account for the request to work and to get the error.
Use those informations : 
username = "xiyai5orn3uqxj7l"
password = "wnyr143enmza3csf"

**Comment by VeNoMouS** [comment]
Neg, still 1020

**Comment by Medd410** [comment]
Calling CreateApiKey is the first step, there is no step before.
This request is the first step to establish a connexion between the client and the server of the game.
It result in a json containing some informations needed to establish a connexion with the server websocket.
![image](https://user-images.githubusercontent.com/57684150/79514479-896e6180-8046-11ea-9a95-d73ff7d74627.png)
Take a look at the request when it's done through a broswer (simulating the real request) :
![image](https://user-images.githubusercontent.com/57684150/79514554-bc185a00-8046-11ea-8820-35d81451e6e4.png)
![image](https://user-images.githubusercontent.com/57684150/79514566-c63a5880-8046-11ea-89ce-f07ba9ec027a.png)

**Comment by VeNoMouS** [comment]
"Take a look at the request when it's done through a broswer (simulating the real request) :" HTF CAN I TAKE A LOOK WHEN YOU WONT EXPLAIN WHERE!!! FFS!!

**Comment by Medd410** [comment]
Calm, I'm trying my best to explain, english isn't my native langage.
There is 3 cookies in the request header : __cfduid __cfruid __cf_bm.
Last time I checked, some of them where missing from the scraper when debugging.

**Comment by Medd410** [comment]
Here is the html code used to replicate the connexion without cloudscraper :

`<form method="post" action="https://haapi.ankama.com/json/Ankama/v2/Api/CreateApiKey">
  <input type="text" id="login" name="login">
  <input type="text" id="password" name="password">
  <button type="submit" id="submit">submit</button>
</form>`

**Comment by VeNoMouS** [comment]
Or you could just tell me what your doing in your browser on anakama.com to replicate like ive asked several times already.

**Comment by Medd410** [comment]
You can't do it directly with the browser, It's an api used by the game Dofus Touch, you can do it with an emulator like Lindo.

**Comment by VeNoMouS** [comment]
cipherSuite issue...

```python
ciphers = [
            'ECDHE-ECDSA-AES128-GCM-SHA256',
            'ECDHE-RSA-AES128-GCM-SHA256',
            'ECDHE-RSA-AES128-SHA',
            'AES128-GCM-SHA256',
            'AES128-SHA',
            'ECDHE-RSA-AES256-SHA384',
            'AES256-SHA',
            'DES-CBC3-SHA',
            'ECDHE-RSA-AES256-GCM-SHA384'
]
scraper = cloudscraper.create_scraper(
    debug=True,
    browser={
        'custom': 'Mozilla/5.0 (Linux; U; Android 6.0.1; zh-cn; OPPO R9s Plus Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.134 Mobile Safari/537.36 OppoBrowser/4.4.9'
    },
    ciphersuite=ciphers
)

scraper.post(
    'https://haapi.ankama.com/json/Ankama/v2/Api/CreateApiKey',
    data={
        'login': 'test',
        'password': 'test',
        'long_life_token': 'true'
    }
)
```

# DEBUG
```
< POST /json/Ankama/v2/Api/CreateApiKey HTTP/1.1
< Host: haapi.ankama.com
< User-Agent: Mozilla/5.0 (Linux; U; Android 6.0.1; zh-cn; OPPO R9s Plus Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.134 Mobile Safari/537.36 OppoBrowser/4.4.9
< DNT: 1
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate, br
< Content-Length: 45
< Content-Type: application/x-www-form-urlencoded
<
< login=test&password=test&long_life_token=true
> HTTP/1.1 601 Bad Credentials
> Date: Fri, 17 Apr 2020 00:07:46 GMT
> Content-Type: application/json
> Transfer-Encoding: chunked
> Connection: keep-alive
> Set-Cookie: __cfduid=db1be504f3bce878d0aaeed58c96489021587082064; expires=Sun, 17-May-20 00:07:44 GMT; path=/; domain=.ankama.com; HttpOnly; SameSite=Lax
> Set-Cookie: __cf_bm=e39f8aae065f296faf88bf214f8fb10366dbdbd2-1587082066-1800-AbGl1oZLuexXCCqV8xuhacbSQUtIwZ6S/Q6tjTFRwOlWqkhfdhonywJF5GKAnqYJVL0/d8Ga4JSTGkE1xfLnfC8=; path=/; expires=Fri, 17-Apr-20 00:37:46 GMT; domain=.ankama.com; HttpOnly; Secure
> Access-Control-Allow-Origin: *
> X-Duration: 2.760172
> CF-Cache-Status: DYNAMIC
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Server: cloudflare
> CF-RAY: 5851e859e928eeaa-AKL
> cf-request-id: 02270f8c2e0000eeaa1cb43200000001
>
{"reason":"FAILED"}
<Response [601]>

```

**Comment by VeNoMouS** [comment]
Feel free to donate a coffee / beer via https://www.buymeacoffee.com/venomous <3

**Comment by HiImNatsu** [comment]
Hi Venomous , you pushed the fix ? i can't seem to update cloudscraper

**Comment by VeNoMouS** [comment]
No refer the posted code.... 

![image](https://user-images.githubusercontent.com/597545/79524936-d89fab00-80b5-11ea-94e5-c9e9d239757f.png)


https://github.com/VeNoMouS/cloudscraper/issues/195#issuecomment-614962385

**Comment by HiImNatsu** [comment]
I have the same problem on another website so i guessed cloudfare changed their cipherSuite globally , that's why i asked if you're gonna push an update

**Comment by VeNoMouS** [comment]
No globally, its just a enhanced security measure outside of the norm... for instance, sneakersnstuff.com have it enabled... its not a default thing.

**Comment by VeNoMouS** [comment]
I could push it as a standard update... but its only a handful of sites that have beefed up their security at this stage that it is effecting.

**Comment by HiImNatsu** [comment]
i would love it if you push it s a standard update , i'm having the same issue with some websites

**Comment by VeNoMouS** [comment]
So why not just issue 

``` python
ciphersuite=[
        'ECDHE-ECDSA-AES128-GCM-SHA256',
        'ECDHE-RSA-AES128-GCM-SHA256',
        'ECDHE-RSA-AES128-SHA',
        'AES128-GCM-SHA256',
        'AES128-SHA',
        'ECDHE-RSA-AES256-SHA384',
        'AES256-SHA',
        'DES-CBC3-SHA',
        'ECDHE-RSA-AES256-GCM-SHA384'
    ]
``` 

in the mean time?

**Comment by HiImNatsu** [comment]
it didn't work for me ( python )

**Comment by VeNoMouS** [comment]
Linux?

**Comment by HiImNatsu** [comment]
windows 10

**Comment by VeNoMouS** [comment]
Open a ticket then.

**Comment by HiImNatsu** [comment]
do you have discord ? i dont wanna go public ^^

**Comment by VeNoMouS** [comment]
@HiImNatsu what version of python on win10, just checked 3.7.5 and higher and des is not in openssl on windows.

**Comment by VeNoMouS** [comment]
Run the following code to see if you you have the cipher compiled into your OpenSSL library that comes with python..

Windows

- 3.7.5, 3.8 does not
- 3.6 does have support.
 
``python
import ssl
from operator import itemgetter

context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
context.set_ciphers('DES-CBC3-SHA')
'DES-CBC3-SHA' in map(itemgetter('name'), context.get_ciphers())
```

**Comment by HiImNatsu** [comment]
> Run the following code to see if you you have the cipher compiled into your OpenSSL library that comes with python..
> 
> Windows
> 
> * 3.7.5, 3.8 does not
> * 3.6 does have support.
> 
> ```python
> import ssl
> from operator import itemgetter
> 
> context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
> context.set_ciphers('DES-CBC3-SHA')
> 'DES-CBC3-SHA' in map(itemgetter('name'), context.get_ciphers())
> ```

Thank you it worked , bought you a coffee :D

**Comment by Fran008** [comment]
Good morning, VeNoMouS

I hope you are fine in this confination times.

I am trying the code with ciphersuite you posted here, but I am getting this error:

TypeError: __init__() got an unexpected keyword argument 'ciphersuite'

Python2 and Python3. Any ideas why it is showing? Thank you in advance.

I guess it is a problem with python language, but any help will be welcomed.

**Comment by Syliaz** [comment]
`ciphersuite` -> `cipherSuite`

**Comment by Fran008** [comment]
Thank you Syliaz! It works now ;)

**Comment by Fran008** [comment]
Sorry, but I have other error now... when I do the test with get_ciphers suggested in this post, I get:

'SSLContext' object has no attribute 'get_ciphers'

Any ideas how to solve it? Thank you!

**Comment by Fran008** [comment]
Anyway, it may not be important... the relevant thing for me is testing against the real web and it is not working now because of the Covid-19. So... I'll have to wait and see if it works some months later. Thank you anyway!

**Comment by VeNoMouS** [comment]
```

**Comment by VeNoMouS** [comment]
```python
'SSLContext' object has no attribute 'get_ciphers'
```

time to get off py2 https://www.python.org/doc/sunset-python-2/ and move your arse to py3 ;P
