### ISSUE TITLE
issue related to a "common problem"

### ISSUE THREAD

**Issue by xpeedo** [VeNoMouS/cloudscraper#196]
Hello, I tested the cloudscraper on:
- Windows 10 Pro 1709 (non-VM, x64) - failed
- Windows 10 Pro 1909 (non-VM, x64) - failed
- Windows 10 Pro 1909 (VM, x64) - failed
- Windows 7 Ultimate (VM, x64) - failed
- Windows 7 Ultimate (non-VM, x64) - success
(i think Linux doesn't matter, but tested on it too)

Here I've got some proofs:

SUCCESS:
![nonvm_w7](https://i.imgur.com/3c78iPn.png)

FAIL:
![vm_w7](https://cdn.discordapp.com/attachments/458009130641129475/700729371169783828/unknown.png)

I want to mention I tested cloudscraper on same website, but on different environments. On ``Windows 7 Ultimate (non-VM, x64) - success`` tested with socks4/5, same result (success).

Also, thanks to @MrReacher for the help.

**Comment by MrReacher** [comment]
Also tested from a virtual server using Ubuntu 14.04 running Python v3.5.3 (latest OpenSSL & cloudscraper)
This is full output with `debug=True`: https://hasteb.in/rolevaqu.lua (please note that the domain name was replaced in this hastebin)
This is what it returns from `cdn-cgi/challenge-platform/orchestrate/jsch/v1`: https://hasteb.in/odewisos.js

**Comment by VeNoMouS** [comment]
#RE os..

the OS has **NOTHING** to do with it, it will be your OpenSSL packaged with your python in windows for instance python >= 3.7.5 on windows and most modern Linux packages does not include 3DES as its a weak cipher... 

# New challenge:

I am aware of the new challenge and there is an active ticket for it https://github.com/VeNoMouS/cloudscraper/issues/185

**Comment by MrReacher** [comment]
There isn't any workaround for this issue, is there? We are very dependent on this project, since one of our APIs is built on top of it. Not trying to be rude, can you provide any ETA? Thanks.

**Comment by VeNoMouS** [comment]
For which? OpenSSL ? or for the new challenge?

**Comment by MrReacher** [comment]
The issue we are having is with one specific website, and we think it's because of the new challenge. (the hastebins posted above)

I can't provide the website url here, do you have some sort of contact so we can chat privately?

**Comment by VeNoMouS** [comment]
I have not finished the code for the new solve yet, but i understand how it works

**Comment by VeNoMouS** [comment]
Closing this dupe ticket
