### ISSUE TITLE
Receiving 1020 error when accessing https://www.spigotmc.org/

### ISSUE THREAD

**Issue by OmerBenGera** [VeNoMouS/cloudscraper#197]
I tried to use the following code to access to spigotmc.org:
```
import cloudscraper
import ssl

print(ssl.OPENSSL_VERSION)

scraper = cloudscraper.create_scraper()

with open("access.html", "w") as file:
    file.write(scraper.get("https://www.spigotmc.org/").text)
```

But, I get a 1020 error. The output of the first print is the following:
> OpenSSL 1.1.1a  20 Nov 2018

**Comment by scullcandyz** [comment]
I think cloudflare changed up, getting 1020 on all my sites (sotostore, nakedcph, stress95)

**Comment by VeNoMouS** [comment]
# spigotmc.org

```
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get('https://www.spigotmc.org/')
<Response [200]>
>>>
```
# soto, stress95 etc...

```python
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get("https://www.sotostore.com")
cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
>>> scraper.get("https://www.stress95.com")
cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
```

![image](https://user-images.githubusercontent.com/597545/79678177-b68c6100-824c-11ea-9955-cd8ecc1b9d91.png)

**Comment by OmerBenGera** [comment]
> 
> 
> I see no 1020's....
> # spigotmc.org
> 
> ```python
> >>> scraper = cloudscraper.create_scraper()
> >>> scraper.get('https://www.spigotmc.org/')
> <Response [200]>
> >>>
> ```
> 
> # soto, stress95 etc...
> 
> ```python
> >>> scraper = cloudscraper.create_scraper()
> >>> scraper.get("https://www.sotostore.com")
> cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
> >>> scraper.get("https://www.stress95.com")
> cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
> ```
> 
> ![image](https://user-images.githubusercontent.com/597545/79678177-b68c6100-824c-11ea-9955-cd8ecc1b9d91.png)

It works fine on my personal computer, but when I try to use it on my VPS, it gives me a 1020 code

**Comment by scullcandyz** [comment]
![image](https://user-images.githubusercontent.com/58109239/79684235-ff81ec80-822f-11ea-8929-4216afbaf7c8.png)

my bad I cant grad tokens on any of the above sites since 2-3 days

**Comment by VeNoMouS** [comment]
> ![image](https://user-images.githubusercontent.com/58109239/79684235-ff81ec80-822f-11ea-8929-4216afbaf7c8.png)
> 
> my bad I cant grab tokens on any of the above sites since 2-3 days

Do the following...

```python
import cloudscraper
scraper = cloudscraper.create_scraper()
response = scraper.get('https://www.sotostore.com')
if '_cf_chl_opt' in response.text:
    print('new challenge detected')
```

if the above print's something... then get in line https://github.com/VeNoMouS/cloudscraper/issues/185

**Comment by scullcandyz** [comment]
> > ![image](https://user-images.githubusercontent.com/58109239/79684235-ff81ec80-822f-11ea-8929-4216afbaf7c8.png)
> > my bad I cant grab tokens on any of the above sites since 2-3 days
> 
> Do the following...
> 
> ```python
> import cloudscraper
> scraper = cloudscraper.create_scraper()
> response = scraper.get('https://www.sotostore.com')
> if '_cf_chl_opt' in response.text:
>     print('new challenge detected')
> ```
> 
> if the above print's something... then get in line #185

Alright as follows: on soto above request asks me to load re-captcha provider, works upon doing so. The same request on NakedCPH returns a 502: https://pastebin.com/jC6xJgpn
The token request on both sites fails, debug: https://pastebin.com/ka8VPWRf (nakedcph)

**Comment by VeNoMouS** [comment]
Funny you should mention 502... We (Project Z) were see'ing something similar with SNS last night after reCaptcha solve... I need to look into it... its monday morning for me , and im doing my day job atm

**Comment by scullcandyz** [comment]
> Funny you should mention 502... We (Project Z) were see'ing something similar with SNS last night after reCaptcha solve... I need to look into it... its monday morning for me , and im doing my day job atm

My bad, hope this didnt come the wrong way didnt mean to be pushy or anything if thats how it came across. Appreciate your work to the fullest! Let me know if theres anything I can do to help out.

**Comment by Oshan96** [comment]
I'm getting the same type of results when trying to access somewbesites, and the errors I'm getting vary time to time. As for an example, when I'm trying to access https://4anime.to/ I get the following type of errors:

### CloudflareIUAMError

```python
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get("https://4anime.to")
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

cloudscraper.exceptions.CloudflareIUAMError: Cloudflare IUAM possibility malformed, issue extracing delay value.
```

### 503 error

```python
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get("https://4anime.to")
<Response [503]>
```

When I'm getting neither type of these errors, it is the usual recaptcha challenge failed error. But that has always been fine if I re-run the command. But this time, I'm not getting anything

**Comment by VeNoMouS** [comment]
Please update to latest 1.2.34 release.

**Comment by OmerBenGera** [comment]
@VeNoMouS Same. Using 1.2.34 - Still receiving 1020 on my VPS, but it works fine on my PC.

**Comment by OmerBenGera** [comment]
@VeNoMouS It still doesn't work, even with the newest version. I added debug=True, here are the results:
```
>>> scraoer = cloudscraper.create_scraper(debug=True)
>>> scraoer.get("https://www.spigotmc.org/")
< GET / HTTP/1.1
< Host: www.spigotmc.org
< User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.70 Safari/537.36
< DNT: 1
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate
<

> HTTP/1.1 403 Forbidden
> Date: Wed, 22 Apr 2020 12:43:34 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Set-Cookie: __cfduid=d2765a35cd5f067bb549c3dc12f32de471587559414; expires=Fri, 22-May-20 12:43:34 GMT; path=/; domain=.spigotmc.org; HttpOnly; SameSite=Lax; Secure
> Cache-Control: max-age=15
> Expires: Wed, 22 Apr 2020 12:43:49 GMT
> X-Frame-Options: SAMEORIGIN
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 587f6e64fcddf2c0-WAW
> Content-Encoding: gzip
> alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
> cf-request-id: 024383531c0000f2c06399d200000001
>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | www.spigotmc.org used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><!--<![endif]-->



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1020</span>
          <small class="heading-ray-id">Ray ID: 587f6e64fcddf2c0 &bull; 2020-04-22 12:43:34 UTC</small>
        </h1>
        <h2 class="cf-subheadline">Access denied</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>This website is using a security service to protect itself from online attacks.</p>

          </div>



        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>587f6e64fcddf2c0</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 51.38.50.120</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};


</script>

</body>
</html>

cloudscraper.exceptions.CloudflareCode1020: Cloudflare has blocked this request (Code 1020 Detected).
```

**Comment by VeNoMouS** [comment]
@OmerBenGera refer #201
