### ISSUE TITLE
Cloudflare "You've been blocked" at peapod

### ISSUE THREAD

**Issue by sparky2708** [VeNoMouS/cloudscraper#198]
I seem to be hitting some sort of cloudflare issue when using cloudscraper and getting a "You've been blocked" by cloudflare. I can access the site using a zipcode and city without any issue using a browser so it is blocking that request for some reason.

Here is my code:
https://stackoverflow.com/questions/61274466/why-cant-i-login-to-peapod-using-the-requests-module
  
Here is the response I get:
`<html>\n<head lang="en">\n    <meta charset="UTF-8">\n    <title>You\'ve Been Blocked</title>\n    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"/>\n\n    <style>\n        * {\n            -webkit-box-sizing: border-box;\n            -moz-box-sizing: border-box;\n            box-sizing: border-box;\n        }\n\n        html {\n            font-size: 62.5%;\n        }\n\n        body {\n            color: #333333;\n            font-family: Helvetica, sans-serif;\n            font-size: 1.6rem;\n            padding: 2rem;\n            line-height: 2.1rem;\n        }\n\n        .page-wrapper {\n            max-width: 40rem;\n            margin: 0 auto;\n            position: relative;\n            padding-top: 4rem;\n        }\n        .section {\n            text-align: center;\n            margin-bottom: 2rem;\n        }\n\n        .logo-wrapper {\n        }\n\n        .logo-image {\n            max-width: 20rem;\n            width: 100%;\n        }\n\n        .main-headline {\n            font-size: 2.1rem;\n            line-height: 3rem;\n            color: #5ea000;\n        }\n\n        .footer {\n            color: #737373;\n            text-align: center;\n        }\n\n    </style>\n\n</head>\n<body>\n\n<div class="page-wrapper">\n    <div class="section">\n        <div class="logo-wrapper">\n            <img class="logo-image" src="New_Peapod_Logo_2c_Transparent.png" alt="Peapod Logo"/>\n        </div>\n    </div>\n\n    <div class="section">\n        <h1 class="main-headline">\n           Too many requests or invalid client\n        </h1>\n    </div>\n\n    <div class="footer">\n        <p>Questions or Concerns?<br>Customer Care: 800-573-2763</p>\n    </div>\n</div>\n\n</body>\n</html>`

**Comment by VeNoMouS** [comment]
- **Not** a cloudscraper bug, PEBKAC
- You're blowing away all the normal headers that are required and not setting the UA properly
- Look at your headers  / Cookies
- POST's to that **API** /api/v4.0/ are JSON
- **WTF** are you using bs4 on a json payload?
- You're not solving the challenge headers for the site (outside of Cloudflare)

# Re Headers

Referer might be required

```python
session.headers['Referer'] = 'https://www.peapod.com/shop/auth/login?gateway=1&redirectTo=%2F'
```

# re POST to API
```python
response = session.post(
    url,
    json={
        'customerType': 'C',
        'cities': None,
        'email': None,
        'serviceLocationId': 95004,
        'zip': '21122'
    }
)
```

# Re UA

```python
with cloudscraper.create_scraper(
    browser={
        'custom': ''Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36'
    }
) as session:
```

# WTF?!!

```python
#get all the service locations for a zipcode (if there are multiple)
    url = f'https://www.peapod.com/api/v4.0/serviceLocations?customerType=C&zip={ZIPCODE}'
    res2 = session.get(url, headers=headers)

    #find the location id needed for the login request
    soup = BeautifulSoup(res2.content, 'html.parser')
    dic = json.loads(str(soup))
    loc_id = ""
    for loc in dic['response']['locations']:
        location = loc['location']
        if (location['city'] == CITY):
            loc_id = location['id']
            break
```

You're better doing something more like ...

```python
response = scraper.get(
    'https://www.peapod.com/api/v4.0/serviceLocations',
    params={
        'customerType': 'C',
        'zip': ZIPCODE
    }
)

try:
    loc_id = list(
        filter(
            lambda x: x.get('location', {}).get('city') == CITY, response.json()['response']['locations']
        )
    )[0]['location']['id']
except IndexError:
    raise ValueError("Can't find City '{}' -> Zip {}".format(CITY, ZIPCODE))
```

# Addtional Challenge

There appears to be some sort of crypt payload going on in the headers

- x-ccwfdfx7-a
- x-ccwfdfx7-b
- x-ccwfdfx7-c
- x-ccwfdfx7-d
- x-ccwfdfx7-f
- x-ccwfdfx7-z


At the end of the day, the problem is PEBKAC, I could solve this , but i would not solve it for free.

**Comment by sparky2708** [comment]
Thanks for the help. Will look into it more...
