### ISSUE TITLE
Caveats with release >= 1.2.34 (1020 Error)

### ISSUE THREAD

**Issue by VeNoMouS** [VeNoMouS/cloudscraper#201]
If you are getting a **1020 error**, check you have the required ciphers compiled into your OpenSSL for your python...

One such cipher you can check is `DES-CBC3-SHA` (this test will only work on python >= 3.6)

```python

import ssl
from operator import itemgetter

context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
context.set_ciphers('DES-CBC3-SHA')
'DES-CBC3-SHA' in map(itemgetter('name'), context.get_ciphers())
```

If this comes back `False`, and you don't know how to fix this... *for some coffee donations* I will send you working OpenSSL libraries.

hit me up on **Discord** `VeNoMouSNZ#5979` if you need help for this issue, all other issues, please log a ticket!!

**Comment by Fran008** [comment]
Please send me that libraries!

I'll be pleased to send some coffees ;)

I guess my mail is in my github profile.

**Comment by VeNoMouS** [comment]
It is not, is your hotmail ok?

**Comment by Fran008** [comment]
cal........@hotmail.com

Is that one, isn't it?

**Comment by Fran008** [comment]
No, no... sorry.

I have updated now in my profile!
