### ISSUE TITLE
9kw does support hCaptcha

### ISSUE THREAD

**Issue by CorentinCAM** [VeNoMouS/cloudscraper#202]
In 9kw.py, an exception is raised if captcha type is hCaptcha to tell the user hCaptcha is not supported. However [this page](https://www.9kw.eu/api.html#apisolve-tab) tells it is with the interactive=1 flag (which is already set in your code). Is there any reason to this?

Thanks for your amazing work!

**Comment by VeNoMouS** [comment]
@CorentinCAM i've added it into the dev branch 005573155edf33aaac77b973296821858fd35418, i personally get never get 9kw to solve anything... 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/597545/80170804-ef597b00-863c-11ea-85f2-b8e5dfc85cda.png)

I personally **hate** 9KW
- The site UX / UI s shit
- The documentation is shit
- The examples are shit
- ... and it now seems the solvers... are shit

![image](https://user-images.githubusercontent.com/597545/80170917-36477080-863d-11ea-843b-34423357ace1.png)

**Comment by CorentinCAM** [comment]
Haha I prefer it over others because they doesn't encourage sub-developed countries people to work for almost nothing :)

Thanks a lot anyways!
