### ISSUE TITLE
503 on IUAM Challenge

### ISSUE THREAD

**Issue by Riazable** [VeNoMouS/cloudscraper#206]
Hey mate, was trying to make a request to: https://www.overkillshop.com/en/adidas-superstar-80s-recon-ee7396.html and it was just returning 503, even though I could access the site manually. I had a look at the __init__() function and it looked like this line: 

re.search(r'action="/.*?__cf_chl_jschl_tk__=\S+".*?name="jschl_vc"\svalue=.*?', resp.text, re.M | re.DOTALL)

was returning None. Doesn't look like a huge issue probably just something to do with parsing values. Thanks mate!

**Comment by 2020iscancelled** [comment]
Sorry for my intrusion here, hope I'm not unwanted.
The site you supplied uses the new IUAM challenge:

You can simply check it by looking for this string in the cloudflare page:

/cdn-cgi/challenge-platform/orchestrate/jsch/v1";

if it's there, you know the new js challenge is enabled.
See #185 for the detailed info about the new cf jschl....

**Comment by Riazable** [comment]
in the response content? i don't see it

**Comment by 2020iscancelled** [comment]
![image](https://user-images.githubusercontent.com/42221876/80509107-37e4a180-8979-11ea-88ef-2d7b3a888968.png)
look in the page source of the IUAM page.

**Comment by Riazable** [comment]
oh thanks alot, looks like @VeNoMouS is still looking into it, i'll have a look myself too!

**Comment by VeNoMouS** [comment]
FWIW, dev branch detects new challenge and raises a custom exception
