### ISSUE TITLE
[Question] Loop Protection when trying to sovle Captcha.

### ISSUE THREAD

**Issue by Va1a** [VeNoMouS/cloudscraper#208]
So I am trying to POST to a website with certain form data. I constantly get Loop protection (Cloudscraper tried solving the CAPTCHA 3 times) is anyone else experiencing a similar problem? This does not seem to be site exclusive, it happens on every site I test it on. My API key is valid, and I use 2captcha.

**Comment by VeNoMouS** [comment]
Post a proper ticket with the issue template or ill close this..

thanks

**Comment by VeNoMouS** [comment]
Failed to comply.
