### ISSUE TITLE
503 response

### ISSUE THREAD

**Issue by Sergey-S-Lebedev** [VeNoMouS/cloudscraper#211]
After attempt to start a script with multiprocessing, got a message "DDOS attack detected" then processing a requests via cloudscraper(wiyhout threads) always get a 503 response 
![2020-05-06_19-10](https://user-images.githubusercontent.com/45784692/81201070-81626b80-8fcd-11ea-90c7-fe74ff3fee82.png)

**Comment by 2020iscancelled** [comment]
#209
