### ISSUE TITLE
How does this website work? I need __cf_bm cookie

### ISSUE THREAD

**Issue by paco020295** [VeNoMouS/cloudscraper#214]
Summary.

## Expected Result

i want to be able to see website content without getting blocked and without using Selenium. I have a solution that works if i open the website once, pass the cookies to a session and create a cloudflare scraper from this. I noticed i only need a cookie named (__cf_bm)

## Actual Result

I mean...it's working. I want to know if there is a way of making it work without using Selenium.

## Reproduction Steps 

```python
session = HTMLSession()
driver = init_driver()
driver.get("https://rewe.de")
cookies = driver.get_cookies()
user_agent = driver.execute_script("return navigator.userAgent;")
for cookie in cookies:
    if cookie["name"] == "__cf_bm": #I noticed i can make it work with only this cookie
        session.cookies.set(cookie['name'], cookie['value'])
        print(cookie['name'], cookie['value'])
driver.close()

scraper = cloudscraper.create_scraper(sess=session)
r = scraper.get("https://shop.rewe.de/productList?objectsPerPage=250", headers={'User-Agent': user_agent})

```

**Comment by VeNoMouS** [comment]
**__cf_bm** is populated from **V2** challenge only if im not mistaken. in regards to ***V1** challenge , we carry over **ALL** cookies populated by Cloudflare

**Comment by VeNoMouS** [comment]
mmm further investigation, it's populated once you pass a valid **__cfduid**

**Comment by paco020295** [comment]
Could you explain in more detail that last part? Because i did try using .get_tokens() and __cfduid was populated and _cf_clerence was an empty string. But when i passed __cfduid as a cookie, i still was prmpted with a captcha. If you don't mind sharing code, that would be great too. I just discovered this repository yesterday.

Thanks for the reply

**Comment by VeNoMouS** [comment]
https://support.cloudflare.com/hc/en-us/articles/360027519452-Understanding-Cloudflare-Bot-Management

**Comment by paco020295** [comment]
This is another piece of code i tried:
```python
scraper = cloudscraper.create_scraper(sess=session)
tokens, user_agent = scraper.get_tokens("https://rewe.de")
print(tokens)
for cookie in tokens:
    scraper.cookies.set(cookie, tokens[cookie])
r = scraper.get("https://shop.rewe.de/productList?objectsPerPage=250", headers={'User-Agent': user_agent})
```
But i still get:
cloudscraper.exceptions.CloudflareReCaptchaProvider: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.

**Comment by VeNoMouS** [comment]
Why... on earth are you doing that smh

**Comment by paco020295** [comment]
Don't i need to pass the __cfduid as a cookie to the scraper?

I don't think i understand how to unlock this website. Do you think you can give me a hand?
