### ISSUE TITLE
[Feature] Add support for hCaptcha

### ISSUE THREAD

**Issue by RafayGhafoor** [VeNoMouS/cloudscraper#219]
https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/

**Comment by VeNoMouS** [comment]
!?!??! there is already support for hCaptcha in the reCaptcha..

**Comment by RafayGhafoor** [comment]
@VeNoMouS, I am trying to bypass protection on animerush.tv and it's giving me captcha error while I am using the antiCaptcha API (premium).

**Comment by VeNoMouS** [comment]
can you give more detail please .... such as code example, response example, exception example..

**Comment by RafayGhafoor** [comment]
```python
import cloudscraper
import sys
import time


scraper = cloudscraper.create_scraper(
    recaptcha={
        "provider": "anticaptcha",
        "api_key": "removed",
    },
)
url = "http://www.animerush.tv"


cookie_value, _ = scraper.get_cookie_string(
    url
)
```
![image](https://user-images.githubusercontent.com/20343475/82134412-1c9ae280-9811-11ea-9759-0a43cc5ce97a.png)

**Comment by VeNoMouS** [comment]
"Detected the new Cloudflare Challenge".....  it detected the **V2** Challenge which i have not published publicly as im still working on that, it has zero to do with reCaptcha.
