### ISSUE TITLE
KeyError: 'return "<i>" + this + "</i>";'

### ISSUE THREAD

**Issue by HawkLiking** [VeNoMouS/cloudscraper#22]
Hi !

Didn't see this new repo, happy to see that you are hardly working on it with pro-src :)

I have an issue with cloudscraper v1.1.4 (I did not test previous versions) 

Here is my test code:
```python
import cloudscraper

scraper = cloudscraper.create_scraper(debug=False)
r = scraper.get('https://japscan.to')
```

And here is the error:
```bash
ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.
Traceback (most recent call last):
  File "test2.py", line 4, in <module>
    r = scraper.get('https://japscan.to')
  File "/usr/local/lib/python3.5/dist-packages/requests-2.21.0-py3.5.egg/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.4-py3.5.egg/cloudscraper/__init__.py", line 142, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.4-py3.5.egg/cloudscraper/__init__.py", line 203, in sendChallengeResponse
    params['jschl_answer'] = JavaScriptInterpreter.dynamicImport(self.interpreter).solveChallenge(body, domain)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.4-py3.5.egg/cloudscraper/interpreters/__init__.py", line 80, in solveChallenge
    re.sub(r'\s{2,}', ' ', jsEnv.format(domain=domain, innerHTML=innerHTML), flags=re.MULTILINE | re.DOTALL),
KeyError: 'return "<i>" + this + "</i>";'
```

The test was made with python3.5 , and with interpreter js2py and nodejs (same error for both).

Here is my pip3 freeze (I have all the needed requirements) https://zerobin.net/?65635dacfc61f40c#act0xFjqamvxYupj+KMl+Gcbz1QCUqPDJMuu26Y8Hnc= 

pip3 show cloudscraper
```bash
Name: cloudscraper
Version: 1.1.4
Summary: A Python module to bypass Cloudflare's anti-bot page.
Home-page: https://github.com/venomous/cloudscraper
Author: VeNoMouS
Author-email: venom@gen-x.co.nz
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.4-py3.5.egg
Requires: brotli, js2py, requests, requests-toolbelt
```

Thank you :)

**Comment by HawkLiking** [comment]
I mailed you the full debug output by mail

**Comment by pro-src** [comment]
@HawkLiking I do believe that it's already fixed it but hasn't been released. The commit that caused that problem had only been pushed and published a few minutes before you got copy. 
I raised the issue here: https://github.com/VeNoMouS/cloudscraper/commit/0c5c6ced9c11cf95b65a2eff572c0bc90d6f80e3#r33407968

I'm not sure what the problem was with all of the PRs for the same thing: #17, #18, #19, #20, #21 
But like I said, I think it's fixed.

Thanks for the mention. :smiley:

**Comment by HawkLiking** [comment]
This was commited in the 1.1.4 one hour ago https://github.com/VeNoMouS/cloudscraper/commit/5c4638cceddb10c22d7a64916deddcb16a1fb0e1

My code was tested with this 1.1.4 commit (I'm not using pip to install cloudscraper, I'm cloning the master branch and installing with setup.py)

So I think the fix does not work for this issue, or that I am doing something else bad... :-/

**Comment by pro-src** [comment]
@HawkLiking The code on Github does not reflect what was published using twine to pypi.org which is where pip pulls the packages from by default. The error would make since only if the bad commit was in the release not the current one on master.

**Comment by pro-src** [comment]
@HawkLiking Heres a command for you to check to confirm it. If grep doesn't print anything, you've got the bad commit.

```sh
cat /usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.4-py3.5.egg/cloudscraper/interpreters/__init__.py | grep -oP '{{ return "<i>"'
```

**Comment by HawkLiking** [comment]
Yep, grep doesn't print anything (beacause '{{ return "<i>"' was changed in the last commit on master)

So I just have to wait for the fix to be merged ? (I think I didn't fully understand the git/twine workflow you explained haha^^)

**Comment by pro-src** [comment]
@HawkLiking Sorry, I missed your comment about not having used pip. I just tested and I'm able to produce the error as well. The problem is that the bad commit is till on master... It's odd... I think something werid was done in an attempt to fix, well something. lol

**Comment by VeNoMouS** [comment]
Sorry guys... my bad, i'll fix it now.

**Comment by VeNoMouS** [comment]
Sorry I did test before I went out... and I didn't see an initial issue... apologies guys.

**Comment by HawkLiking** [comment]
Works like a charm ! Thank you @VeNoMouS , and @pro-src !

**Comment by VeNoMouS** [comment]
Sorry again.
