### ISSUE TITLE
cloudscraper.execptions.CloudflareChallengeError

### ISSUE THREAD

**Issue by dr400** [VeNoMouS/cloudscraper#222]
Summary: 

trigger cloudscraper as expected

## Expected Result

To be able to parse my html page (yggtorrent rss page)

## Actual Result

cloudscraper.exceptions.CloudflareChallengeError: Detected the new Cloudflare challenge.

## System Information

    $ python -m cloudscraper.help

DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2r-fips  26 Feb 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
{
    "platform": {
        "system": "Linux",
        "release": "4.4.59+"
    },
    "interpreter": {
        "version": "3.5.1",
        "name": "CPython"
    },
    "cloudscraper": "1.2.38",
    "requests": "2.23.0",
    "urllib3": "1.25.9",
    "OpenSSL": {
        "version": "OpenSSL 1.0.2r-fips  26 Feb 2019",
        "ciphers": "get_ciphers() is unsupported"
    }
}

**Comment by Ekhozie** [comment]
Same for me:
```sh
Name: cloudscraper  
Version: 1.2.38
Summary: A Python module to bypass Cloudflare's anti-bot page.
Home-page: https://github.com/venomous/cloudscraper
Author: VeNoMouS
Author-email: venom@gen-x.co.nz
License: UNKNOWN
Location: /usr/local/lib/python3.6/site-packages
Requires: pyparsing, requests, requests-toolbelt
Required-by:
```

```sh
BUG: Unhandled error in plugin rss: Detected the new Cloudflare challenge.
cloudscraper.exceptions.CloudflareChallengeError: Detected the new Cloudflare challenge.
```

**Comment by VeNoMouS** [comment]
@Ekhozie please dont puggy back on other tickets #223 , @dr400 your "problem" is not a problem, its picking up the new version of cloudflare's challenge #185... which i have not published publicly.
