### ISSUE TITLE
New content in obfuscated JS causing jsfuckChallenge extraction to fail

### ISSUE THREAD

**Issue by simonpercivall** [VeNoMouS/cloudscraper#223]
The regex for extracting `jsfuckChallance` has started failing on some pages because the non-challenge content after `'challenge-form'` has changed.

## Expected Result

A successfully passed challenge.

## Actual Result

`raise CloudflareSolveError('There was an issue extracting "jsfuckChallenge" from the Cloudflare challenge.')`

## Reproduction Steps 

This is the HTML content that causes the regex to fail:
```
f = document.getElementById('challenge-form'); a.value = '';
```

changing the challenge regex to:
```
r"setTimeout\(function\(\){\s+var.*?f,\s*(?P<variable>\w+).*?:(?P<init>\S+)};"
r".*?\('challenge-form'\);.+?;(?P<challenge>.*?a\.value)\s*=",
```

makes the solver work again. To clarify, the specific change is `.+?` after `challenge-form` instead of `\s+`.

## Version

This is for `cloudscraper` 1.2.38 with the built-in "native" JS engine.

**Comment by VeNoMouS** [comment]
Just fixing a small float -> str bug in py2 for the testing

```python
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> str(102.7365930923)
'102.7365930923'
>>>

Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> str(102.7365930923)
'102.736593092'
>>>
```

**Comment by VeNoMouS** [comment]
This has been all resolved in dev branch  , the str round precision issue was fixed in b7eac6cd70654d960d5c644ee5697dd41828b1e9 for py2

**Comment by VeNoMouS** [comment]
@simonpercivall fwiw i went with `.*?` over `.*+`

```

? | The question mark indicates zero or one occurrences of the preceding element. For example, colou?r matches both "color" and "colour".
-- | --
* | The asterisk indicates zero or more occurrences of the preceding element. For example, ab*c matches "ac", "abc", "abbc", "abbbc", and so on.
+ | The plus sign indicates one or more occurrences of the preceding element. For example, ab+c matches "abc", "abbc", "abbbc", and so on, but not "ac".
{n}[19] | The preceding item is matched exactly n times.
{min,}[19] | The preceding item is matched min or more times.
{min,max}[19] | The preceding item is matched at least min times, but not more than max times.



```

**Comment by VeNoMouS** [comment]
@simonpercivall fwiw i went with `.*?` over `.*+`


* ?  The question mark indicates zero or one occurrences of the preceding element. For example, colou?r matches both "color" and "colour".

* *  The asterisk indicates zero or more occurrences of the preceding element. For example, ab*c matches "ac", "abc", "abbc", "abbbc", and so on.
* +  The plus sign indicates one or more occurrences of the preceding element. For example, ab+c matches "abc", "abbc", "abbbc", and so on, but not "ac".
* {n}[19] | The preceding item is matched exactly n times.
* {min,}[19] | The preceding item is matched min or more times.
{min,max}[19] | The preceding item is matched at least min times, but not more than max times.
```

**Comment by VeNoMouS** [comment]
1.2.40 Pushed after some user testing.
