### ISSUE TITLE
Anticaptcha consumes too much balance

### ISSUE THREAD

**Issue by andress134** [VeNoMouS/cloudscraper#228]
Summary.

## Expected Result

Hello, have tested to bypass hcaptcha using anti-captcha, all work fine, just a problem, use to much $ using multi requests/threads, in 2 mins have used 1$ balance without proxies, proxyless
I don't know if it is a bug or is nomal, but i know with cloudscraper (nodejs) just used 0.02$

Also, tested 2captcha, but can't bypass hcaptcha, dont have any error, just try and waiting, but nothing
tested url : https://exitus.xyz

## Actual Result

What happened instead.

## Reproduction Steps 

```python
import cloudscraper

scraper = cloudscraper.create_scraper(
  interpreter='nodejs',
  recaptcha={
    'provider': 'anticaptcha',
    'api_key': 'my-key'
  }
)

scraper.get(url)
```

## System Information

    $ python -m cloudscraper.help

```python
{
    "platform": {
        "system": "Linux",
        "release": "4.9.0-12-amd64"
    },
    "interpreter": {
        "version": "3.5.3",
        "name": "CPython"
    },
    "cloudscraper": "1.2.40",
    "requests": "2.12.4",
    "urllib3": "1.24.3",
    "OpenSSL": {
        "version": "OpenSSL 1.1.1  11 Sep 2018",
        "ciphers": "get_ciphers() is unsupported"
    }
}

```

## Debug Log
- Add `debug=True` to `create_scraper()`

```
<paste_here>
```

This command is only available on cloudscraper v1.2.33 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system).

**Comment by VeNoMouS** [comment]
re threads / sessions... are you using a new create_scraper each time? are you caching your cookies / headers ? are you using multiple proxies? you do realize that Cloudflare cookies are only valid for the ip / subnet you solve on.

This is not a bug, I am not going to do that for you, that code logic is entirely up to you if you are switching proxies etc, it is up to you to manage your headers / cookies in a caching manner.

**Comment by andress134** [comment]
Im not using proxies, just multi threads, and no just one time create_scraper 
I will check my script again to see

**Comment by VeNoMouS** [comment]
Paste example code if you want some help

**Comment by andress134** [comment]
> Paste example code if you want some help

``python
import cloudscraper

def bypass():
	scraper = cloudscraper.create_scraper(
  interpreter='nodejs',
  recaptcha={
    'provider': 'anticaptcha',
    'api_key': 'key'
  }
)

	time.sleep(5)
	while True:
		while oo:
			try:
				scraper.get(uri)
				print(Fore.GREEN + "Conexion Succesed")
				try:
					for g in range(per):
						scraper.get(uri)
						print(Fore.GREEN + "Conexion Succesed")
					scraper.close()
				except:
					s.close()
			except:
				scraper.close()
				print(Fore.RED + "Conexion Failed")


if __name__ == "__main__":
	main()
```
