### ISSUE TITLE
No module named 'pyparsing'

### ISSUE THREAD

**Issue by Bertooooooo** [VeNoMouS/cloudscraper#231]
Hello, i tried to convert the file .py to file .exe with pyinstaller, but when i try to open the file .exe i get first "ERROR:root:Unable to load native interpreter" and in the seond line "No module named 'pyparsing'. When converting to .exe i wrote --add-data <cloudflare path>. I tried to do the same with pyparsing path inserting the pip package path but i get the same error. Thanks in advance.

Python version -> 3.8
Pyparsing version -> 2.4.7
Cloudscraper version -> 1.2.40

**Comment by 102flex** [comment]
I think there is already an solved ticket for this problem. Check the solved tickets👌🏼

**Comment by Bertooooooo** [comment]
Hello @102flex thanks for the answer, i already checked that ticket but i think it's not the same issue. I have this problem when running the file.exe not whit the .py file.

**Comment by Bertooooooo** [comment]
Update: I solved adding --hidden-import pyparsing
