### ISSUE TITLE
[Not a Bug] Need some help

### ISSUE THREAD

**Issue by Danny1994d** [VeNoMouS/cloudscraper#234]
Summary.

## Expected Result

Hello, when i try to bypass uam he ask me for upgrading openssl, but when im upgrading openssl script dot work

`
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.1.0l  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.`

How can disable it on python or installed to work? for exemple on js just i set strict-ssl false

my os : Debian 9 64bit

## Actual Result

What happened instead.

## Reproduction Steps 

```python
import cloudscraper

def bypass():
    per = '70'
    pprr = open(lista).readlines()
    proxy = random.choice(pprr).strip().split(":")
    scraper = cloudscraper.create_scraper(delay=0)
    scraper .proxies = {}
    scraper .proxies['http'] = 'http://'+str(proxy[0])+":"+str(proxy[1])
    scraper .proxies['https'] = 'https://'+str(proxy[0])+":"+str(proxy[1])
    time.sleep(3)
```

## System Information

    $ python -m cloudscraper.help

```python
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.1.0l  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
{
    "platform": {
        "system": "Linux",
        "release": "4.9.0-4-amd64"
    },
    "interpreter": {
        "version": "3.5.3",
        "name": "CPython"
    },
    "cloudscraper": "1.2.40",
    "requests": "2.23.0",
    "urllib3": "1.25.9",
    "OpenSSL": {
        "version": "OpenSSL 1.1.0l  10 Sep 2019",
        "ciphers": "get_ciphers() is unsupported"
    }
}
```

## Debug Log
- Add `debug=True` to `create_scraper()`

```
<paste_here>
```

This command is only available on cloudscraper v1.2.33 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system).

**Comment by VeNoMouS** [comment]
FWIW ,

Debian is up to 10.4... considered doing a dist-upgrade?? **Debian 9 is 3 years old....**

Otherwise you'll need to manually upgrade OpenSSL to as least 1.1.x and recompile Python agaist the new OpenSSL

```python
import cloudscraper
def bypass():
    per = '70'

    with open(lista, 'r') as ourFile:
        pprr = ourFile.readlines()
    
    proxy = random.choice(pprr).strip().split(":")

    scraper = cloudscraper.create_scraper()
    scraper.proxies = {
        'http' : 'http://{}:{}'.format(proxy[0], proxy[1]),
        'https' : 'https://{}:{}'.format(proxy[0], proxy[1])
    }

```
