### ISSUE TITLE
Captcha Proxy Support

### ISSUE THREAD

**Issue by 2020iscancelled** [VeNoMouS/cloudscraper#244]
More than a bug or actually issue, it's more some sort of suggestion...
Is there any chance, that you could add support for proxies when requesting the captcha? It seems like CF requires the captcha to be solved on the same IP as it gets submitted... 
## Expected Result
Example: 2captcha
Passing the used proxy in the POST data should basically solve the issue
```
data = {
            'key': self.api_key,
            'pageurl': url,
            'json': 1,
            'soft_id': 5507698,
            'proxy':myProxy, //either as ip:port or user:pass@ip:port
            'proxytype':myProxyType //http, https, socks4, socks5
        }
```

I don't know if it's in your interest of integrating support for this feature, but it would be pretty fine...

**Comment by VeNoMouS** [comment]
I will add support in due to the recent change, if i don't complete it tomorrow night, i'll do it over the weekend.

**Comment by VeNoMouS** [comment]
ALSO... FWIW it appears the regex on the `Captcha` detection is broken, data-key has been removed from the forum so ill address that as well.. ill make this ticket as bug

**Comment by VeNoMouS** [comment]
For those wondering about this...

![image](https://user-images.githubusercontent.com/597545/85911092-de182f00-b876-11ea-8c42-95d72a089e79.png)

**Comment by VeNoMouS** [comment]
Anyone got a v1 page with hCaptcha as an example test?

**Comment by Wyvern-Balls** [comment]
Hi sir, how about add https proxy server to your repo? And send it as proxy!

**Comment by VeNoMouS** [comment]
I have started to implement this into the dev branch, 2captcha has been completed

**Comment by VeNoMouS** [comment]
Introduced into 1.2.44 for anti-captcha and 2captcha.
