### ISSUE TITLE
get_tokens not working 

### ISSUE THREAD

**Issue by akmalff** [VeNoMouS/cloudscraper#245]
Morning Venomous, i have issue with get_tokens not working for me while normal get works.
I cannot get CF tokens get using get_tokens().

Below is the test code:

```
import cloudscraper
url = 'https://www.uniqlo.com/jp/store/feature/uq/jacketcoat/women/'
```
## test 1
`cookie_value, user_agent = cloudscraper.get_tokens(url)`

return ==> {'__cfduid': '', 'cf_clearance': ''} Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.0.1 Chrome/65.0.3325.230 Safari/537.36

## test 2
```
cloudscraper_ = cloudscraper.create_scraper()
res = cloudscraper_.get(url)
```

return ==> <Response [200]>

## System Information
Cloudscraper version = 1.2.40
Python = 3.5.2
OS = macOs Mojave & Ubuntu 16.04.4 LTS

**Comment by VeNoMouS** [comment]
There is no IUAM on `https://www.uniqlo.com/jp/store/feature/uq/jacketcoat/women/`
