### ISSUE TITLE
!!Back!!!

### ISSUE THREAD

**Issue by VeNoMouS** [VeNoMouS/cloudscraper#247]
Hi guys!!!

So many of you reached out over the past week with concerns, that I had closed shop and shutdown :heart: :heart: :heart:, cheers guys I really appreciated that love and support that you gave me.

I didn't close my github / repos... my github account got **flagged**.

# So.... What Happened?

In short my account was flagged due to profanity used in a comment (we all know the comment) and it was reported, which is fair enough, it was a knee jerk reaction by other comments being made, and at the time I got sucked in.

# Anyway..

On wards and upwards... 

![image](https://user-images.githubusercontent.com/597545/86852300-9ca24200-c108-11ea-9bbe-a86d20c908ad.png)

**Comment by NoahCardoza** [comment]
Welcome back!

**Comment by rexop** [comment]
Great to see you back. I too got scared and even went on Twitter to look for you. (But you dont seem to have used your Twitter account in years... lol)

Anyway.... Good to see you back! :D Finally.

**Comment by Shanksee** [comment]
Welcome back mate!

**Comment by shakeyourbunny** [comment]
>I didn't close my github / repos... my github account got flagged.

Welcome to the Club "Victims of the Microsoft Code of Conduct".

**Comment by bjgood** [comment]
He must have a png for every situation. Must be a massive collection.
Later...

**Comment by VeNoMouS** [comment]
@rexop it hasnt died, v1 still exists i still maintain cloudscraper, though my time is utilized more on the paid version

**Comment by dessalines** [comment]
Welcome back! Whew, I was pretty scared.

**Comment by jairoxyz** [comment]
Welcome back, glad all is OK :)
