### ISSUE TITLE
CAPTCHA New Challenge

### ISSUE THREAD

**Issue by andress134** [VeNoMouS/cloudscraper#248]
Summary.

## Expected Result

Hello, i see cloudflare has updated captcha, new challenge look like uam, but is captcha + uam
exemple url : http://ovh-captcha.nightdev.xyz
Cloudscraper can't bypass it, do u will update for new challenge? or u got a premium version that can bypass it?

## Actual Result

What happened instead.

## Reproduction Steps 

```python
import cloudscraper

```

## System Information

    $ python -m cloudscraper.help

```python
<paste here>
```

## Debug Log
- Add `debug=True` to `create_scraper()`

```
<paste_here>
```

This command is only available on cloudscraper v1.2.33 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system).

**Comment by VeNoMouS** [comment]
Hi there,

I was working on v1 hCaptcha landing page, sorry other projects came up in the way, expect a release over next couple days to address this.,

Additionally there's actually a ticket already open for this issue -> #244
