### ISSUE TITLE
Welcome back, sorry but its not working again.

### ISSUE THREAD

**Issue by FalconEagleTest** [VeNoMouS/cloudscraper#250]
i just tested it on:
"https://soap2day.to"
and i am getting:
"Detected the new Cloudflare challenge."
can you please take a look?
thanks a lot and again welcome back.

**Comment by VeNoMouS** [comment]
Sorry what am i looking at? the v2 challenge is not covered by the opensource version of cloudscraper, it only solves the v1 challenge, i do have a solution for the v2 challenge but its a subscription based model which has been discussed in numerous tickets prior .. contact me on discord if you wish to discuss further.

**Comment by VeNoMouS** [comment]
@FalconEagleTest I will update the exception msg to reflect that this is not available in the opensource free version
