### ISSUE TITLE
Detected the new Cloudflare challenge

### ISSUE THREAD

**Issue by andreighinea1** [VeNoMouS/cloudscraper#251]
I wanted to get requests from [AnimeUltima](https://www1.animeultima.to/), but it gives me an error.

## Expected Result

Get requests from [AnimeUltima](https://www1.animeultima.to/)

## Actual Result

Got the following error:
`cloudscraper.exceptions.CloudflareChallengeError: Detected the new Cloudflare challenge.`

## Reproduction Steps 

Run this code:
```python
import cloudscraper as cfscrape

url = 'https://www1.animeultima.to/a/rezero-kara-hajimeru-isekai-seikatsu-2nd-season_517659'
scraper = cfscrape.create_scraper()
content = scraper.get(url).text

print(content)
```

## System Information

[Sys Info(Pastebin)](https://pastebin.com/s2wWawiY)

## Debug Log

[Log(Pastebin)](https://pastebin.com/ryb5gxce)

**Comment by VeNoMouS** [comment]
This is not a bug nor is it a problem.

This detected cloudflare's v2 challenge , which is not available in the free opensource version, contact me via discord if you wish to discuss a subscription plan to v2 challenges.
