### ISSUE TITLE
Detected the new Cloudflare challenge.

### ISSUE THREAD

**Issue by BrtFix** [VeNoMouS/cloudscraper#257]
Hello, I get this error for the site below. Can you please check?

**ERROR: 
Detected the new Cloudflare challenge.**

_I waited for the plugin to be updated, but that didn't work either._

Not work: https://goloady.com/

**Comment by VeNoMouS** [comment]
Not a bug, its detected a verion 2 challenge from cloudflare, which i do not provide a free solution for.

**Comment by BrtFix** [comment]
Is there a program or other solution that I can use over localhost that you
know?
or is there a browser plug-in or browser type that I can use on localhost?
or another solution.


------------------
Best Regards,


VeNoMouS <notifications@github.com>, 25 Tem 2020 Cmt, 14:43 tarihinde şunu
yazdı:
