### ISSUE TITLE
[Error] ValueError: Captcha

### ISSUE THREAD

**Issue by Shinyhero36** [VeNoMouS/cloudscraper#29]
Hi,
I downloaded cloudscraper with pip and try the example on the github page
```python
import cloudscraper
scraper = cloudscraper.create_scraper(debug=True)
print(scraper.get("https://www.japscan.to/lecture-en-ligne/solo-leveling/69/").content)
```

with this url: "https://www.japscan.to/".
But i got an error:
https://pastebin.com/wdmcmLv3

**Comment by VeNoMouS** [comment]
Please supply with 

```
import cloudscraper
scraper = cloudscraper.create_scraper(debug=True)
print(scraper.get("https://www.japscan.to/lecture-en-ligne/solo-leveling/69/").content)
```

And pastebin the whole output like its requested in the readme... 

You have got a capthca... either due to CF changing their algo... or perhaps something else, but its impossible to tell without you supplying information.

**Comment by frozenpandaman** [comment]
@VeNoMouS I'm getting the same error too. Here's my output from following your steps above (though with a request to mangadex.org instead, since that's the site giving me the error/reCAPTCHA challenge: https://pastebin.com/Qbk3YDFt

**Comment by pro-src** [comment]
> Would sending a specific cookie with get() (maybe cf_clearance...?) after the user navigates to the site in their browser and solves the reCAPTCHA manually prevent this error from being triggered in the script?

@frozenpandaman Shouldn't have to but... I think that's a real interesting idea, sorta like an OAuth redirect URL opening in the web browser, right?

It would require Cloudscraper to run a server and use of python's webbrowser (stdlib) to open the URL. Once opened, the page would solve the challenge and post the answer back to the server. It would make use of any web browser available and wouldn't require any user interaction.

Quite a few drawbacks though... I wouldn't think it to be something that the average user would want.
I would definitely give a +1 if somebody wants to write this an interpreter/plugin since it only requires python's stdlib. However, I don't think it's something that should reside in this repository.

**Comment by pro-src** [comment]
@frozenpandaman Would you install a browser web extension that Cloudscraper could communicate with for this purpose? I'd be willing to write one!

**Comment by gumuliya** [comment]
> Please supply with
> 
> ```
> import cloudscraper
> scraper = cloudscraper.create_scraper(debug=True)
> print(scraper.get("https://www.japscan.to/lecture-en-ligne/solo-leveling/69/").content)
> ```
> 
> And pastebin the whole output like its requested in the readme...
> 
> You have got a capthca... either due to CF changing their algo... or perhaps something else, but its impossible to tell without you supplying information.

I got the same error too, here is the output:
https://pastebin.com/wdmcmLv3

**Comment by VeNoMouS** [comment]
Cheers guys I will look into this later after ive done my day job

**Comment by VeNoMouS** [comment]
Sorry while I got you boys here can you please run the following code and paste me the output

```
import ssl
ciphers = [
    'GREASE_3A', 'GREASE_6A', 'AES128-GCM-SHA256', 'AES256-GCM-SHA256', 'AES256-GCM-SHA384', 'CHACHA20-POLY1305-SHA256',
    'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-GCM-SHA384',
    'ECDHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-CHACHA20-POLY1305-SHA256', 'ECDHE-RSA-CHACHA20-POLY1305-SHA256',
    'ECDHE-RSA-AES128-CBC-SHA', 'ECDHE-RSA-AES256-CBC-SHA', 'RSA-AES128-GCM-SHA256', 'RSA-AES256-GCM-SHA384',
    'ECDHE-RSA-AES128-GCM-SHA256', 'RSA-AES256-SHA', '3DES-EDE-CBC'
]

cipherSuite = ''

ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)

for cipher in ciphers:
    try:
        ctx.set_ciphers(cipher)
        cipherSuite = '{}:{}'.format(cipherSuite, cipher).rstrip(':').lstrip(':')
    except ssl.SSLError:
        pass
    
print (cipherSuite)
```

Just so I can get an idea of your cipher suites as well..

**Comment by pro-src** [comment]
For python 3.5+ at least, it's going to be more informative to get the [shared ciphers](https://docs.python.org/3/library/ssl.html#ssl.SSLSocket.shared_ciphers).

```py
import ssl
import socket

hostname = 'pro-src.com'

ciphers = [
    'GREASE_3A', 'GREASE_6A', 'AES128-GCM-SHA256', 'AES256-GCM-SHA256', 'AES256-GCM-SHA384', 'CHACHA20-POLY1305-SHA256',
    'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-GCM-SHA384',
    'ECDHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-CHACHA20-POLY1305-SHA256', 'ECDHE-RSA-CHACHA20-POLY1305-SHA256',
    'ECDHE-RSA-AES128-CBC-SHA', 'ECDHE-RSA-AES256-CBC-SHA', 'RSA-AES128-GCM-SHA256', 'RSA-AES256-GCM-SHA384',
    'ECDHE-RSA-AES128-GCM-SHA256', 'RSA-AES256-SHA', '3DES-EDE-CBC'
]

cipherSuite = ''

ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)

for cipher in ciphers:
    try:
        ctx.set_ciphers(cipher)
        cipherSuite = '{}:{}'.format(cipherSuite, cipher).rstrip(':').lstrip(':')
    except ssl.SSLError:
        pass

print('Our ciphers: {}'.format(cipherSuite))

ctx = ssl.create_default_context()
ctx.set_ciphers(cipherSuite)

with ssl.create_connection((hostname, 443)) as sock:
  with ctx.wrap_socket(sock, server_hostname=hostname) as ssock:
    print('Cipher: {}'.format(ssock.cipher()))
    print('Shared ciphers: {}'.format(ssock.shared_ciphers()))
```

```
Our ciphers: AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
Cipher: ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
Shared ciphers: [('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256), ('TLS_CHACHA20_POLY1305_SHA256', 'TLSv1.3', 256), ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128), ('AES128-GCM-SHA256', 'TLSv1.2', 128), ('AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-RSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-ECDSA-AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-RSA-AES256-GCM-SHA384', 'TLSv1.2', 256)]
```

**Comment by gumuliya** [comment]
> Sorry while I got you boys here can you please run the following code and paste me the output
> 
> ```python
> import ssl
> ciphers = [
>     'GREASE_3A', 'GREASE_6A', 'AES128-GCM-SHA256', 'AES256-GCM-SHA256', 'AES256-GCM-SHA384', 'CHACHA20-POLY1305-SHA256',
>     'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-GCM-SHA384',
>     'ECDHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-CHACHA20-POLY1305-SHA256', 'ECDHE-RSA-CHACHA20-POLY1305-SHA256',
>     'ECDHE-RSA-AES128-CBC-SHA', 'ECDHE-RSA-AES256-CBC-SHA', 'RSA-AES128-GCM-SHA256', 'RSA-AES256-GCM-SHA384',
>     'ECDHE-RSA-AES128-GCM-SHA256', 'RSA-AES256-SHA', '3DES-EDE-CBC'
> ]
> 
> cipherSuite = ''
> 
> ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
> 
> for cipher in ciphers:
>     try:
>         ctx.set_ciphers(cipher)
>         cipherSuite = '{}:{}'.format(cipherSuite, cipher).rstrip(':').lstrip(':')
>     except ssl.SSLError:
>         pass
>     
> print (cipherSuite)
> ```
> 
> Just so I can get an idea of your cipher suites as well..

sorry for late repply
the output is:
AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256

**Comment by gumuliya** [comment]
> For python 3.5+ at least, it's going to be more informative to get the [shared ciphers](https://docs.python.org/3/library/ssl.html#ssl.SSLSocket.shared_ciphers).
> 
> ```python
> import ssl
> import socket
> 
> hostname = 'pro-src.com'
> 
> ciphers = [
>     'GREASE_3A', 'GREASE_6A', 'AES128-GCM-SHA256', 'AES256-GCM-SHA256', 'AES256-GCM-SHA384', 'CHACHA20-POLY1305-SHA256',
>     'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-GCM-SHA384',
>     'ECDHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-CHACHA20-POLY1305-SHA256', 'ECDHE-RSA-CHACHA20-POLY1305-SHA256',
>     'ECDHE-RSA-AES128-CBC-SHA', 'ECDHE-RSA-AES256-CBC-SHA', 'RSA-AES128-GCM-SHA256', 'RSA-AES256-GCM-SHA384',
>     'ECDHE-RSA-AES128-GCM-SHA256', 'RSA-AES256-SHA', '3DES-EDE-CBC'
> ]
> 
> cipherSuite = ''
> 
> ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
> 
> for cipher in ciphers:
>     try:
>         ctx.set_ciphers(cipher)
>         cipherSuite = '{}:{}'.format(cipherSuite, cipher).rstrip(':').lstrip(':')
>     except ssl.SSLError:
>         pass
> 
> print('Our ciphers: {}'.format(cipherSuite))
> 
> ctx = ssl.create_default_context()
> ctx.set_ciphers(cipherSuite)
> 
> with ssl.create_connection((hostname, 443)) as sock:
>   with ctx.wrap_socket(sock, server_hostname=hostname) as ssock:
>     print('Cipher: {}'.format(ssock.cipher()))
>     print('Shared ciphers: {}'.format(ssock.shared_ciphers()))
> ```
> 
> ```
> Our ciphers: AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
> Cipher: ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
> Shared ciphers: [('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256), ('TLS_CHACHA20_POLY1305_SHA256', 'TLSv1.3', 256), ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128), ('AES128-GCM-SHA256', 'TLSv1.2', 128), ('AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-RSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-ECDSA-AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-RSA-AES256-GCM-SHA384', 'TLSv1.2', 256)]
> ```

@pro-src, here is the output:
Our ciphers: AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
Cipher: ('ECDHE-ECDSA-AES128-GCM-SHA256', 'TLSv1.2', 128)
Shared ciphers: [('AES128-GCM-SHA256', 'TLSv1.2', 128), ('AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-RSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-ECDSA-AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-RSA-AES256-GCM-SHA384', 'TLSv1.2', 256)]

**Comment by pro-src** [comment]
@gumuliya Doing a diff on the shared ciphers shows that the problem is actually the absence of TLSv1.3 ciphers which is what I discovered on nodejs: https://github.com/codemanki/cloudscraper/issues/211

You can read more info on how I came to that conclusion here: https://github.com/codemanki/cloudscraper/pull/212#issuecomment-488537157

There is not any difference in the ciphers that are being set in the above code for you and I. It's the ciphers that are being shared that is the problem.

```
2,4d1
< ('TLS_AES_256_GCM_SHA384','TLSv1.3', 256),
< ('TLS_CHACHA20_POLY1305_SHA256', 'TLSv1.3', 256),
< ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128),
```

*I would advise fixing it the same way that I fixed it for (cloudscraper ***.js***)*
https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_cipher_list.html

By adding these ciphers and not removing ciphers since that affects compatibility unless there is a problematic cipher determined. If a problematic cipher is determined, I would recommend that it alone be removed from the list of ciphers.

These are the default TLSv3 ciphers that are secure and should be backported to openssl versions prior to `v1.1.1`.
```
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_CCM_SHA256
TLS_AES_128_CCM_8_SHA256
```

**Comment by pro-src** [comment]
Also, it ***should not*** be necessary to do a try catch on the cipher list control string in the way that is currently being done since openssl will simply ignore unsupported ciphers. I don't know whether or not python is checking the ciphers and raising errors but openssl does not. If you're using an old version of openssl that doesn't support these ciphers then the settings will not have any effect. *Upgrade your python...* Python 2 is about to reach End-Of-Life....

**Comment by VeNoMouS** [comment]
@gumuliya thanks for sharing that information... looking at my own system im pretty much the same as you are...

```
Our ciphers: AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
Cipher: ('ECDHE-ECDSA-AES128-GCM-SHA256', 'TLSv1.2', 128)
Shared ciphers: [('AES128-GCM-SHA256', 'TLSv1.2', 128), ('AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-RSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-ECDSA-AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-RSA-AES256-GCM-SHA384', 'TLSv1.2', 256)]
```

Lets see if we can get to the bottom of this :)

**Comment by VeNoMouS** [comment]
ok @Shinyhero36 looking at yours... your header order is out of order...

ie mine

```
< GET /lecture-en-ligne/solo-leveling/69/ HTTP/1.1
< Host: www.japscan.to
< Connection: keep-alive
< Upgrade-Insecure-Requests: 1
< User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 6 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.85 Mobile Safari/537.36
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
< Accept-Encoding: gzip, deflate, br
< Accept-Language: en-US,en;q=0.9
<
```

```
< GET /lecture-en-ligne/solo-leveling/69/ HTTP/1.1
< Host: www.japscan.to
< Connection: keep-alive
< Upgrade-Insecure-Requests: 1
< User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.28 Safari/537.36
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate, br
<
```


notice how 

`Accept-Language` and `Accept-Encoding` in the wrong order on yours... and trust me, it does matter with CF as we discovered awhile ago... this could be an issue with your OrderedDict or your requests library...  can you please show `pip freeze` for __collections__ and __requests__

**Comment by VeNoMouS** [comment]
Actually nm revering the browser json it appears that is correct I will need to manually double check that order however..

**Comment by VeNoMouS** [comment]
Tested with

```
< GET /lecture-en-ligne/solo-leveling/69/ HTTP/1.1
< Host: www.japscan.to
< Connection: keep-alive
< Upgrade-Insecure-Requests: 1
< User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.28 Safari/537.36
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate, br
<
```

and solved challenge fine...

**Comment by Shinyhero36** [comment]
I am currently in class I will do it as soon as possible @VeNoMouS

**Comment by VeNoMouS** [comment]
@Shinyhero36 all good mate its 1am here im going to goto bed soon, sorry to ask this info from you just helps us narrow stuff down... can you also give me the `pip freeze` for __cryptography__ thanks.

**Comment by pro-src** [comment]
... `python -c "import ssl; print ssl.OPENSSL_VERSION"`

**Comment by pro-src** [comment]
Right so like I said... Those TLSv1.3 options should be backported.

**Comment by VeNoMouS** [comment]
@pro-src the tls 1.3 isn't relevant... as mine solves fine..

**Comment by gumuliya** [comment]
@pro-src , OpenSSL 1.1.0j  20 Nov 2018

**Comment by pro-src** [comment]
@VeNoMouS  I guaranteed that if he modifies the transport adapter that is being mounted for HTTPS connections to use the TLSv1.1 protocol which doesn't have the signature algorithms extension that the problem will go away. In tests, I have seen that the difference in the signature was the absence of the TLSv1.3 ciphers (ssllabs did report other unclear differences) but it has already solved this same problem for somebody already... so yes, TLSv1.3 is very much of relevance unless you're going to ignore that fact.

To perform this simple test and verify what I'm saying:
```py
create_urllib3_context(ssl.PROTOCOL_TLSv1)
ctx.options &= ~ssl.OP_NO_SSLv1_1
```

IIRC, you upgraded your openssl version to match mine when we were look at this before, remember???? It would make sense for him to test the theory unless you have a better one.

**Comment by pro-src** [comment]
@gumuliya Thanks, it matches exactly what I expected. openssl version that is less than `v1.1.1`

**Comment by VeNoMouS** [comment]
`IIRC, you upgraded your openssl version to match mine when we were looking at this before, remember???? ` ... i never upgraded my openssl

**Comment by VeNoMouS** [comment]
also I think you mean `OP_NO_TLSv1_1` also... `PROTOCOL_TLSv1` is depreciated https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_TLSv1_1

**Comment by pro-src** [comment]
Fixed, Of course it is ***deprecated***.

**Comment by pro-src** [comment]
https://github.com/codemanki/cloudscraper/issues/211#issuecomment-487980993
Anyways... I'm hoping off of this issue. Best of luck guys...

**Comment by Shinyhero36** [comment]
Sorry for my late response here is the answer 
'''
AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
'''
here is the pip freeze:
'''
beautifulsoup4==4.6.0
Brotli==1.0.7
bs4==0.0.1
cachetools==3.1.0
certifi==2017.4.17
cfscrape==1.9.7
chardet==3.0.4
cloudscraper==1.1.5
colorama==0.3.9
cursor==1.2.0
enum34==1.1.6
get==2019.4.13
google-api-python-client==1.7.8
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.3.0
halo==0.0.23
httplib2==0.12.3
idna==2.5
Js2Py==0.63
log-symbols==0.0.12
mfetcher==0.1
oauthlib==3.0.1
post==2019.4.13
progressbar2==3.39.3
public==2019.4.13
pyasn1==0.4.5
pyasn1-modules==0.2.5
pyjsparser==2.7.1
python-utils==2.3.0
pytz==2019.1
query-string==2019.4.13
request==2019.4.13
requests==2.21.0
requests-oauthlib==1.2.0
requests-toolbelt==0.9.1
rsa==4.0
six==1.11.0
soupsieve==1.9.1
spinners==0.0.23
termcolor==1.1.0
tqdm==4.31.1
tzlocal==1.5.1
uritemplate==3.0.0
urllib3==1.23
win-inet-pton==1.0.1
'''

**Comment by gumuliya** [comment]
@pro-src, update my openssl to v1.1.1b and no more captcha
here the test output :
[(https://pastebin.com/rf05263a)]

**Comment by VeNoMouS** [comment]
@Shinyhero36 can you tell what version `cryptography` module is...

**Comment by Shinyhero36** [comment]
I didn't have the package i just install it here is the version ```cryptography==2.6.1```

**Comment by VeNoMouS** [comment]
Did that make any difference @Shinyhero36 ? just trying to workout what the exact difference is between yourself and I as I have the same openssl version.

**Comment by Shinyhero36** [comment]
It seems there aren't any differences
https://pastebin.com/Ja305udq

**Comment by VeNoMouS** [comment]
Can you try what @pro-src suggested... edit cloudscraper `__init__.py` and change the CipherSuiteAdapter to the following and test it for me.

```
class CipherSuiteAdapter(HTTPAdapter):

    def __init__(self, cipherSuite=None, **kwargs):
        self.cipherSuite = cipherSuite
        super(CipherSuiteAdapter, self).__init__(**kwargs)

    ##########################################################################################################################################################

    def init_poolmanager(self, *args, **kwargs):
        kwargs['ssl_context'] = create_urllib3_context(ssl.PROTOCOL_TLSv1)
        kwargs['ssl_context'].options &= ~ssl.OP_NO_TLSv1_1
        return super(CipherSuiteAdapter, self).init_poolmanager(*args, **kwargs)

    ##########################################################################################################################################################

    def proxy_manager_for(self, *args, **kwargs):
        kwargs['ssl_context'] = create_urllib3_context(ssl.PROTOCOL_TLSv1)
        kwargs['ssl_context'].options &= ~ssl.OP_NO_TLSv1_1
        return super(CipherSuiteAdapter, self).proxy_manager_for(*args, **kwargs)
```

**Comment by Shinyhero36** [comment]
```__init.py__``` change

output:
https://pastebin.com/T4S1aCVq

**Comment by VeNoMouS** [comment]
@Shinyhero36 one more test... just so i can write a work around gimmie a sec to code it up and test

**Comment by VeNoMouS** [comment]
I will have to write this later I have to go into the office for a bit, @Shinyhero36 and @gumuliya can you both not change anything on your system / code you're ideal test candidates for work around... I want to check some things and put a work around in place for the core code to detect specific attributes

Anyway I gotta get going I will talk to you guys later, and I appreciate helping me / us / everyone diagnose this to make the library better :)

**Comment by pro-src** [comment]
I'm just commenting to clearly state the problem. Feel free to @mention me though...

As it turns out, urllib3 is already doing exactly what I have recommended as a fix but it has no effect since the ciphers are being overridden...
```py
from urllib3.util.ssl_ import DEFAULT_CIPHERS
print(DEFAULT_CIPHERS)
# TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:...
```
As we can see, blindly removing ciphers is not a good idea.

> If a problematic cipher is determined, I would recommend that it alone be removed from the list of ciphers.

Quoting myself. :point_up: 
This is how you would determine whether or not to play with the ciphers.
```py
import ssl
cryptography_installed = false
try:
  import cryptography
  # Check `cryptography.__version___` here
  cryptography_installed = true
except ImportError:
  pass
# This is not a good idea but solves the `cryptography` package problem....
# The `cryptography` package problem doesn't apply to everybody...
if cryptograpthy_installed:
  from urllib3.util.ssl_ import DEFAULT_CIPHERS
  # Again, I do not believe this should be done.
  ciphers = DEFAULT_CIPHERS.replace('ECDH+AESGCM', '')
  # If cryptography is introducing a bad cipher, use the negation operator
  # ciphers += ':!BAD_CIPHER';
  # Proceed to mount the transport adapter
else:
  # Do nothing...
  pass
```

@Shinyhero36 Please remove the following line from `cloudscraper/__init__.py` to confirm this.
```py
self.mount('https://', CipherSuiteAdapter(self.loadCipherSuite()))
```
If you don't get a CAPTCHA, it is confirmed.
For the record, I was against removing ciphers from the beginning.

**Comment by pro-src** [comment]
@Shinyhero36 Please remove the cryptography package if you do get a CAPTCHA before posting your response since that affects the aforementioned test... Thanks...

**Comment by VeNoMouS** [comment]
```
Update2: The only reason that @VeNoMouS hasn't completely broken cloudscraper by overriding the ciphers is that openssl versions >=1.1.1 know that TLSv1.3 is always relevant and is protecting you... Basically, it does the right thing anyway because you have support for TLSv1.3... lol
```

@pro-src excuse me?

**Comment by pro-src** [comment]
@VeNoMouS I can't think of any excuses given how many times I recommended a completely different approach.

> pull your head out of your arse

Calm down now son...

**Comment by Shinyhero36** [comment]
@pro-src , sorry to be late
here is the output:
```
AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
```

**Comment by VeNoMouS** [comment]
@Shinyhero36 wondering if your available to run some tests for me?

**Comment by VeNoMouS** [comment]
I think i've worked out the root cause.

**Comment by pannal** [comment]
@VeNoMouS I'm available as well, as subscene doesn't like the current approach, either.

I'd also love to join you guys on Discord, whatever's currently happening with this project (there seems to be beef between you and @pro-src)

**Comment by VeNoMouS** [comment]
@pannal flick me an email i'll send you an invite

**Comment by VeNoMouS** [comment]
@Shinyhero36 , @gumuliya I have released 1.1.6 , thanks to @pannal who had some systems that were slightly out of date that we were able to test 3 different scenarios on..

**Comment by gumuliya** [comment]
@VeNoMouS I tested v1.1.6 on my other device with python v2.7 & v3.5 both OpenSSL 1.1.0j 20 Nov 2018.
With python 2.7 captcha error is raised :
`https://pastebin.com/yBjSZcXb`

`asn1crypto==0.24.0
Brotli==1.0.7
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
cloudscraper==1.1.5
cryptography==2.6.1
enum34==1.1.6
idna==2.8
ipaddress==1.0.22
Js2Py==0.63
pexpect==4.2.1
Pillow==4.0.0
ptyprocess==0.5.1
pycparser==2.19
pygobject==3.22.0
pyjsparser==2.7.1
python-apt==1.4.0b3
pytz==2019.1
requests==2.21.0
requests-toolbelt==0.9.1
RPi.GPIO==0.6.4
six==1.12.0
speedtest-cli==1.0.0
tzlocal==1.5.1
Unidecode==0.4.19`

With python 3.5 no captcha :
`https://pastebin.com/qcwYg31E`

`asn1crypto==0.24.0
Brotli==1.0.7
certifi==2019.3.9
chardet==3.0.4
cloudscraper==1.1.5
idna==2.8
Js2Py==0.63
pycparser==2.19
pyjsparser==2.7.1
pytz==2019.1
requests==2.21.0
requests-toolbelt==0.9.1
six==1.12.0
tzlocal==1.5.1
urllib3==1.24.3`

**Comment by VeNoMouS** [comment]
hi @gumuliya sorry i noticed some other things... can you jump to 1.1.8 sorry

**Comment by VeNoMouS** [comment]
@gumuliya all good?

**Comment by gumuliya** [comment]
with v1.1.8, both py2.7 and py3.5 raise captcha
py2.7 output :
`https://pastebin.com/bujDXX3p'

py3.5 output:
`https://pastebin.com/bujDXX3p`

**Comment by VeNoMouS** [comment]
@gumuliya can you jump on my discord? send me an email i'll flick you an invite.

**Comment by Shinyhero36** [comment]
@VeNoMouS yeh i am ready to test

**Comment by Shinyhero36** [comment]
> @Shinyhero36 wondering if your available to run some tests for me?

I am sorry i didn't receive the notification i am currently ready

**Comment by VeNoMouS** [comment]
@Shinyhero36 all good mate, just saw your email, have sent you an invite... if you are able to get on in the next 5 mins i can talk you through a test... I'm about to go out for a few hours

**Comment by VeNoMouS** [comment]
OK guys, 1.1.9 released, thank you to everyone (@gumuliya , @pannal , @krylancelo, @Shinyhero36)  for testing and confirming that all is working :)

**Comment by pannal** [comment]
@VeNoMouS I can't see the Discord that you invited me to before, anymore. Any specific reason for that?

**Comment by VeNoMouS** [comment]
@pannal check youre email
