### ISSUE TITLE
can im using custom user-agent ?

### ISSUE THREAD

**Issue by devprojectid** [VeNoMouS/cloudscraper#38]
i'ts possible to scrape cookies using custom user-agent ?
ex:
custom-ue = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"

**Comment by VeNoMouS** [comment]
You can but you will need to set the whole header order correctly... the user-agent is currently set from [this list](https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/browsers.json) randomly... Cloudflares Bot Inspection is now assessing the header's and header order... if you do set a custom user-agent via scraper.headers __YOU WILL NEED__ to set all the headers correctly to match a browser or face a possible reCaptcha , 403 or failed challenge response.
