### ISSUE TITLE
Download image file from a Cloudflare protected web. AKA Feature Request

### ISSUE THREAD

**Issue by OfficialSpade000** [VeNoMouS/cloudscraper#39]
There's this problem when trying to download a image from a cloudflare protected website using urllib

Here's the sample code.

```
import urllib.request
import random

DEFAULT_USER_AGENTS = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554 Safari/9537.53",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
]

DEFAULT_USER_AGENT = random.choice(DEFAULT_USER_AGENTS)

print(DEFAULT_USER_AGENT)

src = 'https://kissanime.ru/Special/CapImg/a0p3YnJsN251Tjh6NEtsZng0SWUvMFJYWHRZU1l1WktFbDVtVldVRlFkTnBObmcwcFRPVVphZk5PUGNoZWh3Ng==.jpg'
#src = 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
ex = list(src)
ex.reverse()
opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', DEFAULT_USER_AGENT)]
urllib.request.install_opener(opener)
urllib.request.urlretrieve(src, 'filename' + str(ex[3]) + str(ex[2]) + str(ex[1]) + str(ex[0]))
```

Note that I have two src var. kissanime have a cloudflare protected and google have none.

**Comment by HawkLiking** [comment]
Why urllib ?

Just use cloudscraper (this repo) with (or not) requests lib, nothing difficult here :)

**Comment by OfficialSpade000** [comment]
> Why urllib ?
> 
> Just use cloudscraper (this repo) with (or not) requests lib, nothing difficult here :)

Oh! I totally forgotten that we can also use cloudscraper. (I was thinking that time that only `urllib` was the only one that works in grabbing images). I'll try this [stack discussion](https://stackoverflow.com/questions/13137817/how-to-download-image-using-requests). Meanwhile I'm gonna close this issue.

**Comment by VeNoMouS** [comment]
@OfficialSpade000 refer to https://github.com/VeNoMouS/cloudscraper#usage if you need some guidance :)
