### ISSUE TITLE
Is it possible to use cookies until response is Cloudflare challange?

### ISSUE THREAD

**Issue by BarryThrill** [VeNoMouS/cloudscraper#41]
Hello!

This isn't a really issue but more of a question and an example of it would be nice to see.

My question is that is it possible to run a session where we call the cloudscraper once and use those cookies into the pages we use for requests and to refresh cloudscraper cookies until the requests returns a reponse of 502 (Which I believe means cloudflare challange)?

Would something like this be possible to do?

**Comment by VeNoMouS** [comment]
yup...Hey @BarryThrill , refer to https://github.com/VeNoMouS/cloudscraper#retrieving-a-cookie-dict-through-a-proxy

**Comment by BarryThrill** [comment]
Hmm alright! So I tried to use your example and also the retrieving-a-cookie-string method. What I tried first is that I tried to use ur code:
```
scraper = cloudscraper.create_create()
scraper.get('https://someite')

headers = scraper.headers
requests.get('https://somesite', headers=headers)
```
This just returned me a 503 response asking for Cloudflare challange.

I tried also to apply **__cfduid** and **cf_clearance=** in a cookie headers which also returned a response of 503 (Cloudflare challange). 

This is my code:

```

def get_scraper_cookies():
	
	url = 'https://.....'
    tokens, user_agent = cloudscraper.get_tokens(url)
    return tokens
	
	

def main():
    connected = False
    while not connected:

        try:

            grab_cookies = get_scraper_cookies(thread)

            url = 'https://.....'


            headers = {
                'Connection': 'keep-alive',
                'Cache-Control': 'no-cache',
                'dnt': '1',
                'Upgrade-Insecure-Requests': '1',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36',
                'Accept-Language': 'sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6',
                'cookie': '__cfduid=' + headers_done['__cfduid'] + '; cf_clearance=' + headers_done['cf_clearance']
            }

            proxies = get_random_proxy()
            r = requests.get(url, headers=headers, proxies=proxies, timeout=5)
	    print(r.status_code)
```
