### ISSUE TITLE
proxy issues, getting captcha challenge

### ISSUE THREAD

**Issue by JeanRon** [VeNoMouS/cloudscraper#43]
Hi, open this new ticket.

When i putting proxies on cloudscraper, i always get captcha challenge.

Ps: Can i  ini session on local ip and then navigate in the sites with proxies ?

**Comment by VeNoMouS** [comment]
```
Ps: Can i ini session on local ip and then navigate in the sites with proxies ?
```

yes, just `{}` the proxies in your scrapper session.

**Comment by VeNoMouS** [comment]
The only "major" thing is see is that requests uses urllib3 which inturn uses httplib to proxiy https requests... and this changes the request methodology from a `GET` to a `CONNECT`... 

I still need to investigate more

**Comment by JeanRon** [comment]
I tried this : `def IniSession(proxies,k):


    while 1 :

        print('Monitor {} - Try to ini session '.format(k))
        L = []
        s = cfscrape.create_scraper()
        proxie=None
        try:

            a = s.get('https://www.nakedcph.com/adidas-originals-yeezy-boost-350-v2-eg5293/p/7677', proxies=proxie)

            if a.status_code == 200 :

                print('Monitor {} - Ini success !'.format(k))
                proxie = random.choice(proxies)
                a = s.get('https://www.nakedcph.com/adidas-originals-yeezy-boost-350-v2-eg5293/p/7677', proxies=proxie)
                L.append(s)
                L.append(proxie)
                return L



        except Exception as e:

            print('Monitor {} - ERROR TO INI !{}'.format(k,e))
            pass`


output : 
Monitor 0 - Try to ini session 
Monitor 0 - Ini success !
Monitor -0 : Error in Monitorlinks ... Captcha

>

**Comment by VeNoMouS** [comment]
So... after much debugging... i just decided to install my own socks5 proxy locally to test with,... i don't get any reCaptcha's ... @JeanRon have you tested this out with a local proxy instead of a random public one?

**Comment by VeNoMouS** [comment]
That said... I am in the process of implementing some 3rd party reCaptcha solvers... so if you do want to use public proxies... you can solve the reCaptcha that way... but of course you will need to get an account with said 3rd party... but tbh they cheap as...

**Comment by JeanRon** [comment]
That not free public proxies, but they could be flag. Where did you make your proxies ? 
sounds good

**Comment by VeNoMouS** [comment]
I used `danted`

**Comment by VeNoMouS** [comment]
@JeanRon re those proxies?

**Comment by JeanRon** [comment]
Hi, proxies are form different servers, Linode, vultr etc ..

**Comment by VeNoMouS** [comment]
@JeanRon tbh, i think its because the exit nodes are known to CF... anyway i have started to introduce 3rd party reCaptcha resolvers into the code, currently anti-captcha.com is in there, and im working on deathbycaptcha atm, but there service seems to keep going down and giving me 500 errors... so it makes it hard to test / write for... 

I'm going to close this off as i do not believe this is a code based issue, as when i push it through private proxies i dont get captcha's but i do when i push it out open or well known proxy providers, including tor exit nodes... which leads me to believe CF is aware of the end points
