### ISSUE TITLE
What is reason DCMA notice

### ISSUE THREAD

**Issue by Piedrosys** [VeNoMouS/cloudscraper#44]
I see lot this on Github? Say not following license or steal?

I ***afirm*** that I have read the Guide to Submitting a DMCA Takedown
Notice: https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/
I ***afirm*** that I have read the DMCA Takedown Policy:
https://help.github.com/articles/dmca-takedown-policy/

**Are you the copyright owner or authorized to act on the copyright owner’s behalf?**
Yes. I am the copyright owner.

**Please provide a detailed description of the original copyrighted work that has allegedly been infringed. If possible, include a URL to where it is posted online.**

The original work is here:
https://github.com/codemanki/cloudscraper/blob/master/lib/browsers.json

**What files should be taken down? Please provide URLs for each file, or if the entire repository, the repository’s URL:**

The file at the following location should be taken down: https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/browsers.json

**Is the work licensed under an open source license? If so, which open source license? Are the allegedly infringing files being used under the open source license, or are they in violation of the license?**

Yes, it is licensed under the MIT License. The MIT License is a very simple license that requires the original copyright notice(s) remain present. The MIT License is being violated due to the removal of the project's copyright notice: `Copyright (c) 2019 Oleksii Sribnyi`. In addition, the individual file's copyright notice should be `Copyright (c) 2019 Rodney Teal`. The absence of these notices is a clear violation of the MIT License as quoted below.

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Other information:
The work was contributed under the MIT License in accordance to the `inbound = outbound` clause of 
Github's Terms of Service. The work was contributed in the form of a PR that I authored and sent to 
https://github.com/codemanki/cloudscraper. The LICENSE is here: 
https://github.com/codemanki/cloudscraper/blob/master/LICENSE
I have not signed a CLA or waived my copyright in any way thus I am still the copyright owner.

**What would be the best solution for the alleged infringement? Are there specific changes the other person can make other than removal? Can the repository be made private?**

Add the proper copyright notices and stop the plagiarism. This is an issue for which I have sent many DMCA notices. I'd prefer to have the repository removed and the user blocked from Github services. I have contacted legal counsel to aid in sending additional DMCA notices.

**Do you have the alleged infringer’s contact information? If so, please provide it:**
[private]

I have a good faith belief that use of the copyrighted materials described above on the infringing web pages is not authorized by the copyright owner, or its agent, or the law. I have taken fair use into consideration.

I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.

I have read our Guide to Submitting a DMCA Takedown Notice: https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/

I hereby demand that the infringed content be removed. I urge you to act expeditiously.

[private]

**Please type your full legal name below to sign this request:**
[private]

**Comment by VeNoMouS** [comment]
That is pro-src being extremely petty after i banned him from this repo and my discord for being abusive to myself and others of the community, its his second attempt at filing a DMCA against this project.

I should just report him for abuse.

He clearly doesn't know how the DMCA works...

I personally think he could benefit from counseling as I suspect he's bi-polar, he doesn't have a job and spends way too much of his life fixated on other peoples projects, and gets abusive when people won't do exactly as he demands then has tantrums,  if he focused on things in his own life that should matter to him I believe he would be find a sense of belonging, instead of the man child we see currently.

Just my 2 cents,

Anyway I have nothing more to say on the subject.

**Comment by VeNoMouS** [comment]
Also funny that you specifically created your account only 30 minutes ago.... just to post that...

**Comment by Piedrosys** [comment]
Not personal. You say he do stuff but he create the project? You copy or no?
Clone not work and license chagne so he right or no?
He say theft there https://github.com/pypa/warehouse/issues/5901
And why change even he not code creator?

**Comment by VeNoMouS** [comment]
@Piedrosys no... if your referring to the pypi name space....

![image](https://user-images.githubusercontent.com/597545/58440849-430fcb80-8131-11e9-8058-0cdbc86bc865.png)

![image](https://user-images.githubusercontent.com/597545/58440863-620e5d80-8131-11e9-972f-4b6d0c3420fc.png)


if your refering to the actual code... look at the commit history of this project...  most of this code came from my archived project https://github.com/VeNoMouS/cloudflare-scrape-js2py


pro-src is delusional if he thinks he wrote this project. you can see the commits from both projects.

**Comment by Piedrosys** [comment]
ok he did create but delete why? Look like he gave you like said
commit keep changing. What is problem?

**Comment by Piedrosys** [comment]
Code came from cloudflare-scrape or no?

**Comment by VeNoMouS** [comment]
@Piedrosys he created the initial name space on pypi that is all , he gave it to me, none of the code that was on their was used, all the code in this project is originated from https://github.com/VeNoMouS/cloudflare-scrape-js2py

**Comment by Piedrosys** [comment]
ok thank you but still confused not make sense

**Comment by VeNoMouS** [comment]
not sure what you are confused about?

**Comment by Piedrosys** [comment]
Sorry no mean make mad sorry I leave now

**Comment by VeNoMouS** [comment]
You're not making me angry, just wondering why you are confused?

**Comment by Piedrosys** [comment]
You say he not author I see different commit changing. it okay I like the project

**Comment by Piedrosys** [comment]
Sorry no good english

**Comment by VeNoMouS** [comment]
`You say he not author I see different commit changing. it okay I like the project`

He is not the author, When I initially started this project there was alot of dirty commits etc... he did a couple PR's... before i made a production release i did a fresh repo and force pushed... 

I have since fixed this by rebasing the his PR's back in and acknowledged what little code he did contribute.

**Comment by VeNoMouS** [comment]
Also history logs from pypi showing pro-src making me the owner and taking himself off owner..

![image](https://user-images.githubusercontent.com/597545/58441213-3f317880-8134-11e9-8ea0-6d7d43339504.png)

**Comment by VeNoMouS** [comment]
@WebSpider, @pannal, @miigotu.... figured since you were so interested about this i would include you.

**Comment by Piedrosys** [comment]
ok understand a little and I read https://github.com/VeNoMouS/cloudscraper/issues/23
So you try to fix mistakes but whyy he get mad? it ok you tell more
No use code on discord or he lie? Why no fix sooner I make new clone
what he say abusive?

**Comment by VeNoMouS** [comment]
@Piedrosys no ... while code ideas were discussed, none of his code was "stolen" i'm sure @Krylanc3lo can also vouch since he was sitting in the discord...

He's mad because the guy is bi-polar asf..

https://github.com/PiotrDabkowski/Js2Py/issues/167
https://github.com/PiotrDabkowski/Js2Py/issues/168

He abuses people, then changes the story afterwards... i feel sorry for @PiotrDabkowski as I have pro-src do the same bullshit

**Comment by VeNoMouS** [comment]
![image](https://user-images.githubusercontent.com/597545/58441408-009cbd80-8136-11e9-8270-d1a40be45720.png)

**Comment by VeNoMouS** [comment]
Look I can go on and on, and paste further but at the end... i'm not wanting to play his stupid games, So I'm going to refrain from continuing this conversation, frankly it's pointless

**Comment by Piedrosys** [comment]
oooo rude to https://github.com/PiotrDabkowski/Js2Py/issues/168
block him for this or no? I see he call you a name when argue
hmm... He get mad but some not make sense no whole story here
thank you anwer me and for info. I keep use my code and no problem legal?

**Comment by VeNoMouS** [comment]
@Piedrosys his DMCA's are __not valid__ and he's simply lashing out, there are no legal problems.

**Comment by Piedrosys** [comment]
the pro guy look like work a lot this at Mar 28 https://github.com/codemanki/cloudscraper/issues/80#issuecomment-477672175
not sure what happens but this not look good at all
Sorry I use nodejs so no legal problem there
hope it ok here and no problem with law

**Comment by VeNoMouS** [comment]
@Piedrosys you know https://github.com/codemanki/cloudscraper/ is javascript for node right? this is all a python project...

**Comment by Piedrosys** [comment]
oh I not know. thanks

**Comment by VeNoMouS** [comment]
@Piedrosys while i appreciate your interest in this matter, however... I'm refuse to get sucked back into pro-src's drama, so unless you have something constructive further too add to this thread, I am going to refrain from contributing anything more on this thread, its already taken up more time than i want to give to it.

thanks :)

**Comment by Piedrosys** [comment]
I need ask browser.json. Who create it? pro guy lies again?
Me friend say you and commit is you and other commit say him
I no think pro guy lie. Why say mean thing here? No good :

**Comment by Piedrosys** [comment]
you delete all issue I open and you mad?
You say new brower.json but not.
It is same but repeat file.
I say no more if you delete
