### ISSUE TITLE
brotli.error: BrotliDecompress failed

### ISSUE THREAD

**Issue by kxltsuper** [VeNoMouS/cloudscraper#47]
cloudscraper 1.1.16

website:  https://bwh88.net/

scraper = cloudscraper.create_scraper()
req=scraper.get("https://bwh88.net/")
--------------------------
Traceback (most recent call last):
  File "C:/Users/jsd/PycharmProjects/Uovz_qiangou/bwg_qianggou.py", line 268, in <module>
    main()
  File "C:/Users/jsd/PycharmProjects/Uovz_qiangou/bwg_qianggou.py", line 72, in main
    req=scraper.get("http://bwh88.net/")
  File "C:\Python27\lib\site-packages\requests-2.22.0-py2.7.egg\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\cloudscraper\__init__.py", line 139, in request
    resp._content = brotli.decompress(resp.content)
brotli.error: BrotliDecompress failed

**Comment by VeNoMouS** [comment]
Could be a bad brotli response .. in the mean time try set allow_brotli=False in your scraper

```
cloudscraper.create_scraper(allow_brotli=False)
```

Thanks though @kxltsuper i'll look into this, the above should help you however

**Comment by kxltsuper** [comment]
thank you.
`    scraper = cloudscraper.create_scraper(allow_brotli=False)
    req=scraper.get("https://bwh88.net/",headers=header,verify=False)
    print req.content`
but still can't get the right content which i want.

because i can't get the "u_token":
u_token=re.search('<input type="hidden" name="token" value="(.*?)" />',req.content).group(1)

can you help me to test it?

**Comment by VeNoMouS** [comment]
I would not recommend setting headers UNLESS you have to, Cloudflare's bot inspects the header order of known browsers etc... cloudscraper sets up random User-Agents from a massive list https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/browsers.json?raw=true , if you __really__ need to pass headers... Make sure you use OrderedDict from collections and you set them up in the exact order they are expect by cloudflare..

also if you just want the token, you can simply use the `get_tokens` function https://github.com/VeNoMouS/cloudscraper#retrieving-a-cookie-dict-through-a-proxy

ie

```
>>> import cloudscraper
>>> tokens, user_agent = cloudscraper.get_tokens("https://bwh88.net/", allow_brotli=False, verify=False)
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
>>> tokens
{'cf_clearance': '', '__cfduid': 'da09e74a2666263e0f58d1e0f145c48111559698005'}
>>> user_agent
u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.33 Safari/537.36'
>>>
```

**Comment by kxltsuper** [comment]
thank you very much. i solve it.

**Comment by VeNoMouS** [comment]
thanks @kxltsuper , that helped  me track down the issue, urllib3 1.25.1 added in brotli decompression support

if you are running 2.22.0 you are more than most likely running new urllib3

```python
import requests
requests.packages.urllib3.__version__
```

Anyway I am adding in a fix for it now
