### ISSUE TITLE
SOCKS5 proxy: Always getting root URL instead of requested URL

### ISSUE THREAD

**Issue by verybadsoldier** [VeNoMouS/cloudscraper#50]
I am trying to use a SOCKS5 proxy. It basically works but it seems I am always getting the root website instead of the URL I requested.

So when requesting `https://example.com/page1` I am getting a response as if I had requested `https://example.com`.

Code to reproduce:
```
scraper = cloudscraper.create_scraper(debug=True)
r = scraper.get('https://www.japscan.to/manga/tales-of-demons-and-gods/')
```

This delivers correctly that:
```
<!DOCTYPE html>\n<html lang="fr">\n\n\t<head>\n\t\t<title>Manhua Tales Of Demons And Gods | JapScan</title>\n\t\t<meta charset="utf-8" />\n\t\t<meta name="referrer" content="no-referrer" />\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1" />\n\n\t\t<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">\n\t\t<link rel="stylesheet" href="/css/main.css" />\n\t\t<link rel="stylesheet" href="/css/mobile.css" />\n\n\t\t<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css" integrity="sha384-v2Tw72dyUXeU3y4aM2Y0tBJQkGfplr39mxZqlTBDUZAb9BGoC40+rdFCG0m10lXk" crossorigin="anonymous">\n\t\t<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/fontawesome.css" 
...
```

But when I add a proxy:
```
scraper = cloudscraper.create_scraper(debug=True)
scraper.proxies = {'https': 'socks5://103.216.82.28:6667'}
r = scraper.get('https://www.japscan.to/manga/tales-of-demons-and-gods/')
```

Then I get this:
```
<!DOCTYPE html>\n<html lang="fr">\n\t<head>\n\t\t<title>Lecture en ligne des meilleurs mangas japonais en ligne | Japscan</title>\n\t\t<meta charset="utf-8" />\n\t\t<meta name="referrer" content="no-referrer" />\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1" />\n\t\t\n\t\t<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css" integrity="sha384-v2Tw72dyUXeU3y4aM2Y0tBJQkGfplr39mxZqlTBDUZAb9BGoC40+rdFCG0m10lXk" crossorigin="anonymous">\n\t\t<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/fontawesome.css" 
...
```

Which is not the requested URL but rather the root website `https://www.japscan.to`.

Am doing something wrong or is this some sort of bug? Thanks for help.

**Comment by verybadsoldier** [comment]
This is my pip:
```
alabaster==0.7.12
appdirs==1.4.3
asn1crypto==0.24.0
attrdict==2.0.1
attrs==19.1.0
Babel==2.6.0
backtrader==1.9.73.123
backtrader-plotting==0.5.3
bencoder.pyx==1.2.1
bitstring==3.1.5
bokeh==0.13.0
brotli==1.0.7
cached-property==1.5.1
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
cloudpickle==1.0.0
cloudscraper==1.1.17
colorama==0.4.1
conda==4.6.14
cryptography==2.6.1
cycler==0.10.0
defusedxml==0.6.0
docopt==0.6.2
docutils==0.14
fritzconnection==0.6.5
future==0.17.1
html5lib==1.0.1
idna==2.6
imagesize==1.1.0
isodate==0.6.0
Jinja2==2.10.1
Js2Py==0.63
jsonpickle==0.9.6
kiwisolver==1.1.0
lxml==4.2.5
MarkupSafe==1.1.1
matplotlib==3.1.0rc2
menuinst==1.4.14
mkl-fft==1.0.12
mkl-random==1.0.2
munch==2.3.2
myjdapi==1.0.2
NBT==1.5.0
numpy==1.16.3
oauthlib==2.1.0
packaging==19.0
pandas==0.24.2
pillow==6.0.0
py-cpuinfo==5.0.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
Pygments==2.3.0
pyjsparser==2.5.2
pymongo==3.8.0
pymp4parse==0.3.0
pyOpenSSL==18.0.0
pyparsing==2.4.0
PySocks==1.6.8
python-dateutil==2.8.0
pytz==2018.7
pywin32==223
PyYAML==5.1
qbtrunner==0.3.5
regex==2018.8.29
requests==2.22.0
requests-toolbelt==0.9.1
ruamel-yaml==0.15.37
sacred==0.7.4
six==1.11.0
snowballstemmer==1.2.1
sphinxcontrib-websupport==1.1.0
str2bool==1.1
torf==1.5
tornado==6.0.2
tqdm==4.31.1
tzlocal==2.0.0b1
urllib3==1.22
webencodings==0.5.1
websocket-client==0.56.0
win-inet-pton==1.0.1
wincertstore==0.2
wrapt==1.11.1
youtube-dl==2019.3.1
zeep==3.3.1
```

**Comment by VeNoMouS** [comment]
@verybadsoldier i'll investigate this for you later today, thanks for raising the issue.

**Comment by VeNoMouS** [comment]
@verybadsoldier can you email your full debugs please, as im having problems replicating your probem...

**Comment by verybadsoldier** [comment]
@VeNoMouS 
Interesting. Yes, seems to be working for you.

This is my log without proxy:
https://pastebin.com/fTe6tJ9J

And this is with proxy:
https://pastebin.com/mQGPmRPd

**Comment by VeNoMouS** [comment]
Yea so on the 302..

```
 CONNECT https://www.japscan.to/cdn-cgi/l/chk_jschl?s=24380fd58ef9e750137b903c3db34649879f6ba7-1560232791-1800-AR6%2FTlJiTURq%2F6K3zw9k9q3EunU7Gf89f2AaWFsot3LRYj5h2kuRp9SIBW3ICgrrIWo7CTe19I%2FlnobV4unELam%2Btk4lbWv7ttYH8OlN0gcs%2BKwJfRqMYeCI3JXeZyPpQyWo0tYBlJ04RPhh7YLg5KXNXrP2hUccCGQ9IDL%2BdI%2By&jschl_vc=9dea4f398effa765bc932e736ef5989c&pass=1560232795.792-RFf4%2B3Ta2v&jschl_answer=-8.9616786750 HTTP/1.1
< Host: www.japscan.to
< User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate, br
< Connection: keep-alive
< Upgrade-Insecure-Requests: 1
< Cookie: __cfduid=d208469907b7d5fd56ae8ddd54475cd671560232791
<
 
> HTTP/1.1 302 Moved Temporarily
> Date: Tue, 11 Jun 2019 05:59:59 GMT
> Content-Type: text/html
> Content-Length: 159
> Connection: keep-alive
> Location: /
> Server: cloudflare
> CF-RAY: 4e515cb2bb5ac761-AMS
> X-Frame-Options: SAMEORIGIN
>
```

it's changing the Location on you to /

**Comment by VeNoMouS** [comment]
I'll see if i replicate what is going on and try to work out why its redirecting you away...

**Comment by verybadsoldier** [comment]
Sorry, I just noticed that you wanted the logs to be emailed. I hope the pastebin way was ok also.

**Comment by VeNoMouS** [comment]
Yea paste is fine, most people seem to want to keep their requests private (not sure why) so its just easier to say hey email... otherwise you never get them

**Comment by VeNoMouS** [comment]
@verybadsoldier can you show me a couple raw debugs with fresh create_scraper()'s

**Comment by verybadsoldier** [comment]
You mean running this demo program a couple of times?
```
scraper = cloudscraper.create_scraper(debug=True)
scraper.proxies = {'https': 'socks5://103.216.82.28:6667'}
r = scraper.get('https://www.japscan.to/manga/tales-of-demons-and-gods/')
```

**Comment by VeNoMouS** [comment]
yea , i just wanna see if its mozilla user-agent causing it, or if its a random thing going on.

**Comment by verybadsoldier** [comment]
Just to make sure that I don't misunderstand you:
I should run the exact same code that I ran before to provide my latest log, yes?
If yes then, tbh, I do not expect a different outcome and would not expect a change in the user-agent header. But sure, I am not the expert and I will provider whatever is helpful to you.

Sorry if I got something wrong.

**Comment by VeNoMouS** [comment]
@verybadsoldier what I think is happening ... and tbh its not my code this is cloudflare, is due to you failing the first challenge response... the second challenge takes the failed solve as the the base url , technically you shouldnt fail the first not sure why you did... have you tried a different interpreter instead of __js2py__?

Anyway... I guess a resolve could be.. in place of https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L235

```python
        redirect_location = urlparse(resp.url)
        if not redirect_location.netloc:
            redirect_url = urlunparse(
                (
                    parsed_url.scheme,
                    domain,
                    redirect_location.path,
                    redirect_location.params,
                    redirect_location.query,
                    redirect_location.fragment
                )
            )
            return self.request(resp.request.method, redirect_url, **original_kwargs)

        return self.request(resp.request.method, resp.url, **original_kwargs)
```

And use the force the code back onto the original requests URL before the challenge was issued, while not ideal.. I can understand what has happened

**Comment by VeNoMouS** [comment]
@verybadsoldier how'd you go?

**Comment by verybadsoldier** [comment]
> **Anyway**... I guess a resolve/workaround could be.. in place of https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L235-L249
> 
> ```python
>         redirect_location = urlparse(resp.url)
>         if not redirect_location.netloc:
>             redirect_url = urlunparse(
>                 (
>                     parsed_url.scheme,
>                     domain,
>                     redirect_location.path,
>                     redirect_location.params,
>                     redirect_location.query,
>                     redirect_location.fragment
>                 )
>             )
>             return self.request(resp.request.method, redirect_url, **original_kwargs)
> 
>         return self.request(resp.request.method, resp.url, **original_kwargs)
> ```
> 
> And force the code back onto the original requested URL before the challenge was issued and not use CF's 302 redirect Location header, while not ideal.. I can understand what has happened.

Yay, I changed the code and this is working nicely, thanks!!

> Technically you shouldn't fail in a normal browser... have you tried a different interpreter instead of **js2py**? more information regarding different supported javascript interpreters can be found at https://github.com/venomous/cloudscraper/#javascript-interpreters

No, I did not try yet. But looks interesting.

So, is this a code change you would consider to keep that way or was it more like a workaround? I would be happy to test further stuff when you need something (e.g. the javascript interpreter?).

Thanks!

**Comment by VeNoMouS** [comment]
I'll get my test group to test it more as, as i said i dont think theres any real side affects but we are basicly ignoring the 302 ... so ..... yeaaaaa
