### ISSUE TITLE
ReCaptcha problem

### ISSUE THREAD

**Issue by verybadsoldier** [VeNoMouS/cloudscraper#51]
Since today I get a ReCaptcha error. This does not appear when I open the URL in Chrome Browser. I know I can configure 3rd party recaptcha solvers but they seem to need registration. Also as I understand the documentation, captchas should not appear in normal use.

Test program:
```
    scraper = cloudscraper.create_scraper(debug=True)
    r = scraper.get('https://www.japscan.to/manga/tales-of-demons-and-gods/')
```

Gives me this:
https://pastebin.com/E9kYuqKm

My python packages:
```
alabaster==0.7.12
appdirs==1.4.3
asn1crypto==0.24.0
attrdict==2.0.1
attrs==19.1.0
Babel==2.6.0
backtrader==1.9.73.123
backtrader-plotting==0.5.3
bencoder.pyx==1.2.1
bitstring==3.1.5
bokeh==0.13.0
brotli==1.0.7
cached-property==1.5.1
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
cloudpickle==1.0.0
cloudscraper==1.1.17
colorama==0.4.1
conda==4.6.14
cryptography==2.6.1
cycler==0.10.0
defusedxml==0.6.0
docopt==0.6.2
docutils==0.14
fritzconnection==0.6.5
future==0.17.1
html5lib==1.0.1
idna==2.6
imagesize==1.1.0
isodate==0.6.0
Jinja2==2.10.1
Js2Py==0.63
jsonpickle==0.9.6
kiwisolver==1.1.0
lxml==4.2.5
MarkupSafe==1.1.1
matplotlib==3.1.0rc2
menuinst==1.4.14
mkl-fft==1.0.12
mkl-random==1.0.2
munch==2.3.2
myjdapi==1.0.2
NBT==1.5.0
numpy==1.16.3
oauthlib==2.1.0
packaging==19.0
pandas==0.24.2
pillow==6.0.0
py-cpuinfo==5.0.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
Pygments==2.3.0
pyjsparser==2.5.2
pymongo==3.8.0
pymp4parse==0.3.0
pyOpenSSL==18.0.0
pyparsing==2.4.0
PySocks==1.6.8
python-dateutil==2.8.0
pytz==2018.7
pywin32==223
PyYAML==5.1
qbtrunner==0.3.5
regex==2018.8.29
requests==2.22.0
requests-toolbelt==0.9.1
ruamel-yaml==0.15.37
sacred==0.7.4
six==1.11.0
snowballstemmer==1.2.1
sphinxcontrib-websupport==1.1.0
str2bool==1.1
torf==1.5
tornado==6.0.2
tqdm==4.31.1
tzlocal==2.0.0b1
urllib3==1.22
webencodings==0.5.1
websocket-client==0.56.0
win-inet-pton==1.0.1
wincertstore==0.2
wrapt==1.11.1
youtube-dl==2019.3.1
zeep==3.3.1
```

Thanks alot!

**Comment by Krylanc3lo** [comment]
Same issue on my side. 
As usual, I can help with the tests ^^

**Comment by VeNoMouS** [comment]
Sorry Only saw this been away... interesting... I'll look into this shortly i too am hit with reCaptcha.

**Comment by VeNoMouS** [comment]
OK so initial checks are showing that it is NOT the challenge solve...

![image](https://user-images.githubusercontent.com/597545/59485734-067ef680-8ecb-11e9-91b9-1ba80c2a27f8.png)

^^ my browser solving... 

![image](https://user-images.githubusercontent.com/597545/59485748-1a2a5d00-8ecb-11e9-8ecc-3eef3206fc7e.png)


^^ cloudscraper solving the same challenge request.... 

Next is to look at User-Agents... then SSL..

**Comment by VeNoMouS** [comment]
Ok... i skipped user-agents... and stripped it back to just 1 known good cipher.. which is working... now to workout which is the bad cipher ...

**Comment by VeNoMouS** [comment]
Problem cipher is __ECDHE-RSA-AES256-GCM-SHA384__ , I will push a fix shortly.

**Comment by VeNoMouS** [comment]
1.118 (bab6c267b16435dffd126fa690c1e606bdc41d8d) in dev branch for you guys to test @Krylanc3lo , @verybadsoldier

**Comment by VeNoMouS** [comment]
Ok ... i've released __1.1.18__

**Comment by Krylanc3lo** [comment]
Thanks a lot! it is working perfectly on my end now ^^

**Comment by devgianlu** [comment]
Did they break their own protection? I'm getting this on the console when visiting http://x1337x.se/:
```
(index):51 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

    at Function (<anonymous>)
    at (index):51
    at (index):51
```

**Comment by verybadsoldier** [comment]
Working for me too here! Thanks alot!

**Comment by VeNoMouS** [comment]
> Did they break their own protection? I'm getting this on the console when visiting http://x1337x.se/:
> 
> ```
> (index):51 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".
> 
>     at Function (<anonymous>)
>     at (index):51
>     at (index):51
> ```

most likely due to here

```
if (self === top) {
--
  | var antiClickjack = document.getElementById("antiClickjack");
  | antiClickjack.parentNode.removeChild(antiClickjack);
  | } else {
  | top.location = self.location;
  | }
```
