### ISSUE TITLE
Status code = 403

### ISSUE THREAD

**Issue by EVILPINGUU** [VeNoMouS/cloudscraper#53]
Hello im getting error 403 on this website, nakedcph.com. I set all cookies and headers correctly, but im still getting 403 error. Cloudscraper version = 1.19.
Thanks for help.

**Comment by VeNoMouS** [comment]
Sorry about the delay, i only just saw the tickets... CF is marking __ECDHE-RSA-AES128-GCM-SHA256__ as bad cipher will push fix for you now.

**Comment by VeNoMouS** [comment]
@EVILPINGUU version 1.1.20 has been released (cdb767cf87f7091100627e9f9157) on github and pip, and should resolve this issue for you, least it does for me, if this is still an issue please open the ticket again.

- VeN
