### ISSUE TITLE
reCaptcha: cat and mouse game

### ISSUE THREAD

**Issue by HawkLiking** [VeNoMouS/cloudscraper#54]
Hi @VeNoMouS :)

Since today, 16:30 PM (UTC), I have the error : 
`Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.`

For example in https://pro-src.com/ and http://japscan.to/

Cat and mouse game, I guess :P 

Thank you !

**Comment by VeNoMouS** [comment]
LOL, glad you saw that cat & mouse reference on 1.1.19 ;P

**Comment by VeNoMouS** [comment]
Sorry about the delay, i only just saw the tickets... CF is marking ECDHE-RSA-AES128-GCM-SHA256 as bad cipher will push fix for you now.

**Comment by VeNoMouS** [comment]
Refer #53

**Comment by HawkLiking** [comment]
Thank you :)
