### ISSUE TITLE
captcha triggered by bad ciphers

### ISSUE THREAD

**Issue by johnnyollo** [VeNoMouS/cloudscraper#57]
i always trigger captcha on https://www.sneakersnstuff.com/ and a couple of other sites even i solve them with 2captcha

**Comment by VeNoMouS** [comment]
CF triggering reCaptcha on cipher `ECDHE-RSA-AES128-SHA256` , pushing update now.

**Comment by VeNoMouS** [comment]
1.1.25 Released...

Seems every 6-8 days CF randomly mark / target ciphers even though they are valid ciphers...

**Comment by VeNoMouS** [comment]
And re 2captcha... yea when there's a cipher they mark / target... solving reCaptcha won't matter, as it will just constantly trigger the reCaptcha, I need to work out a way when this is occuring.

**Comment by johnnyollo** [comment]
Thank you, I'll let you know if some other cipher will trigger captchas.
If i have to fix it quickly can I just remove the marked cipher right?

**Comment by 102flex** [comment]
@johnnyollo hey, I have the same problem. How did you fixed it? I just have the problem on sneakersnstuff.

``import cloudscraper

scraper = cloudscraper.create_scraper()
response = scraper.get("https://www.sneakersnstuff.com/de/")
print(response.status_code)``

Output:
``403``

**Comment by VeNoMouS** [comment]
sneakersnstuff implemented a reCaptcha on their frontpage , outside of cloudflare, solve the challenge.

![image](https://user-images.githubusercontent.com/597545/60688262-33da2580-9f08-11e9-9fc0-0fa14c39e9fd.png)

The reason this library didn't do it for you as well.. is because the src URL is different 

```HTML
script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="4f1439b9584ba433" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
```

What you need to do is still use the library to bypass cloudflare, but then solve the challenge..

and submit it to the form

 ```HTML
<form class="challenge-form" id="challenge-form" action="/cdn-cgi/l/chk_captcha" method="get">
```

I can post a simple solution if you need to....

**Comment by VeNoMouS** [comment]
HRRM.... actually... 

I could adapt my code to perhaps help out with this... 

Rather than statically send to 

```python
submit_url = '{}://{}/cdn-cgi/l/chk_captcha'.format(parsed_url.scheme, domain)
```

I could read the src URL from what ever has sitekey....

Let me do some testing boys...

**Comment by VeNoMouS** [comment]
Wait...  what am i Saying.. that should solve it as is... (sorry guys ive only just woken up , like seriously just rolled outta bed) ;P

**Comment by VeNoMouS** [comment]
Ok... @102flex found the issue, version 1.1.26 is currently on __dev__ branch , if you have 3rd party reCaptcha solver loaded now (https://github.com/VeNoMouS/cloudscraper#3rd-party-recaptcha-solvers)... it will solve it for you.

**Comment by 102flex** [comment]
2captcha support would be very cool!

You have any link to tip you an coffee? 
Thank you

**Comment by VeNoMouS** [comment]
<a href="https://buymeacoff.ee/venomous" target="_blank"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" alt="Buy Me A Coffee" style="height: 41px !important;width: 174px !important;box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;-webkit-box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;" ></a>

**Comment by johnnyollo** [comment]
Yeah many sites host the cf recaptcha challenge on their sites,
I already use 2captcha with no problem, but I think someone else would appreciate it.
Enjoy your coffee.

**Comment by VeNoMouS** [comment]
feel the love boys :)

**Comment by VeNoMouS** [comment]
3rd party reCaptcha __2captcha__ support added in __Release 1.1.27__

**Comment by johnnyollo** [comment]
captcha is triggered by bad ciphers again
