### ISSUE TITLE
Give users the ability to read requests content when reCaptcha detected with out 3rd party solver loaded.

### ISSUE THREAD

**Issue by johnnyollo** [VeNoMouS/cloudscraper#59]
I need the recaptcha html page, can you remove the "RuntimeError: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter." ?

**Comment by VeNoMouS** [comment]
rgr i'll see what i can do for you

**Comment by VeNoMouS** [comment]
__Release 1.1.29__ should sort you out refer to https://github.com/VeNoMouS/cloudscraper#return_response
