### ISSUE TITLE
Exciting new project!

### ISSUE THREAD

**Issue by pannal** [VeNoMouS/cloudscraper#6]
Hey,

Can you explain the differences of this project compared to [the old one](https://github.com/VeNoMouS/cloudflare-scrape-js2py) apart from being not necessarily dependant on js2py?

Thank you

**Comment by VeNoMouS** [comment]
* Multiple Interpreter Support (With more to possibly come... have written it in such a way its plug and play.)
** js2py 
** nodejs 


* Adding in Anticapcha support
* Core of the framework rewritten
* Better User-Agent support for CF headers
* Optimization
* Bunch of other stuff we felt was missing...

Project is still on going.

**Comment by pro-src** [comment]
The code used to solve challenges is more robust too so there should be less breakage when CF updates by doing away with the fragile regular expressions found in similar projects. The new UA support addresses issues that people may encounter with CF's improved BIC which mostly has to do with headers. So many improvements over the other code bases out there.

**Comment by pannal** [comment]
> Better User-Agent support for CF headers
Is this planned or already implemented? I've been using the old project for a while now (and am very familiar with the source), and I can't find major differences yet.

**Comment by pro-src** [comment]
Planned. @VeNoMouS is working on it, not committed yet

**Comment by VeNoMouS** [comment]
I'm currently drinking coffee and writing it as we speak.

**Comment by pannal** [comment]
Ah, great.

FYI: I've implemented a work in progress anticaptcha integration layer (currently supports AntiCaptcha and DeathByCaptcha) into Sub-Zero: https://github.com/pannal/Sub-Zero.bundle/blob/master/Contents/Libraries/Shared/subliminal_patch/pitcher.py

**Comment by VeNoMouS** [comment]
Nice, 

Yea the anticaptcha stuff will be plug and play like the js interpreters.. so you can simply just drop in another one on a PR etc... avoiding changes to the core.

**Comment by pro-src** [comment]
If you're looking for insight into the headers, you can see the work that I've done on cloudscraper[*.js*](): https://github.com/pro-src/cloudscraper.js/tree/4.0.0

**Comment by pannal** [comment]
Oh, you're dropping "br"! I've been playing around with the CF headers recently and found that "br" breaks the CF validation reproducably. Do you have any idea why that is?

When I "solve" a CF check with my real browser, which includes "br" in Accept-Encoding, it works flawlessly.

**Comment by pro-src** [comment]
@pannal Completely different project that drop the PR from the default headers when there is no support for Brotli available but has complete support for it (native or user supplied). Let's not get off topic though :wink:

**Comment by VeNoMouS** [comment]
brotli is easy to understand and implement ;P

**Comment by pannal** [comment]
@pro-src yeah I get that. I was just wondering why once I "add" brotli support to Accept-Encoding for the CF headers, CF breaking instantly fails.

**Comment by pro-src** [comment]
I haven't noticed that being the case for ***all*** domains and I wouldn't under estimate what the site owner can do with CF's extensive API.

**Comment by pannal** [comment]
OK, I've only tested it with subscene.com. But one I add "br" to
```
self.headers = OrderedDict([
            ('User-Agent', default_user_agent()),
            ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'),
            ('Accept-Language', 'en-US,en;q=0.5'),
            ('Accept-Encoding', 'gzip, deflate'),
            ('Connection', 'keep-alive'),
            ('Pragma', 'no-cache'),
            ('Cache-Control', 'no-cache'),
            ('Upgrade-Insecure-Requests', '1'),
            ('DNT', '1'),
        ])
```'s Accept-Encoding, CF scraping fails.

Back to topic, though, sorry.

**Comment by VeNoMouS** [comment]
because you have to uncompress the content ...

**Comment by pannal** [comment]
> because you have to uncompress the content ...

Makes sense. Now I'm feeling stupid.

**Comment by pro-src** [comment]
@VeNoMouS said and I think I misunderstood you, for some reason I thought you were saying it only worked when adding the `br`.

**Comment by pannal** [comment]
Btw, to stay off-topic: Is the order of the headers important for CF in any way, or is it just advisable to *keep* the order of the headers consistent?

**Comment by VeNoMouS** [comment]
no its __REQUIRED__ for the correct order, CF will hit you with failed challenge responses or captcha's...

**Comment by pro-src** [comment]
The order is important on a per UA basis, meaning the headers that are expected for one UA will not necessarily be the same for a similar (Changed OS, same browser vesion). The BIC is getting smarter.

**Comment by VeNoMouS** [comment]
We have spent many hours investigating and mapping this stuff out ;P

**Comment by pannal** [comment]
Oh wow. That's a hell of an assumption from CF's side, as HTTP headers aren't really required to be ordered in any way afaik.

Good to know.

**Comment by VeNoMouS** [comment]
They have the meta data to analyze past metrics... remember all requests are just being proxies through CF...

**Comment by pannal** [comment]
So the user agents from `DEFAULT_USER_AGENTS` are matched to work with the order of the headers you impose in `request`?

**Comment by pro-src** [comment]
Everything is currently under development and that is not how it's going to work when released. There will not be any header imposing. If you override the headers (probably shouldn't), your mileage may vary.

**Comment by pannal** [comment]
OK, I'm just trying to figure out whether to use your (small) default User-Agent list, or my large one. I'm leaning towards yours right now, judging from what you just told me.

**Comment by pro-src** [comment]
That list is a very small subset of the data that we have at our disposal to implement this properly. Just use cloudscraper when @VeNoMouS releases it. Great progress is being made.

**Comment by pannal** [comment]
@pro-src @VeNoMouS thank you for your work on all of this. And for coping with my off-topicness.

**Comment by pannal** [comment]
Is there a Slack or Discord I may join for this project?

**Comment by VeNoMouS** [comment]
@pannal we are now live :) 

Try out thew new project ["cloudscraper"](https://pypi.org/project/cloudscraper/)
