### ISSUE TITLE
Anticap issue

### ISSUE THREAD

**Issue by xzilesnrks** [VeNoMouS/cloudscraper#60]
Hi, i got this error when i tried with anticap: 
 from python_anticaptcha import AnticaptchaClient, NoCaptchaTaskProxylessTask, NoCaptchaTask, Proxy
ImportError: cannot import name 'Proxy'

**Comment by VeNoMouS** [comment]
The author of `python_anticaptcha` has made some changes, I have fixed your issue and am also using his new features, please upgrade cloudscraper to __Release 1.1.30__ to resolve your issue :)
