### ISSUE TITLE
Can't find browsers.json if builded with pyarmor

### ISSUE THREAD

**Issue by simonetoscano** [VeNoMouS/cloudscraper#62]
Hi, I keep getting this error every time I try to execute my exe builded with pyarmor.

> https://github.com/dashingsoft/pyarmor

`[Errno 2] No such file or directory: '/var/folders/81/zgg3srks7_l0ytf4ljkhdkg80000gn/T/_MEIIci0I7/cloudscraper/user_agent/browsers.json'`

**Comment by VeNoMouS** [comment]
Is the json file actually bundled in your container?

**Comment by VeNoMouS** [comment]
Can you please supply your full cmd line your using to obfuscate the package with please.

**Comment by simonetoscano** [comment]
Nope, the json is not in my folder because I didn't think it was necessary. Everything works fine when I try to run the script **without** building it with pyarmor. But as I need to protect my script, I must build it with pyarmor.

Here are the commands I use to obfuscate my script:

`pyarmor obfuscate main.py`
`pyarmor init --src=. --entry=main.py .`
`pyarmor build`
`cd dist`
`pyinstaller main.spec`

**Comment by VeNoMouS** [comment]
You need __browsers.json__ in your package, it needs to be in the same dir as what the __init__.py is from the __user-agent__ directory https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/__init__.py#L25

**Comment by VeNoMouS** [comment]
I am closing this and marking it as invalid as it not an issue of the code.

**Comment by simonetoscano** [comment]
I believe I expressed myself wrongly: of course I have **browser.json** in the same dir as what the `__init__.py` is (that's because I've installed your library through `pip install cloudscraper`) so everything works fine while I compile my script **without** pyarmor

But as I said, the **error occurs only** when I try to execute the exe builded with pyarmor.

**Comment by VeNoMouS** [comment]
Did you check exe build that the json is packaged with it? I don't understand how you think its my code that's the issue, https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/__init__.py#L25 clearly opens the __browser.json__ as the same dir that the original code is designed to do, your re-packaging it and its failing because your not including the file... how is that the codes fault?

**Comment by 102flex** [comment]
Dont open issues like that. This is clearly not the problem off the code.

**Comment by VeNoMouS** [comment]
FWIW if your using pyexe, it does now play well with `os.path.dirname(__file__)` ...

you could try do

```python

import inspect
import os
path = os.path.dirname(os.path.abspath(inspect.getframeinfo(inspect.currentframe()).filename))

user_agents = json.load(
    open(os.path.join(path, 'browsers.json'), 'r'),
    object_pairs_hook=OrderedDict
)
```

**Comment by simonetoscano** [comment]
@VeNoMouS thanks! appreciate it man, that's initially what I needed. but I'm still receiving an error:

> ERROR:root:Unable to load js2py interpreter
An exception occured: 'ModuleNotFoundError' object has no attribute 'message'

**Comment by VeNoMouS** [comment]
most like you'll need to find a work around for https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/interpreters/__init__.py#L29 ... good luck with that.

I have __no plains at this time__ to adapt my code to work with py2exe, it was never designed to be run with it.

**Comment by simonetoscano** [comment]
Thanks for your infos and sorry for wasting your time, have a nice day!

**Comment by VeNoMouS** [comment]
A question isn't a waste of time, what your doing is just out of scope of what the project was originally designed to be run under.

**Comment by VeNoMouS** [comment]
When I'm not so busy I might circle back around and look at it for you

**Comment by simonetoscano** [comment]
I'll be grateful!
