### ISSUE TITLE
_openssl.abi3.so: undefined symbol: OBJ_cleanup

### ISSUE THREAD

**Issue by karma007** [VeNoMouS/cloudscraper#64]
Hello, I have install cloudscraper (virtualenv with python 3.7.4) and I have this error : 
```
pi@karmapi ~/flexget $ bin/python cf.py
Traceback (most recent call last):
  File "cf.py", line 1, in <module>
    import cloudscraper
  File "/home/pi/flexget/lib/python3.7/site-packages/cloudscraper/__init__.py", line 3, in <module>
    import OpenSSL
  File "/home/pi/flexget/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/pi/flexget/lib/python3.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/home/pi/flexget/lib/python3.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/pi/flexget/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/pi/flexget/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: OBJ_cleanup
```
thanks

**Comment by VeNoMouS** [comment]
That is not a cloudscraper issue that appears to be a cryptography package issue... 

```
ImportError: /home/pi/flexget/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: OBJ_cleanup
```

have yout ried reinstalling and/or upgrading cryptography? 
`pip3 install -U cryptography`

**Comment by karma007** [comment]
hello I have uninstalled and reinstalled cryptography -> same error
I have tested import OpenSSL -> same error
any clue to install the good version of OpenSSL ?
thanks

**Comment by VeNoMouS** [comment]
FWIW have you tried `pip3 install -U pyOpenSSL`

**Comment by karma007** [comment]
it was installed. I have reinstalled it. same problem. 
I am using virtualenv  
as I had an SSL error on flexget Intried this to fix it : https://help.dreamhost.com/hc/en-us/articles/115000702772-Installing-a-custom-version-of-Python-3
with a custom install of openssl. I don’t know how to do a clean install now
thanks

**Comment by VeNoMouS** [comment]
Yea sorry, I think you'll have to resolve this yourself as its outside the scope of this project I'm afraid.

**Comment by VeNoMouS** [comment]
You're running linux anyway, so you should have python installed default so don't understand why you using flexiget packaged version...

**Comment by karma007** [comment]
i’ m using raspbian jessie
not so easy to install python 3.x

**Comment by VeNoMouS** [comment]
`apt-get install python3`

**Comment by VeNoMouS** [comment]
Anyway, best of luck mate, but I just don't have the time atm as I'm doing my day job, and as I stated earlier it falls outside the scope of this project

**Comment by karma007** [comment]
thanks a lot

**Comment by schors** [comment]
Sorry. I have a solution of this problem. Actually It's py-cryptography library build stage problem. This error occurs when two conditions are satisfied. First is openssl 1.1.0 and greater in the system so build utils prefers that. Second is header file "openssl/objects.h" from versions less than 1.1.0 so build utils prefers this file. "OBJ_cleanup" was deprecated in  openssl 1.1.0. py-cryptography building process matches "openssl/objects.h" and objects.py (somewhere inside source code tree) to binding's symbols. So ooops... It is required to explicitly set the headers file path. Like this:
CFLAGS="-I/opt/openssl/include" pip3 install -U cryptography
or this
LDFLAGS="-L/opt/openssl/lib -Wl,-rpath,/opt/openssl/lib" CFLAGS="-I/opt/openssl/include" pip3 install -U cryptography
