### ISSUE TITLE
Man or Machine

### ISSUE THREAD

**Issue by lilyoungbug** [VeNoMouS/cloudscraper#66]
Like yesterday it was working like a charm, bypassing Man or Machine page and sending error on Cloudflare captcha. Now both. Please fix!

**Comment by dontshareyourname8** [comment]
For first you should know how bypass cloudflare AntiBot as you're a bot dev, second thing, close your ticket and bring respect to VeNoMouS.

**Comment by lilyoungbug** [comment]
fixed, sorry 😅
