### ISSUE TITLE
Cloudflare reCaptcha detected

### ISSUE THREAD

**Issue by mass828** [VeNoMouS/cloudscraper#67]
It seems something changed, the module isn't working good anymore.

**Comment by VeNoMouS** [comment]
Sorry I'm currently on holiday overseas, however some of the other users of cloudscraper have been in contact with me, and the problem hasnt't really been a cloudflare issue, from what people have been complaining its mostly sneaker related sites .. owned by some company in particular ... anyway I had a dev version i had sitting around for ~2 weeks that fixes the issue... have pushed this version...

I hope this resolves your issue

**Comment by mass828** [comment]
Yeah it works like a charm, many thanks! Enjoy your holidays. :)

**Comment by VeNoMouS** [comment]
cheers, cause the latency is an epic bitch to my boxes back home, i'm on other side of the planet atm ;P
