### ISSUE TITLE
No module named js2py

### ISSUE THREAD

**Issue by noembryo** [VeNoMouS/cloudscraper#70]
This is a really strange problem..
I was using cloudscrape in an RSS feed reader ([Feedani](http://www.noembryo.com/apps.php?feedani)), and the last compiling (with PyInstaller) was done in May 16.
After that I had some holidays and when I returned I updated the lib to the 1.1.40 version.
I re-compiled the app, but now, if a url is CloudFlare blocked, I get this error:
```python
Traceback (most recent call last):
  File "secondary.py", line 1073, in process
  File "secondary.py", line 1196, in get_feeds
  File "secondary.py", line 1260, in get_page
  File "site-packages\requests\sessions.py", line 537, in get
  File "site-packages\cloudscraper\__init__.py", line 145, in request
  File "site-packages\cloudscraper\__init__.py", line 220, in sendChallengeResponse
ValueError: Unable to parse Cloudflare anti-bots page: No module named js2py Cloudflare may have changed their technique, or there may be a bug in the script.
```
When I run the code from the IDE it still works OK.
At first, I added the `js2py` as a hidden import to the PyInstaller's `.spec` file, but it didn't help.
Another thing I tried was to import `js2py` in the `__init__` of the cloudscraper but it also failed.

So, I tried to downgrade the lib.
Since I don't remember the version I had when I last compiled the app, I went all the way to 1.1.13.
The same error.
I then tried with a backup of the Python folder, that had the 1.1.11 version.
Still nothing.
Finally I downloaded the files for as back as the 1.1.5 version using github archives.
The same error (actually, older versions got only the `ValueError:  No module named js2py` part of the error string).

So, does anyone has any idea what might be the problem?
It could be something obvious that I'm missing here, since nobody else is reporting this, but I run out of option... :o(

TIA

EDIT: Specs
Windows7 SP1x64
Python 2.7.15
Js2Py 0.66
pyOpenSSL 19.0.0
requests 2.20.0
Brotli 1.0.7
requests_toolbelt 0.9.1

**Comment by VeNoMouS** [comment]
Refer #72 please.
