### ISSUE TITLE
Need an API which turns body and domain into url

### ISSUE THREAD

**Issue by Hecate2** [VeNoMouS/cloudscraper#71]
Would you please add a function which allows me to input the response body (the HTML of 'checking yor browser…') and domain, to obtain the url (containing jschl _answer) I shall GET? 
It's not easy to derive such a function from the source code of cloudscraper. The function will enable asyncronous spiders to work fluently!

**Comment by VeNoMouS** [comment]
kinda of defaults the purpose of the library but you could try call something like...

```python
from cloudscraper.interpreters import JavaScriptInterpreter
jschl_answer = JavaScriptInterpreter.dynamicImport('js2py').solveChallenge(body, domain)
```

**Comment by VeNoMouS** [comment]
Would it not be easier to call __get_cookie_string()__ or __get_tokens()__? https://github.com/VeNoMouS/cloudscraper#integration-examples

**Comment by Hecate2** [comment]
> from cloudscraper.interpreters import JavaScriptInterpreter
> params['jschl_answer'] = JavaScriptInterpreter.dynamicImport('js2py').solveChallenge(body, domain)
> solveURL = 'https://{}/cdn-cgi/l/chk_jschl?{}'.format(domain, urllib.urlencode(params))

It works ! Thank you very much!

**Comment by VeNoMouS** [comment]
Sorry I know you guys haven't much more on this since i posted an ad-hoc solution, I am implementing a solution for you in 1.1.43

**Comment by ViRb3** [comment]
Any update on this? Would love a more elegant solution

**Comment by VeNoMouS** [comment]
It's been pending for awhile now... its being tested by some users... and the latest cipher suite issues has just been holding me up, I haven't forgotten about you mate

I've been busy with personal projects as well

Here's a proof shot for you ;P

![image](https://user-images.githubusercontent.com/597545/66174909-c8912280-e6b3-11e9-8b1a-2d44efba08c6.png)

**Comment by ViRb3** [comment]
No rush at all, just wanted to check the status. Many thanks!

**Comment by VeNoMouS** [comment]
There you go boys, it's in release 1.2.0 for you...

https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L261

can be called via `cloudscraper().IUAM_Challenge_Response(body, domain, interpreter)`


Sorry about the massive delay.

Enjoy :)
- VeNoMouS
