### ISSUE TITLE
ERROR:root:Unable to load nodejs interpreter

### ISSUE THREAD

**Issue by j0el99** [VeNoMouS/cloudscraper#72]
I am getting this error when running the latest version of Cloudscraper to scrape a CF protected page. The page is : hdfilme.cc and they use the normal 5 seconds waiting page by CF. I also tried with other sites, but still the same error. 
I installed NodeJS (version 10.9.0) on my machine like required and the following is a code-snippet, I use, where that error gets thrown. 
self.scraper=cloudscraper.create_scraper(interpreter='nodejs')
home_page=self.scraper.get(self.url)
soup=bs(home_page.text, 'lxml')

After the home_page request it logs the ERROR.root thing and crashes with following Exception: 

ModuleNotFoundError: No module named 'cloudscraper.interpreters.nodejs'
[5884] Failed to execute script scr_hdfilme

The same also happens if I try to use interpreter='js2py'

The only weird thing is, it happens only when I use it as a Pyinstaller exe, so that I can run the script from my office computer without need to install my whole Py environment... If I use the normal PC and run it purely in Python (3.7.0) it works fine. Due you have any clue what this could be associated to? It didn't happen with the old cloudscraper version, updated to the current one last night and started having these issues.
I would appreciate any help. If you think this is inappropriated, just close the issue and I will respect your decision.

**Comment by VeNoMouS** [comment]
https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#listing-hidden-imports

https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/interpreters/__init__.py#L29

**Comment by VeNoMouS** [comment]
You could also... (not saying it would work...)
replace 

```python
 __import__('{}.{}'.format(cls.__module__, name))
```
With something like.. (untested)

```python
import importlib
importlib.import_module(name)
```

**Comment by VeNoMouS** [comment]
Also... __NOTHING__ has changed at all in regards to dynamic interpreter loading in 3+ months...

**Comment by j0el99** [comment]
Okay appreciate your answers, very weird it suddenly started giving errors. I tried checking if it was packed by unpacking the exe and seems that the nodejs interpreter was missing in the PYZ created by PyInstaller. 
Thanks a lot for your disponibility, I will look to try with hidden imports now. Best wishes and have a good weekend!

**Comment by VeNoMouS** [comment]
you too mate :)

**Comment by VeNoMouS** [comment]
#70 , @noembryo

**Comment by j0el99** [comment]
Right have seen the #70 issue just now! Thanks and sorry for eventually wasting your time with some stuff you already answered previously. :))

**Comment by VeNoMouS** [comment]
A question is never wasted time mate, at least you reached out and tried to fix it, and it'll help with people in the future asking the same thing.

**Comment by VeNoMouS** [comment]
Honestly in encourage people to ask questions, its how you learn and grow.

**Comment by j0el99** [comment]
Definitely right with that! I am glad that this can contribute the community and really respect all the effort and patience you put in to mantain this huge project... Really appreciate it all

**Comment by VeNoMouS** [comment]
Cheers man :)

**Comment by noembryo** [comment]
> The code dynamically loads interpreters from the interpreter directory https://github.com/VeNoMouS/cloudscraper/tree/master/cloudscraper/interpreters, i don't think its packaging it in your pyinstaller perhaps?

Tried with the `interpreters` folder manually added with no luck.
Hidden imports didn't help either...

I might be missing for some days due to holidays, so best of luck with this ;o)
I'll check it again when I'm back with a PC.

Thanks for your time..

**Comment by VeNoMouS** [comment]
I had a play... (i dont use pyinstaller)

However the following worked fine for me...
```bash
pyinstaller  test.py --add-data='/usr/local/lib/python3.7/dist-packages/cloudscraper/:cloudscraper' --add-data='/usr/local/lib/python3.7/dist-packages/requests/:requests' --onefile --hidden-import=js2py
```

```
root@xxxxxxx:/tmp# dist/test
< GET / HTTP/1.1
< Host: japscan.to
< User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.24.2840.71 Safari/537.36
< DNT: 1
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate, br
<

> HTTP/1.1 503 Service Temporarily Unavailable
> Date: Sun, 25 Aug 2019 01:43:00 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> Set-Cookie: __cfduid=d645c313161c2520fad7f8c0ba358aafc1566697380; expires=Mon, 24-Aug-20 01:43:00 GMT; path=/; domain=.japscan.to; HttpOnly
> X-Frame-Options: SAMEORIGIN
> Cache-Control: no-cache
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 50b9df64ada71912-AKL
.....
< GET /cdn-cgi/l/chk_jschl?s=9e632767c5f30f4adc6b57178a6d79f55686e645-1566697380-1800-AYB0abFfiZvWpY1ymVfExD2tnYshhnRz7rQlslQx3SgE0zh5Frv2X9v596Yd9nyxPFUS3o%2BDKqG0iA0SlSdwlgO%2Fyg2sEzvi%2B4mkRxta3BhzJgz3NkFXPZsLkYCdxRjRMA%3D%3D&jschl_vc=3c7c346d79507f055d4fda46f809b64c&pass=1566697384.588-CouSea2kER&jschl_answer=2.4093467846 HTTP/1.1
< Host: japscan.to
< User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.24.2840.71 Safari/537.36
< DNT: 1
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate, br
< Cookie: __cfduid=d645c313161c2520fad7f8c0ba358aafc1566697380
<

> HTTP/1.1 302 Moved Temporarily
> Date: Sun, 25 Aug 2019 01:43:05 GMT
> Content-Type: text/html
> Content-Length: 159
> Connection: keep-alive
> Set-Cookie: cf_clearance=deefff483c8ae23b0a87e166ceec5e875fd8b914-1566697385-14400-150; path=/; expires=Sun, 25-Aug-19 06:43:05 GMT; domain=.japscan.to; HttpOnly
> Location: /
> Server: cloudflare
> CF-RAY: 50b9df80fea3a439-AKL
> X-Frame-Options: SAMEORIGIN
>
.....
200
```

```python3
#!/usr/bin/python3

import cloudscraper

scraper = cloudscraper.create_scraper(debug=True)
print(scraper.get('https://japscan.to/').status_code)
```

**Comment by VeNoMouS** [comment]
At the end of the day, the problem is __pyinstaller__ not including files from the module... it is not __cloudscraper__, frankly, pyinstaller is pretty flawed in its analysis.... it would have also missed out the user agents json file as well.... shitty packager imho ;P

**Comment by j0el99** [comment]
Hey. Thanks for your latest comments. I tried to do the same now. Didn't work with hidden imports and so on but worked fine by just appending the data to archive. I copied the requests and cloudscraper folder into my script directory, created the main.spec with pyi-spec and edited the data section to the following ```datas=[('cloudscraper/', 'cloudscraper'), ('requests/', 'requests')],``` including the two libraries like you did above and it worked. Including the nodejs interpreter file as hidden-import it didn't work but appending the data seems to be enough. 
Still thanks for your useful comments and these great contributions to the community!
Best wishes and you got all my respect for opensourcing such an interesting project!

**Comment by noembryo** [comment]
Back from some holidays and trying to make this work using v1.1.43..

Copying the "cloudscraper" and "requests" directories manually (although "requests" were working OK) and adding the "js2py" in `hiddenimports` did not change anything.
Even adding the `js2py` folder didn't do a thing.
The #70 issue still persists.

Checking the differences with you guys, I must also add that I don't use the `onefile` option in pyinstaller and I use Python 2.7.15 in Windows 7SP1 x64

Any thoughts?

**Comment by noembryo** [comment]
Did a little more digging..

The `js2py` module that is missing in the error I get
`ValueError: Unable to parse Cloudflare anti-bots page: No module named js2py Cloudflare may have changed their technique, or there may be a bug in the script.`
is not the system's `js2py` module but the `cloudscraper.interpreters.js2py` one.

That means that perhaps its not a PyInstaller's error but `JavaScriptInterpreter.dynamicImport`'s.
The `__import__` command that is using, might be different between Python 2.7.x and 3.x

Since these importing stuff are too advanced for me, can somebody please create another `JavaScriptInterpreter.dynamicImport` function that always returns the `js2py` interpreter, to test if it will work?
