### ISSUE TITLE
Problem getting cookies

### ISSUE THREAD

**Issue by Fran008** [VeNoMouS/cloudscraper#77]
I have this problem:

When I do this

```
s = requests.Session()
res = s.get('http://arenavision.cc')
cookies = dict(res.cookies)
print cookies
```

I get this correct output message:

`{'__cfduid': 'db525e1fd170d9f44a8006f18e58688701568808549'}`

But when I do this, in the same python program:

`cookie_value, user_agent = cloudscraper.get_cookie_string("http://arenavision.cc")`

I get this error message

`ERROR:root:"http://arenavision.cc" returned an error. Could not collect tokens.`

More things to have into account:

1- Is Debian OS in a Google Cloud account LOCATED IN USA
2- It's not desktop OS, which means I can't watch the original web in a browser
3- When I do "sudo wget http://arenavision.cc" I get

```
--2019-09-18 12:14:52--  http://arenavision.cc/
Resolving arenavision.cc (arenavision.cc)... 104.31.94.29, 104.31.95.29, 2606:4700:30::681f:5e1d, ...
Connecting to arenavision.cc (arenavision.cc)|104.31.94.29|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-09-18 12:14:52 ERROR 403: Forbidden.
```

4- When I do the request.get --not cloudscraper, just python request-- I get this web in text mode, inside python program:
```

<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projec
tion" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/cs
s" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]--
>
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><!--<![endif]--
>
</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">**Please e
nable cookies.**</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
     <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to 
access</span> arenavision.cc</h2>
      </div><!-- /.header -->
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/cdn-cgi/l/chk_captcha" method="get">
  <input type="hidden" name="s" value="1b81a0026a7f5cab5247745693c418800963823b-1568809023-1800-ARy/uLUnNkVQWdy52S3
zG29zaqQketOnk8QBTbCRCKCUTllfD5Jt+FekXziolL2hmg72YYzAcO5dlQp0AsFb7GP3gWYSH+0iNc4DSGGqQD4wF6rCQAs3lAyr/USs8WvaWOitSC
+CfXPNVcsz+GsVfjduRWwVluqsB4hP754s4HQhM8zft8z9e9OJdFZPTe4cgEWskGUpzu3sgt8NtwxuOVc="></input>
  <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="5183412a0a9ed
50d" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
    <div><div style="width: 302px">
      <div>
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0" fram
eborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
      </div>
      <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25p
x; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
        <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 
250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
        <input type="submit" value="Submit"></input>
      </div>
    </div></div>
  </noscript>
</form>


```

**Comment by VeNoMouS** [comment]
Can you please show user-agent, also what python version are you using? 3.5,3.6,3.7 etc??

**Comment by VeNoMouS** [comment]
I don't think you are showing me the full error, are you sure that the error isnt more along the lines of reCaptcha...

**Comment by Fran008** [comment]
Ok, I have detected a little better the error, and I am now pretty sure that is a bug:

```
import cloudscraper

scraper = cloudscraper.create_scraper(interpreter='nodejs',debug=True)
scraper.recaptcha={  'provider': 'deathbycaptcha',  'username': 'myuser',  'password': 'mypassword'}

web=scraper.get('http://arenavision.cc')
```

This code goes OK, with python and with python3, and the final page beyond cloudflare displays correctly.

But this other code goes wrong:

```
import cloudscraper

scraper = cloudscraper.create_scraper(interpreter='nodejs',debug=True)
scraper.recaptcha={  'provider': 'deathbycaptcha',  'username': 'myuser',  'password': 'mypassword'}

cookie_value, user_agent = cloudscraper.get_cookie_string('http://arenavision.cc')
```

So the bug is finally in the get_cookie_string function, which is not getting the recaptcha provider given in the scraper instance. I know that I call 'cloudscraper.get_cookie_string' and not 'scraper.get_cookie_string' but before using recaptcha providers it worked.

**Comment by VeNoMouS** [comment]
Ok i'll look that tomorrow if you don't mind, as its almost 10pm here and i only just got home

**Comment by VeNoMouS** [comment]
@Fran008 , if you are encountering a reCaptcha via

```
python
cookie_value, user_agent = cloudscraper.get_cookie_string('http://arenavision.cc')
```

you need to pass reCaptcha params...

for example..
```
cookie_value, user_agent = cloudscraper.get_cookie_string(
    'http://arenavision.cc',
    recaptcha={ 'provider': 'deathbycaptcha',  'username': 'myuser',  'password': 'mypassword'}
)
```

Also check that the reCaptcha isn't releated to 1.1.43, as there was an issue under ubuntu calling reCaptcha &| addtional challenges to trigger 

But... ultimately if you are triggering reCaptcha due to whatever reason, you will need to solve the captcha.

**Comment by VeNoMouS** [comment]
@Fran008 

Heres a logic flow if you wanna learn whats going on..

![image](https://user-images.githubusercontent.com/597545/65290146-1e3cd980-dba2-11e9-91c5-41a4c0faff94.png)

**Comment by Fran008** [comment]
Thank you for the explanations. Do I have to update? With the same version, not updating, I got this error message --because it does not recognize the parameter 'recaptcha' in get_cookie_string:

>>> cookie_value, user_agent = cloudscraper.get_cookie_string('http://arenavision.cc',recaptcha={'provider': 'death
bycaptcha', 'username': 'myusername', 'password': 'mypassword'})
ERROR:root:"http://arenavision.cc" returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.1.42-py2.7.egg/cloudscraper/__init__.py", line 295, i
n get_cookie_string
    tokens, user_agent = cls.get_tokens(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.1.42-py2.7.egg/cloudscraper/__init__.py", line 263, i
n get_tokens
    resp = scraper.get(url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.1.42-py2.7.egg/cloudscraper/__init__.py", line 123, i
n request
    resp = super(CloudScraper, self).request(method, url, *args, **kwargs)
TypeError: request() got an unexpected keyword argument 'recaptcha'

**Comment by VeNoMouS** [comment]
Let me look into that mate 👀

**Comment by VeNoMouS** [comment]
Uhhh.... 

```
>>> import cloudscraper
>>> cloudscraper.get_cookie_string('http://arenavision.cc',recaptcha={'provider': 'deathbycaptcha', 'username': 'myusername', 'password': 'mypassword'})
('__cfduid=da1982b0facd8f2b7bb6ae8106a6f72371568962804; cf_clearance=3eac074a6a3caa47cd12ff1139f352ebc4c950c7-1568962804-1800-150', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.6.3) Gecko/20100101 Firefox/60.6.3')
>>>
```

**Comment by VeNoMouS** [comment]
Can you please 

```python
import cloudscraper
cloudscraper.__version__
```

and show me? thanx...

**Comment by Fran008** [comment]
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
>>> cookie_value, user_agent = cloudscraper.get_cookie_string('http://arenavision.cc',recaptcha={'provider': 'death
bycaptcha', 'username': 'Fran008', 'password': '12340007aA@'})
ERROR:root:"http://arenavision.cc" returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.42-py3.5.egg/cloudscraper/__init__.py", line 295, i
n get_cookie_string
    tokens, user_agent = cls.get_tokens(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.42-py3.5.egg/cloudscraper/__init__.py", line 263, i
n get_tokens
    resp = scraper.get(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.42-py3.5.egg/cloudscraper/__init__.py", line 123, i
n request
    resp = super(CloudScraper, self).request(method, url, *args, **kwargs)
TypeError: request() got an unexpected keyword argument 'recaptcha'
>>> cloudscraper.__version__
'1.1.42'
```

**Comment by Fran008** [comment]
Look at the last line, including version. I'll make the test with python2 too --see next comment

**Comment by Fran008** [comment]
```
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
>>> cookie_value, user_agent = cloudscraper.get_cookie_string('http://arenavision.cc',recaptcha={'provider': 'death
bycaptcha', 'username': 'Fran008', 'password': '12340007aA@'})
ERROR:root:"http://arenavision.cc" returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.1.42-py2.7.egg/cloudscraper/__init__.py", line 295, i
n get_cookie_string
    tokens, user_agent = cls.get_tokens(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.1.42-py2.7.egg/cloudscraper/__init__.py", line 263, i
n get_tokens
    resp = scraper.get(url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.1.42-py2.7.egg/cloudscraper/__init__.py", line 123, i
n request
    resp = super(CloudScraper, self).request(method, url, *args, **kwargs)
TypeError: request() got an unexpected keyword argument 'recaptcha'
>>> cloudscraper.__version__
'1.1.42'
```

**Comment by Fran008** [comment]
And OS version:

```
uname -r
4.9.0-8-amd64
```

**Comment by VeNoMouS** [comment]
> And OS version:
> 
> ```
> uname -r
> 4.9.0-8-amd64
> ```

that is the kernel version... not the "os version"

**Comment by VeNoMouS** [comment]
Might want to change your password to dbc... as you posted it..

**Comment by Fran008** [comment]
Thank you, better keep password safe ;)

**Comment by VeNoMouS** [comment]
Can you change https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L258 in /usr/local/lib/python2.7/dist-packages/cloudscraper-1.1.42-py2.7.egg/cloudscraper/__init__.py

to

```python
field: kwargs.pop(field, None) for field in ['allow_brotli', 'browser', 'debug', 'delay', 'interpreter', 'recaptcha'] if field in kwargs
```

**Comment by Fran008** [comment]
Sorry... OS version:

```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch
```

**Comment by Fran008** [comment]
Operating System: Debian GNU/Linux 9 (stretch)
            Kernel: Linux 4.9.0-8-amd64
      Architecture: x86-64``

**Comment by Fran008** [comment]
Your solution has worked!

Now it goes fine in python2.7 having changed line 258.

Thank you very much!

**Comment by VeNoMouS** [comment]
ok so something weird with attributes vs keys ... its better to use the way i posted, so i'll make that change public.

**Comment by Fran008** [comment]
There's a new related issue...

When I do the cloudscrape with the deathbycaptcha provider it always get the tokens... but when I do without provider it RANDOMLY fails, not always. I have made a loop to retrieve the cookies without failing, but it's a workaround a little bit ugly... specially because the web I want to scrape blocks you after some attempts.

I will try to gather more info... but please don't close this issue until we clarify this.

**Comment by Fran008** [comment]
It seems that the difference is not because of the provider... it's because of the interpreter: it's working well if in my program I change the line

`scraper = cloudscraper.create_scraper()`

with

`scraper = cloudscraper.create_scraper(interpreter='nodejs')`

**Comment by Fran008** [comment]
Mmm... no, it fails sometimes too. And it's randomly. With captcha providers works well.

**Comment by VeNoMouS** [comment]
Sounds to me like the site is picking up that your being abusive... and slapping reCaptcha on you, and its not a IUAM challenge issue..

you SHOULD NOT be challenge solving on every single request as you will just get yourself detected, and well your evasion techniques are wrong if you're doing that, its like using a hammer to open an egg..

You should be using the same session for your requests, or storing your cookies away and reloading them when needed if you are doing individual requests outside a shared session.

If there was a issue with IUAM challenges, everyone would be reporting the issue as that is the core 
 function of this library.

**Comment by VeNoMouS** [comment]
kwargs fix pushed in 1.1.44 (e8994348721c373095d5f5409b20218f06408282)

I am closing this issue off

**Comment by VeNoMouS** [comment]
@Fran008 you do understand what i meant by storing the cookies and re-using rather then constantly solving on every single request?

**Comment by Fran008** [comment]
Yes, I do. And knowing that is a great achievement! Thank you for that.

I will get the cookies once a day and store them in my database. Then I will retrieve them everytime I want to access the web. I guess once or twice a day will be enough.

**Comment by Fran008** [comment]
Mmm... I have tried to store and retrieve cookies from my database and it seems that it isn't enought to keep a session alive. Silly me.

Is there a way to persist this session in time? Or do I have to persist the session ONLY in each instance of my executions? If the correct answer is the second one, I have adapted all my programs to use the same cookies in each call, so I guess it's what you recommended.

If it's possible to persist one session by storing it in a database, I still don't know how to do it.

**Comment by VeNoMouS** [comment]
Make sure you are using the same User-Agent with the cookies...

**Comment by VeNoMouS** [comment]
```
If it's possible to persist one session by storing it in a database, I still don't know how to do it.
```

With an upcoming release I want to do, you can pickle dump the whole session, http adaptor with ssl context and all..

that should make your life alot easier

For the moment till that is released, dump your cookies using like __pickle.dumps__ and load them via __pickle.loads__

**Comment by VeNoMouS** [comment]
```python
>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get('https://japscan.to')
<Response [200]>
>>> import pickle
>>>
>>> x = pickle.dumps(scraper.cookies)
>>> x
b'\x80\x03crequests.cookies\nRequestsCookieJar\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00_policyq\x03chttp.cookiejar\nDefaultCookiePolicy\nq\x04)\x81q\x05}q\x06(X\x08\x00\x00\x00netscapeq\x07\x88X\x07\x00\x00\x00rfc2965q\x08\x89X\x13\x00\x00\x00rfc2109_as_netscapeq\tNX\x0c\x00\x00\x00hide_cookie2q\n\x89X\r\x00\x00\x00strict_domainq\x0b\x89X\x1b\x00\x00\x00strict_rfc2965_unverifiableq\x0c\x88X\x16\x00\x00\x00strict_ns_unverifiableq\r\x89X\x10\x00\x00\x00strict_ns_domainq\x0eK\x00X\x1c\x00\x00\x00strict_ns_set_initial_dollarq\x0f\x89X\x12\x00\x00\x00strict_ns_set_pathq\x10\x89X\x10\x00\x00\x00_blocked_domainsq\x11)X\x10\x00\x00\x00_allowed_domainsq\x12NX\x04\x00\x00\x00_nowq\x13Jz\xf5\x85]ubX\x08\x00\x00\x00_cookiesq\x14}q\x15(X\x0b\x00\x00\x00.japscan.toq\x16}q\x17X\x01\x00\x00\x00/q\x18}q\x19X\x08\x00\x00\x00__cfduidq\x1achttp.cookiejar\nCookie\nq\x1b)\x81q\x1c}q\x1d(X\x07\x00\x00\x00versionq\x1eK\x00X\x04\x00\x00\x00nameq\x1fh\x1aX\x05\x00\x00\x00valueq X+\x00\x00\x00df243f31ee15ef94d69272b7605a0bafe1569060208q!X\x04\x00\x00\x00portq"NX\x0e\x00\x00\x00port_specifiedq#\x89X\x06\x00\x00\x00domainq$h\x16X\x10\x00\x00\x00domain_specifiedq%\x88X\x12\x00\x00\x00domain_initial_dotq&\x88X\x04\x00\x00\x00pathq\'h\x18X\x0e\x00\x00\x00path_specifiedq(\x88X\x06\x00\x00\x00secureq)\x89X\x07\x00\x00\x00expiresq*J\xf0(g_X\x07\x00\x00\x00discardq+\x89X\x07\x00\x00\x00commentq,NX\x0b\x00\x00\x00comment_urlq-NX\x07\x00\x00\x00rfc2109q.\x89X\x05\x00\x00\x00_restq/}q0X\x08\x00\x00\x00HttpOnlyq1NsubssX\x0b\x00\x00\x00.japscan.coq2}q3h\x18}q4(X\x08\x00\x00\x00__cfduidq5h\x1b)\x81q6}q7(h\x1eK\x00h\x1fX\x08\x00\x00\x00__cfduidq8h X+\x00\x00\x00d2db18f9fc994014942a1ecb0d51d36981569060211q9h"Nh#\x89h$X\x0b\x00\x00\x00.japscan.coq:h%\x88h&\x88h\'h\x18h(\x88h)\x89h*J\xf3(g_h+\x89h,Nh-Nh.\x89h/}q;X\x08\x00\x00\x00HttpOnlyq<NsubX\x0c\x00\x00\x00cf_clearanceq=h\x1b)\x81q>}q?(h\x1eK\x00h\x1fh=h X<\x00\x00\x00a21795001527e9dc0ebaefb5dd24bae54daa50df-1569060216-1800-150q@h"Nh#\x89h$X\x0b\x00\x00\x00.japscan.coqAh%\x88h&\x88h\'h\x18h(\x88h)\x89h*J\x90\n\x86]h+\x89h,Nh-Nh.\x89h/}qBX\x08\x00\x00\x00HttpOnlyqCNsubX\x07\x00\x00\x00sessionqDh\x1b)\x81qE}qF(h\x1eK\x00h\x1fhDh X\x1a\x00\x00\x00v6qi410per4jmou1blfuaqjos9qGh"Nh#\x89h$X\x0b\x00\x00\x00.japscan.coqHh%\x88h&\x88h\'h\x18h(\x88h)\x89h*Nh+\x88h,Nh-Nh.\x89h/}qIubusuh\x13Jz\xf5\x85]ub.'
>>> scraper = cloudscraper.create_scraper()
>>> scraper.cookies = pickle.loads(x)
>>> scraper.cookies
<RequestsCookieJar[Cookie(version=0, name='__cfduid', value='d2db18f9fc994014942a1ecb0d51d36981569060211', port=None, port_specified=False, domain='.japscan.co', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=1600596211, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False), Cookie(version=0, name='cf_clearance', value='a21795001527e9dc0ebaefb5dd24bae54daa50df-1569060216-1800-150', port=None, port_specified=False, domain='.japscan.co', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=1569065616, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False), Cookie(version=0, name='session', value='v6qi410per4jmou1blfuaqjos9', port=None, port_specified=False, domain='.japscan.co', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='__cfduid', value='df243f31ee15ef94d69272b7605a0bafe1569060208', port=None, port_specified=False, domain='.japscan.to', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=1600596208, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False)]>
>>>
```

^^ as an example

**Comment by Fran008** [comment]
Great, great, GREAT!!

It's working now storing cookies and user-agent. I just needed the user-agent too. I am making this manually in my database, I won't use pickle by the moment but thank you sooo much for the patience and the info. You're awesome.

**Comment by VeNoMouS** [comment]
All good man, knowledge should be shared :)

Drop me a line if you got any more queries :)

- VeNoMouS
