### ISSUE TITLE
Cloudfare Error : Access denied

### ISSUE THREAD

**Issue by HiImNatsu** [VeNoMouS/cloudscraper#79]
<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Access denied | haapi.ankama.com used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>

<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1020</span>
          <small class="heading-ray-id">Ray ID: 51c6447bbdb95fdf &bull; 2019-09-26 15:28:24 UTC</small>
        </h1>
        <h2 class="cf-subheadline">Access denied</h2>
      </div>

      <section></section>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>This website is using a security service to protect itself from online attacks.</p>
          </div>

        </div>
      </div>

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>51c6447bbdb95fdf</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: xxxxxxx</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div>

    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};

trying to acces this page : https://haapi.ankama.com/json/Ankama/v2/Account/CreateGuest?game=18&lang=fr

**Comment by VeNoMouS** [comment]
Can you please __debug=True__ and supply me with a dump as when i access the page you have given me "https://haapi.ankama.com/json/Ankama/v2/Account/CreateGuest?game=18&lang=fr" I get

```
{
key: "ankama_captcha_incorrect",
text: "Le code de sécurité est invalide. Merci d'essayer de nouveau."
}```

**Comment by VeNoMouS** [comment]
Ah actually I see what you mean..

**Comment by smartmimo** [comment]
hello venomous, that page requires a request with several parameters, that's why it gives u that error

**Comment by VeNoMouS** [comment]
I need to be able to replicate said error  in order to assess/diagnose and implement a possible fix.

If you don;t want to public post all the information, then email me off the record.

But without further information I'm unable to do anything for you.

**Comment by VeNoMouS** [comment]
Looking at what you have posted, this looks like a reCaptcha?!

**Comment by HiImNatsu** [comment]
it's not recaptcha , i'll send you the code in private

**Comment by VeNoMouS** [comment]
Rgr , got the code from you, sorry only just got home, i'll review it later and get back to you if thats cool?

**Comment by HiImNatsu** [comment]
that's totally cool , thank you
