### ISSUE TITLE
403 Access denied

### ISSUE THREAD

**Issue by ItsASmallWorld** [VeNoMouS/cloudscraper#80]
I am using 2captcha integration and am accessing www.bstn.com.  Using v1.1.43.

> < GET / HTTP/1.1
> < Host: bstn.com
> < user-agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36
> < Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
> < Accept-Language: en-US,en;q=0.5
> < Accept-Encoding: gzip, deflate, br
> < DNT: 1
> < 
> 
> > HTTP/1.1 403 Forbidden
> > Date: Fri, 27 Sep 2019 14:54:06 GMT
> > Content-Type: text/html; charset=UTF-8
> > Transfer-Encoding: chunked
> > Connection: keep-alive
> > Set-Cookie: __cfduid=dca6dcfe3ef919c0b7892f452abf4156f1569596046; expires=Sat, 26-Sep-20 14:54:06 GMT; path=/; domain=.bstn.com; HttpOnly; Secure
> > Cache-Control: max-age=15
> > Expires: Fri, 27 Sep 2019 14:54:21 GMT
> > X-Frame-Options: SAMEORIGIN
> > Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> > Vary: Accept-Encoding
> > Server: cloudflare
> > CF-RAY: 51ce4f975ddcc1d9-IAD
> > Content-Encoding: gzip
> >

**Comment by VeNoMouS** [comment]
@ItsASmallWorld can you please update to the lastest cloudscraper package version, and let me know if you still have a problem please?

thanks

**Comment by ItsASmallWorld** [comment]
Hi I'm still having the same issue using v1.1.47

**Comment by ItsASmallWorld** [comment]
You know what, I think the issue is that my recaptca solver service is taking a long time to finish.   I'll reopen if I continue to experience issues.
