### ISSUE TITLE
Why so many user-agents?

### ISSUE THREAD

**Issue by ViRb3** [VeNoMouS/cloudscraper#82]
I see all of your updates with cipher changes to fix certain user-agent strings, why not use one single user-agent and cipher suite that is well-tested and works?

**Comment by VeNoMouS** [comment]
The problem isn't user-agents, 

Most of the time is a variation of different operating systems using different ciphers and in conjunction with Cloudflare checking specific ciphers being there, I'm also trying to replicate the browser ciphers as close to minimize detection as much as possible, also hence why we have so many different user-agents in the browser.json.

I'm also catering for users using the library on non Cloudscraper sites and using a compatible moderate security cipher suite that suits all needs, hence why I just don't to put what just works solely on Cloudflare.. (if that makes sense?)

On top of Cloudflare changing what it triggers on cipher wise.

I am changing some stuff in the browser.json to break it up a bit more, adding in desktop / mobile sections, so they are split giving the developer more control over their requests

Also help is always welcome if you have a better idea, I'm more than willing to listen to you :)

Cheers for the question, I hope this answered your query :)

- VeNoMouS
