### ISSUE TITLE
It Simply doesen't work

### ISSUE THREAD

**Issue by soermejo** [VeNoMouS/cloudscraper#88]
>>> import cloudscraper
>>> scraper.get("https://altadefinizione01-nuovo.link")
<Response [503]>
>>> 

It gives me 503 everytime.

**Comment by VeNoMouS** [comment]
```python

Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper(browser={'browser': 'chrome', 'mobile': False})
>>> scraper.get('https://altadefinizione01-nuovo.link/')
<Response [200]>
>>>
```

**Comment by soermejo** [comment]
Apparently the site removed cloudflare, but i swear, before wasn't working. 
Proof: try with "https://ggdrop.net"

**Comment by VeNoMouS** [comment]
it's still using cloudflare, you can see it in the headers, however it does not have IUAM enabled,

![image](https://user-images.githubusercontent.com/597545/69675214-041ffa00-1103-11ea-887b-b9124294ac09.png)


I will look at "https://ggdrop.net" in a minute

**Comment by VeNoMouS** [comment]
ok... if this is a __real__ cloudflare.... (which i dont think it is) they have changed their end points... hold up while i investigate if this is actually behind cloudflare, or the site is just faking that it is...

**Comment by VeNoMouS** [comment]
#89 is also related

**Comment by VeNoMouS** [comment]
endpoint is `/?__cf_chl_jschl_tk_` for the challenge solve 

Method is now a __POST__, not a __GET__, parameter's have been removed, and are instead are data in the POST

**Comment by VeNoMouS** [comment]
Give Release 1.2.9 a go

**Comment by LXMedia1** [comment]
Give Release 1.2.9 a go means it should work now ?
1.2.12 still not working

**Comment by VeNoMouS** [comment]
@LXMedia1 got an example?

**Comment by LXMedia1** [comment]
sorry my fould not updated my venv, sorry ;(

**Comment by VeNoMouS** [comment]
All good, next time, can you send examples though with version etc?

I'm actually just pushing out 1.2.13 with some improvements

**Comment by VeNoMouS** [comment]
Enjoy 1.2.13... 

I'm off to work out

**Comment by LXMedia1** [comment]
thx dude
