### ISSUE TITLE
does cloudscraper support getting the javascript load-needed website?

### ISSUE THREAD

**Issue by hahawhy** [VeNoMouS/cloudscraper#90]
hi i want to get the data from one website, but the content need load javascript, when i use cloudscraper to get the website, it just returned some js code, not the text what i want.
so i wonder how to use cloudcraper to get the text content from the website which need to load javascript?

**Comment by VeNoMouS** [comment]
The only Javascript it processes is the javascript from cloudflare is its challenge page , the rest is up to you, the developer , perhaps you would be happier with selenium if you need to fully load and process JavaScript

**Comment by VeNoMouS** [comment]
Do you have an example of said site?

**Comment by VeNoMouS** [comment]
![image](https://user-images.githubusercontent.com/597545/69830197-7b32cb00-1288-11ea-87f0-e445ef7b35fe.png)

**Comment by hahawhy** [comment]
Sorry I'm late..  but thank you very much!! 😄
