### ISSUE TITLE
SSL: SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by mab5vot9us9a** [VeNoMouS/cloudscraper#92]
Hi, thanks so much for your work.

Since CF changed their mechanism yesterday, I was happy to see you were already on it, so I promptly upgraded.

However, now I can't access a certain website anymore, because I think a secure connection is enforced which they do not have set up. The site in question is [http://rmz.cr/](http://rmz.cr/).

The regular request returns the cloudflare landing page.

```python
ret = requests.get(url="http://rmz.cr")
print(ret.content)
```

However when using cloudscraper like this

```python
session = cloudscraper.create_scraper()
ret = session.get(url="http://rmz.cr")
print(ret.content)
```
I get the following error:

```
Traceback (most recent call last):
  File "../tests/cloudscraperTest.py", line 41, in <module>
    ret = session.get(url="http://rmz.cr")
  File "/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/lib/python3.7/site-packages/cloudscraper/__init__.py", line 215, in request
    resp = self.Challenge_Response(resp, **kwargs)
  File "/lib/python3.7/site-packages/cloudscraper/__init__.py", line 437, in Challenge_Response
    **cloudflare_kwargs
  File "/lib/python3.7/site-packages/cloudscraper/__init__.py", line 193, in request
    super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='rmz.cr', port=443): Max retries exceeded with url: /?__cf_chl_jschl_tk__=8c483c95c617df1dd55c44e15b517631c655e2eb-1574895185-0-AbmprNY1_xwTORnOFSKxOt6kuMhw0NemJAyKkm2DVrHLLV0PJEs9RzhIqiNh0Mdxy5XPuLUhXGWN9RpjjxrDG_EIaTdY0Sit58C1G3nZWiRHAfIcxJM6i0dqbNwYEoyjiVGggoN9v312z-sGsyf68fRFrJ5jWMMkPE7u7j7SIlKbsAV6BbgIxXq9lD8SGDaPQjPu2pfSXH0U72LzRx2BZtp0cRmOVPiIq7XvgFbX5dI9YxL3gJ-MioQDn16LRv7jDMmxl8TTjIQss7yqzp2y6rM (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1076)')))
```

The following is the output from `pip freeze`:
```
Brotli==1.0.7
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
cloudscraper==1.2.13
cryptography==2.8
idna==2.8
Js2Py==0.66
pycparser==2.19
pyjsparser==2.7.1
pyOpenSSL==19.1.0
pytz==2019.3
requests==2.22.0
requests-toolbelt==0.9.1
six==1.13.0
tzlocal==2.0.0
urllib3==1.25.7
```

Might it be that you are enforcing secure connections along the way somewhere? 
Or do you possibly have another suggestion on how to handle this problem?
TIA

**Comment by VeNoMouS** [comment]
That was/is my fault... in assuming that every normal person in the world would be using cloudflare with SSL.... 

![image](https://user-images.githubusercontent.com/597545/69766061-47e63280-11db-11ea-85d9-78220f113dc7.png)

I will push a fix out for this later today... and __THANK YOU, SO MUCH__ you are one of those RARE people who actually supply enough information in a ticket, without me requiring to go back and ask for more information...

I've actually just written the fix for you... but i'll I need to test out some more things... either way it'll be released today for you :)

**Comment by mab5vot9us9a** [comment]
Yeah, I was rather shocked as well that they don't have any SSL set up! 

Glad I could provide the necessary information :) And thank you again for your work!

**Comment by VeNoMouS** [comment]
@mab5vot9us9a , thanks heaps for the coffee's mate, I have pushed 1.2.14 to pypi and to the git repo... should resolve your issue, can you test it out and let me know please :)

**Comment by mab5vot9us9a** [comment]
My pleasure!

Yes, just tried it out and it works as beautifully as before 🙌

Thanks a bunch!!
