### ISSUE TITLE
about re pattern 

### ISSUE THREAD

**Issue by alzamer2** [VeNoMouS/cloudscraper#97]
https://github.com/VeNoMouS/cloudscraper/blob/265c2a56a5fb32026fab238d192e408aafeaa1a7/cloudscraper/__init__.py#L285
hi i tried to fix my scrapper and found out from lastest IUM  you better change (r|jschl_vc|pass) to (r|s|jschl_vc|pass) as it some times ask for s instead of r (of course you need to edit the rest of code too

**Comment by VeNoMouS** [comment]
Have you got a IUAM challenge source for this?

**Comment by VeNoMouS** [comment]
![](https://media.tenor.com/images/fc01ae3840476fb659d1e19e04fe7252/tenor.gif)

**Comment by alzamer2** [comment]
my bad

**Comment by alzamer2** [comment]
hmmm i could not get the code i tried many time with requests
but both r and s are value for IUMA function so with (r|s|jschl_vc|pass) it will capture what ever is there in html

**Comment by VeNoMouS** [comment]
I'm hesitant to introduce a variable back into the code that was removed due to it being in the old challenge.. 

I will take it on board, but I will not be introducing it back in, until I actually start see'ing some evidence its actually required.

But thank you for raising it as possible bug.
